<h1>Initial EDA for telecom data</h1>

In [1]:
import os
import sys

import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import BernoulliNB, MultinomialNB, GaussianNB
from sklearn.dummy import DummyClassifier

import matplotlib.pyplot as plt

import psycopg2 as pg

Read the data file

In [2]:
test_df = pd.read_csv('../data/WA_Fn-UseC_-Telco-Customer-Churn.csv')

In [3]:
test_df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [4]:
test_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
customerID          7043 non-null object
gender              7043 non-null object
SeniorCitizen       7043 non-null int64
Partner             7043 non-null object
Dependents          7043 non-null object
tenure              7043 non-null int64
PhoneService        7043 non-null object
MultipleLines       7043 non-null object
InternetService     7043 non-null object
OnlineSecurity      7043 non-null object
OnlineBackup        7043 non-null object
DeviceProtection    7043 non-null object
TechSupport         7043 non-null object
StreamingTV         7043 non-null object
StreamingMovies     7043 non-null object
Contract            7043 non-null object
PaperlessBilling    7043 non-null object
PaymentMethod       7043 non-null object
MonthlyCharges      7043 non-null float64
TotalCharges        7043 non-null object
Churn               7043 non-null object
dtypes: float64(1), int64(2), object(18)
memory usage: 1.1+ MB

In [5]:
# The psycopg2 functions don't like numpy number types
test_df['SeniorCitizen'] = [int(test_df.loc[i,'SeniorCitizen'] == 1) for i in test_df.index]

In [6]:
test_df['tenure'] = [int(test_df.loc[i,'tenure']) for i in test_df.index]

Split the data into features and outcome

In [7]:
feature_df = test_df.loc[:, :'TotalCharges']

In [8]:
target_df = test_df['Churn']

Not split off some data for final model scoring and save

In [9]:
# Split the dataset
feature_train, feature_test, targ_train, targ_test = \
    train_test_split(feature_df, target_df, test_size=.25, random_state=42)

In [10]:
# Rejoin the dataset and save the two sections to CSV file
train_df = feature_train.copy()
train_df['Churn'] = targ_train
test_df = feature_test.copy()
test_df['Churn'] = targ_test

In [11]:
train_df.to_csv('../data/telecom_train.csv')
test_df.to_csv('../data/telecom_test.csv')
train_df.dtypes

customerID           object
gender               object
SeniorCitizen         int64
Partner              object
Dependents           object
tenure                int64
PhoneService         object
MultipleLines        object
InternetService      object
OnlineSecurity       object
OnlineBackup         object
DeviceProtection     object
TechSupport          object
StreamingTV          object
StreamingMovies      object
Contract             object
PaperlessBilling     object
PaymentMethod        object
MonthlyCharges      float64
TotalCharges         object
Churn                object
dtype: object

Now split the training data into customer characteristics and account information

In [12]:
customer_cols = ['customerID', 'gender', 'SeniorCitizen', 'Partner', 'Dependents']
account_cols = ['customerID', 'tenure', 'PhoneService', 'MultipleLines', 'InternetService', 'OnlineSecurity', \
               'OnlineBackup', 'DeviceProtection', 'TechSupport', 'StreamingTV', 'StreamingMovies', 'Contract',\
               'PaperlessBilling', 'PaymentMethod', 'MonthlyCharges', 'TotalCharges']
result_cols = ['customerID', 'Churn']

In [13]:
customer_df = train_df[customer_cols]
account_info_df = train_df[account_cols]
target_df = train_df[result_cols]

In [14]:
customer_df.head()

      customerID  gender  SeniorCitizen Partner Dependents
6607  7242-QZLXF    Male              0      No        Yes
2598  8325-QRPZR  Female              0      No         No
2345  7874-ECPQJ  Female              0      No        Yes
4093  2476-YGEFM  Female              0      No         No
693   2276-YDAVZ  Female              0      No         No

Put this data into an sql database

In [15]:
connection_args = {
    'host': 'localhost',  # You will need to put the PUBLIC IP address of your AWS instance here
    'user': 'ubuntu',    # your username on AWS is 'ubuntu'
    'dbname': 'churn_train',    # DB that we are connecting to
    'password' : 'Metis',
    'port': 5432             # port we opened on AWS
}

# We will talk about this magic Python trick!
connection = pg.connect(**connection_args)
cur = connection.cursor()

In [16]:
# Create a table if needed

type_trans = { 'object' : 'varchar(30)',
               'int64' : 'int',
               'float64' : 'float',
                'bool' : 'bit'}
type_mask = { 'object' : '%s ',
                'int64' : '%i ',
                'float' : '%f',
                'bool' : '%i'}

columns = train_df.columns

In [17]:
def create_sql_table_str(name, col_names, dat_types) :
    # Paste a string together to create a table
    test_str = 'CREATE TABLE ' + name + ' ( '
    for i in range(len(col_names)-1) :
        test_str += col_names[i] + ' ' + type_trans[str(dat_types[i])] + ', '
    test_str += col_names[-1] + ' ' + type_trans[str(dat_types[-1])]
    test_str += ')'
    
    return test_str

def create_sql_row_str(frame, col_names, dat_types) :
    # Paste a string together to create a table
    test_str = ' ( '
    for i in range(len(col_names)-1) :
        test_str += col_names[i] + ', '
    test_str += col_names[-1] + ' '
    test_str += ')'
    
    return test_str

In [18]:
cur.execute('begin')

In [19]:
# Create a string to make a table for each of the Dataframes we've created
table_str = create_sql_table_str('customer', customer_df.columns, customer_df.dtypes)
cur.execute(table_str)

table_str = create_sql_table_str('account_info', account_info_df.columns, account_info_df.dtypes)
cur.execute(table_str)

table_str = create_sql_table_str('target_info', target_df.columns, target_df.dtypes)
cur.execute(table_str)

In [25]:
def insert_data_to_sql(frame, table_name, cur) :
    # for each row in the data put the data into the database in the specified table
        # build the command string  
        base_cmd_str = 'INSERT INTO ' + table_name + create_sql_row_str(frame, frame.columns, frame.dtypes) + ' VALUES  ('

        # For each row in the dataframe insert the data
        for j in frame.index :
            cmd_str = base_cmd_str
            
            record_data = tuple(frame.loc[j, :])
        
            for obj in record_data[:-1] :
                if (type(obj) == str) | (type(obj) == bool) :
                    cmd_str += "'" + str(obj) + "', "
                else :
                    cmd_str += str(obj) + ', '
            obj = record_data[-1]
            if (type(obj) == str) | (type(obj) == bool) :
                cmd_str += "'" + str(obj) + "') "
            else :
                cmd_str += str(obj) + ') '           

            cur.execute(cmd_str, record_data)

In [21]:
customer_df.dtypes

customerID       object
gender           object
SeniorCitizen     int64
Partner          object
Dependents       object
dtype: object

In [22]:
# Insert the data into table
insert_data_to_sql(customer_df, 'customer', cur)
insert_data_to_sql(account_info_df, 'account_info', cur)
insert_data_to_sql(target_df, 'target_info', cur)

INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('7242-QZLXF', 'Male', 0, 'No', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('8325-QRPZR', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('7874-ECPQJ', 'Female', 0, 'No', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('2476-YGEFM', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('2276-YDAVZ', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('0661-XEYAN', 'Female', 1, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('1397-XKKWR', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('9249-FXSCK', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('4718-WXBGI', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('0486-HECZI', 'Male', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('7291-CDTMJ', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('7196-LIWRH', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('0625-AFOHS', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('5656-MJEFC', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('5640-CAXOA', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('3946-MHCZW', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('8374-UULRV', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('2108-YKQTY', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('2862-PFNIK', 'Male', 0, 'No', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('2856-HYAPG', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('3707-GNWHM', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('2363-BJLSL', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('3663-MITLP', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('3373-YZZYM', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('5848-FHRFC', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('0840-DFEZH', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('5879-HMFFH', 'Female', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('4723-BEGSG', 'Male', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('3976-BWUCK', 'Female', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('7120-RFMVS', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('8292-FRFZQ', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('9480-BQJEI', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('4350-ZTLPI', 'Female', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('3763-GCZHZ', 'Male', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('1658-XUHBX', 'Female', 1, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('2507-QZPQS', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('0564-JJHGS', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('9750-BOOHV', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('8773-HHUOZ', 'Female', 0, 'No', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('1335-MXCSE', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('6029-CSMJE', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('8707-RMEZH', 'Female', 1, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('0771-CHWSK', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('3703-KBKZP', 'Male', 1, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('9477-LGWQI', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('4893-GYUJU', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('2393-DIVAI', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('0872-JCPIB', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('9909-IDLEK', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('4086-WITJG', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('2874-YXVVA', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('0057-QBUQH', 'Female', 0, 'No', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('4676-MQUEA', 'Male', 1, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('0580-PIQHM', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('5243-SAOTC', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('8347-GDTMP', 'Female', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('5012-YSPJJ', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('5288-AHOUP', 'Male', 1, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('7488-MXJIV', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('9867-XOBQA', 'Female', 0, 'No', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('2511-ALLCS', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('5578-NKCXI', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('1223-UNPKS', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('9087-EYCPR', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('5924-SNGKP', 'Female', 0, 'No', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('1101-SSWAG', 'Female', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('0082-LDZUE', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('2003-CKLOR', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('0679-IDSTG', 'Female', 1, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('7729-JTEEC', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('1550-LOAHA', 'Female', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('8336-TAVKX', 'Female', 1, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('9114-VEPUF', 'Male', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('2688-BHGOG', 'Male', 1, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('2038-OEQZH', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('4767-HZZHQ', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('0093-XWZFY', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('5519-TEEUH', 'Male', 0, 'No', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('1088-CNNKB', 'Male', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('1813-JLKWR', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('4566-NECEV', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('1009-IRMNA', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('7410-OIEDU', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('7549-MYGPK', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('0056-EPFBG', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('5032-USPKF', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('6723-WSNTY', 'Female', 1, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('1195-OIYEJ', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('7964-YESJC', 'Female', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('5995-SNNEW', 'Male', 1, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('9904-EHEVJ', 'Female', 1, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('7876-AEHIG', 'Female', 0, 'No', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('4933-BSAIP', 'Female', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('2978-XXSOG', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('2585-KTFRE', 'Male', 0, 'No', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('4847-TAJYI', 'Female', 1, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('6141-OOXUQ', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('8189-DUKMV', 'Female', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('7752-XUSCI', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('4334-HOWRP', 'Male', 1, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('4445-KWOKW', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('0541-FITGH', 'Female', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('8039-EQPIM', 'Male', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('6474-FVJLC', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('3776-EKTKM', 'Female', 1, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('7036-ZZKBD', 'Male', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('6696-YDAYZ', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('6040-CGACY', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('3006-XIMLN', 'Female', 0, 'No', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('7668-XCFYV', 'Female', 1, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('6101-IMRMM', 'Male', 0, 'No', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('7839-NUIAA', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('7302-ZHMHP', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('7661-CPURM', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('5583-EJXRD', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('7055-JCGNI', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('8946-BFWSG', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('7636-PEPNS', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('7619-PLRLP', 'Female', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('2478-EEWWM', 'Male', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('6305-YLBMM', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('4429-WYGFR', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('6064-PUPMC', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('1097-FSPVW', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('9058-CBREO', 'Female', 1, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('9239-ZBZZV', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('9084-OAYKL', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('5299-SJCZT', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('5231-FIQPA', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('7670-ZBPOQ', 'Female', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('8749-JMNKX', 'Male', 1, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('2067-QYTCF', 'Female', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('3129-AAQOU', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('1036-GUDCL', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('5375-XLDOF', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('3191-CSNMG', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('3874-EQOEP', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('7517-SAWMO', 'Female', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('2609-IAICY', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('2632-TACXW', 'Female', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('3334-CTHOL', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('6513-EECDB', 'Male', 1, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('4945-RVMTE', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('9589-ABEPT', 'Male', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('4248-HCETZ', 'Male', 1, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('1862-SKORY', 'Female', 1, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('1135-LMECX', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('7881-INRLC', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('7163-OCEQI', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('7634-HLQJR', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('4986-MXSFP', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('8066-POXGX', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('5025-GOOKI', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('6425-JWTDV', 'Male', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('8402-EIVQS', 'Male', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('1325-USMEC', 'Male', 0, 'Yes', 'No')

INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('4905-JEFDW', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('6260-XLACS', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('8597-CWYHH', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('3658-QQJYD', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('2180-DXNEG', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('7266-GSSJX', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('5438-QMDDL', 'Female', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('4393-RYCRE', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('7072-MBHEV', 'Female', 1, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('9675-ICXCT', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('6680-NENYN', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('1449-XQEMT', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('6458-CYIDZ', 'Female', 1, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('1142-WACZW', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('3301-VKTGC', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('5244-IRFIH', 'Male', 1, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('4718-DHSMV', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('1891-FZYSA', 'Male', 1, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('1469-LBJQJ', 'Female', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('4115-BNPJY', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('4608-LCIMN', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('5456-ITGIC', 'Male', 1, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('1767-TGTKO', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('2325-WINES', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('8129-GMVGI', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('0940-OUQEC', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('2348-KCJLT', 'Female', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('0461-CVKMU', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('1215-VFYVK', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('4072-IPYLT', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('6173-ITPWD', 'Male', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('7389-KBFIT', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('0731-EBJQB', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('7330-WZLNC', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('9055-MOJJJ', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('9992-UJOEL', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('8388-DMKAE', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('2619-WFQWU', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('7851-FLGGQ', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('7139-JZFVG', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('3771-PZOBW', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('3733-ZEECP', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('4906-ZHGPK', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('7439-DKZTW', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('2592-HODOV', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('7826-VVKWT', 'Female', 1, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('1658-TJVOA', 'Female', 1, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('2439-LYPMQ', 'Male', 1, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('7596-LDUXP', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('4524-QCSSM', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('7816-VGHTO', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('3092-IGHWF', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('6646-QVXLR', 'Male', 1, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('9074-KGVOX', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('5360-XGYAZ', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('0354-WYROK', 'Female', 1, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('9778-OGKQZ', 'Male', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('4139-JPIAM', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('3727-JEZTU', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('3882-IYOIJ', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('4335-UPJSI', 'Female', 0, 'No', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('7760-OYPDY', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('7786-WBJYI', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('4102-HLENU', 'Female', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('7718-UPSKJ', 'Female', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('4110-PFEUZ', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('3768-VHXQO', 'Male', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('3027-ZTDHO', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('4833-QTJNO', 'Male', 1, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('0141-YEAYS', 'Female', 1, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('9822-WMWVG', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('3612-YUNGG', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('7665-TOALD', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('5027-XWQHA', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('9443-JUBUO', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('2325-ZUSFD', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('6953-PBDIN', 'Male', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('3247-ZVOUO', 'Male', 1, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('6629-CZTTH', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('2176-LVPNX', 'Female', 1, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('9505-SQFSW', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('1705-GUHPV', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('7978-DKUQH', 'Female', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('7608-RGIRO', 'Male', 0, 'No', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('3807-BPOMJ', 'Female', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('1960-UOTYM', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('9560-ARGQJ', 'Female', 0, 'No', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('5294-DMSFH', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('2485-ITVKB', 'Female', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('7967-HYCDE', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('2135-DQWAQ', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('5396-IZEPB', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('6022-UGGSO', 'Female', 1, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('7971-HLVXI', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('7021-XSNYE', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('1986-PHGZF', 'Male', 1, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('5118-MUEYH', 'Female', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('3841-NFECX', 'Female', 1, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('3494-JCHRQ', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('5440-VHLUL', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('3154-HMWUU', 'Male', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('0616-ATFGB', 'Male', 1, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('2607-FBDFF', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('3717-LNXKW', 'Male', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('1336-EZFZY', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('7954-MLBUN', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('6646-JPPHA', 'Female', 1, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('0013-SMEOE', 'Female', 1, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('9878-TNQGW', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('9777-IQHWP', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('0570-BFQHT', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('5285-MVEHD', 'Female', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('9093-FPDLG', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('2848-YXSMW', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('0970-QXPXW', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('2522-AHJXR', 'Male', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('9373-WSLOY', 'Male', 1, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('4277-BWBML', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('6156-UZDLF', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('0378-TOVMS', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('2436-QBZFP', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('3402-XRIUO', 'Female', 1, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('4929-BSTRX', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('0285-INHLN', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('4501-EQDRN', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('0337-CNPZE', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('2272-QAGFO', 'Female', 1, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('5027-QPKTE', 'Male', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('5423-BHIXO', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('1338-CECEE', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('2718-GAXQD', 'Female', 1, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('4521-WFJAI', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('3336-JORSO', 'Female', 1, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('5485-WUYWF', 'Male', 1, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('8868-WOZGU', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('7246-ZGQDF', 'Female', 0, 'No', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('2967-MXRAV', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('4512-ZUIYL', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('8361-LTMKD', 'Male', 1, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('2697-NQBPF', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('6872-HXFNF', 'Female', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('1386-ZIKUV', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('2330-PQGDQ', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('1930-BZLHI', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('2999-AANRQ', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('5198-EFNBM', 'Male', 1, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('8185-UPYBR', 'Male', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('5780-INQIK', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('6791-YBNAK', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('5931-FLJJF', 'Male', 1, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('6131-FOYAS', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('5985-TBABQ', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('4998-IKFSE', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('0980-FEXWF', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('6075-SLNIL', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('7279-BUYWN', 'Female', 1, 'No', 'No')

INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('5320-BRKGK', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('1345-ZUKID', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('0750-EKNGL', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('5685-IIXLY', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('0516-VRYBW', 'Female', 0, 'No', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('1069-QJOEE', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('3174-AKMAS', 'Female', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('2207-NHRJK', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('0623-GDISB', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('7570-WELNY', 'Female', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('6954-OOYZZ', 'Male', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('6496-JDSSB', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('2616-FLVQC', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('2865-TCHJW', 'Female', 1, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('4671-VJLCL', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('4525-VZCZG', 'Male', 0, 'No', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('0536-ESJEP', 'Male', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('0270-THENM', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('1636-NTNCO', 'Male', 1, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('1227-UDMZR', 'Female', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('9000-PLFUZ', 'Female', 1, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('6319-IEJWJ', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('9112-WSNPU', 'Female', 1, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('3097-NNSPB', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('1853-ARAAQ', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('4559-UWIHT', 'Male', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('5240-IJOQT', 'Male', 1, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('5642-MHDQT', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('7926-IJOOU', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('5567-GZKQY', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('4256-ZWTZI', 'Female', 0, 'No', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('0678-RLHVP', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('6469-QJKZW', 'Female', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('6988-CJEYV', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('3703-VAVCL', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('3750-CKVKH', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('6424-ELEYH', 'Female', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('4626-GYCZP', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('2599-CZABP', 'Male', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('7780-OTDSO', 'Male', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('5022-KVDQT', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('8232-CTLKO', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('5129-HHMZC', 'Female', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('6993-YGFJV', 'Male', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('3144-KMTWZ', 'Male', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('5371-VYLSX', 'Female', 1, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('4163-HFTUK', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('7336-RLLRH', 'Male', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('1403-GYAFU', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('4713-LZDRV', 'Female', 1, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('1213-NGCUN', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('4523-WXCEF', 'Female', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('5747-PMBSQ', 'Male', 1, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('4021-RQSNY', 'Male', 1, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('6621-YOBKI', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('4094-NSEDU', 'Female', 1, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('6341-AEVKX', 'Female', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('6479-SZPLM', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('6776-TLWOI', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('0106-UGRDO', 'Female', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('4030-VPZBD', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('3106-ULWFW', 'Female', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('1078-TDCRN', 'Female', 1, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('7359-PTSXY', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('4315-MURBD', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('4360-PNRQB', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('6344-SFJVH', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('7854-EDSSA', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('1809-DMJHQ', 'Female', 0, 'No', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('1535-VTJOQ', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('9091-WTUUY', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('6559-PDZLR', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('9090-SGQXL', 'Male', 1, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('2525-GVKQU', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('2519-TWKFS', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('5044-XDPYX', 'Female', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('4646-QZXTF', 'Female', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('5986-WWXDV', 'Male', 0, 'No', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('1027-LKKQQ', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('1194-HVAIF', 'Female', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('9711-FJTBX', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('7416-CKTEP', 'Female', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('6591-QGOYB', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('5909-ECHUI', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('7601-GNDYK', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('5924-IFQTT', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('2984-RGEYA', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('9374-YOLBJ', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('0927-LCSMG', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('8628-MFKAX', 'Female', 1, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('7938-OUHIO', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('7470-DYNOE', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('2240-HSJQD', 'Male', 0, 'No', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('2674-MIAHT', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('8390-FESFV', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('2273-QCKXA', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('0239-OXEXL', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('0228-MAUWC', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('9297-EONCV', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('9650-VBUOG', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('5569-IDSEY', 'Male', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('3473-XIIIT', 'Female', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('6425-YQLLO', 'Female', 1, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('0094-OIFMO', 'Female', 1, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('7233-PAHHL', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('5213-TWWJU', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('3751-KTZEL', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('3831-YCPUO', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('2892-GESUL', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('9732-OUYRN', 'Female', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('2080-CAZNM', 'Female', 1, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('0515-YPMCW', 'Male', 0, 'No', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('1989-PRJHP', 'Male', 1, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('3675-EQOZA', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('2144-ESWKO', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('9308-ANMVE', 'Male', 0, 'No', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('8885-QSQBX', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('9474-PHLYD', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('1077-HUUJM', 'Female', 0, 'No', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('4881-GQJTW', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('3503-TYDAY', 'Female', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('2683-BPJSO', 'Male', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('4163-NCJAK', 'Female', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('2229-VWQJH', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('5294-CDGWY', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('7781-EWARA', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('3566-VVORZ', 'Female', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('7526-IVLYU', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('8058-JMEQO', 'Female', 1, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('9938-EKRGF', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('0480-KYJVA', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('2495-TTHBQ', 'Female', 0, 'No', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('7663-YJHSN', 'Female', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('7665-VIGUD', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('6235-VDHOM', 'Female', 1, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('7994-UYIVZ', 'Male', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('6712-OAWRH', 'Female', 1, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('2077-DDHJK', 'Female', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('4697-LUPSU', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('3488-PGMQJ', 'Male', 1, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('0030-FNXPP', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('0952-KMEEH', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('7594-LZNWR', 'Male', 1, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('0769-MURVM', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('8706-HRADD', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('2873-ZLIWT', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('8208-EUMTE', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('6933-FHBZC', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('5536-RTPWK', 'Male', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('3764-MNMOI', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('5442-XSDCW', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('5766-FTRTS', 'Male', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('6961-MJKBO', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('5510-BOIUJ', 'Male', 0, 'No', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('6917-YACBP', 'Female', 1, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('6461-SZMCV', 'Female', 0, 'Yes', 'No')

INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('8816-VXNZD', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('0895-LMRSF', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('9283-LZQOH', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('9577-WJVCQ', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('4452-ROHMO', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('4682-BLBUC', 'Male', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('9812-GHVRI', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('7601-DHFWZ', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('0817-HSUSE', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('4598-ZADCK', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('7883-ROJOC', 'Female', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('6145-NNPNO', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('9738-QLWTP', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('9154-QDGTH', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('9430-FRQOC', 'Female', 0, 'No', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('7998-WNZEM', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('2195-ZRVAX', 'Female', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('9722-UJOJR', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('8224-UAXBZ', 'Female', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('8614-VGMMV', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('2904-GGUAZ', 'Female', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('6397-JNZZG', 'Female', 1, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('4598-XLKNJ', 'Female', 1, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('8739-QOTTN', 'Female', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('1635-FJFCC', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('1794-SWWKL', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('0486-LGCCH', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('6509-TSGWN', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('4078-SAYYN', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('7088-FBAWU', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('5268-DSMNQ', 'Female', 1, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('1666-JZPZT', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('9621-OUPYD', 'Female', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('0608-JDVEC', 'Male', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('0979-PHULV', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('9891-NQDBD', 'Female', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('6169-PPETC', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('8873-TMKGR', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('4832-VRBMR', 'Male', 1, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('2878-DHMIN', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('6582-PLFUU', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('3859-CVCET', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('2040-LDIWQ', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('3511-APPBJ', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('3865-QBWSJ', 'Male', 1, 'No', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('5019-GQVCR', 'Male', 1, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('5197-YPYBZ', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('4837-QUSFT', 'Female', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('0916-QOFDP', 'Female', 1, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('6331-EWIEB', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('5181-OABFK', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('6743-HHQPF', 'Male', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('1391-UBDAR', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('7314-OXENN', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('1465-WCZVT', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('3428-XZMAZ', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('1093-YSWCA', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('1230-QAJDW', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('8605-ITULD', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('2181-TIDSV', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('1722-LDZJS', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('5298-GSTLM', 'Female', 1, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('4274-DRSQT', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('9473-CBZOP', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('6705-LXORM', 'Female', 1, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('2778-OCLGR', 'Male', 1, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('5906-CVLHP', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('6137-NICCO', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('8348-JLBUG', 'Male', 1, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('1930-WNXSB', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('6015-VVHHE', 'Female', 1, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('7869-ZYDST', 'Male', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('0939-YAPAF', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('9294-TDIPC', 'Male', 0, 'No', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('6692-YQHXC', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('8999-XXGNS', 'Female', 1, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('1150-FTQGN', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('6651-RLGGM', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('5684-FJVYR', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('9447-YPTBX', 'Female', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('2740-JFBOK', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('6108-OQZDQ', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('0722-TROQR', 'Female', 1, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('2504-DSHIH', 'Male', 1, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('6229-LSCKB', 'Male', 1, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('9169-BSVIN', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('9512-PHSMG', 'Female', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('1319-YLZJG', 'Male', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('0628-CNQRM', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('2452-SNHFZ', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('7079-QRCBC', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('0866-QLSIR', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('6549-YMFAW', 'Male', 1, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('0618-XWMSS', 'Male', 0, 'No', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('2954-PIBKO', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('4450-YOOHP', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('1258-YMZNM', 'Female', 1, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('5857-XRECV', 'Female', 0, 'No', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('7298-IZWLY', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('8079-XRJRS', 'Male', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('3482-ABPKK', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('7613-LLQFO', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('0390-DCFDQ', 'Female', 1, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('2640-PMGFL', 'Male', 0, 'No', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('7008-LZVOZ', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('7921-BEPCI', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('2205-LPVGL', 'Male', 1, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('3811-VBYBZ', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('2979-SXESE', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('1299-AURJA', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('9244-ZVAPM', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('8592-PLTMQ', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('3537-HPKQT', 'Female', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('0549-CYCQN', 'Male', 1, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('4548-SDBKE', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('1557-EMYVT', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('7056-IMHCC', 'Male', 1, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('9625-RZFUK', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('2346-CZYIL', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('5760-WRAHC', 'Female', 1, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('4369-HTUIF', 'Male', 1, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('5898-IGSLP', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('2250-IVBWA', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('5324-KTGCG', 'Male', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('8819-WFGGJ', 'Male', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('9108-EJFJP', 'Female', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('7426-GSWPO', 'Male', 1, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('3234-VKACU', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('5522-JBWMO', 'Male', 0, 'No', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('1104-FEJAM', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('5067-DGXLL', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('3398-GCPMU', 'Female', 1, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('3736-BLEPA', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('2696-ECXKC', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('2296-DKZFP', 'Female', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('9971-ZWPBF', 'Male', 1, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('2634-HCZGT', 'Male', 1, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('7696-CFTAT', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('2189-WWOEW', 'Female', 0, 'No', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('5702-KVQRD', 'Male', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('4343-EJVQB', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('3022-BEXHZ', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('2279-AXJJK', 'Male', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('8213-TAZPM', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('6778-EICRF', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('2272-UOINI', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('7452-FOLON', 'Male', 0, 'No', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('1215-EXRMO', 'Male', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('9571-EDEBV', 'Male', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('0854-UYHZD', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('8992-CEUEN', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('0082-OQIQY', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('0822-QGCXA', 'Female', 1, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('5306-BVTKJ', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('2472-OVKUP', 'Male', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('8097-OMULG', 'Male', 0, 'Yes', 'Yes')

INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('7560-QRBXH', 'Female', 0, 'No', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('0040-HALCW', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('2971-SGAFL', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('1845-CSBRZ', 'Female', 1, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('4819-HJPIW', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('0577-WHMEV', 'Female', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('7563-BIUPC', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('9504-YAZWB', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('6896-SRVYQ', 'Male', 1, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('8761-NSOBC', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('4701-LKOZD', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('4587-VVTOX', 'Female', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('0983-TATYJ', 'Female', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('8084-OIVBS', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('0402-OAMEN', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('7363-QTBIW', 'Female', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('0230-UBYPQ', 'Male', 1, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('5808-TOTXO', 'Female', 0, 'No', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('3186-AJIEK', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('8404-VIOMB', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('8040-MNRTF', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('8294-UIMBA', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('9506-UXUSK', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('9488-FVZCC', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('9415-TPKRV', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('3325-FUYCG', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('5055-MGMGF', 'Female', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('5701-YVSVF', 'Female', 1, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('1439-LCGVL', 'Female', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('9693-XMUOB', 'Male', 1, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('2626-VEEWG', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('1591-XWLGB', 'Female', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('0533-UCAAU', 'Male', 1, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('7110-BDTWG', 'Female', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('7493-GVFIO', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('9838-BFCQT', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('1746-TGTWV', 'Male', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('5937-EORGB', 'Male', 1, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('0793-TWELN', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('6243-OZGFH', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('4119-ZYPZY', 'Male', 1, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('7925-PNRGI', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('5966-EMAZU', 'Male', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('9504-DSHWM', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('3814-MLAXC', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('5150-ITWWB', 'Male', 1, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('4092-OFQZS', 'Male', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('1573-LGXBA', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('5233-GEEAX', 'Male', 1, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('2650-GYRYL', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('5010-IPEAQ', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('5494-WOZRZ', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('3863-QSTYI', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('0673-IGUQO', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('3585-YNADK', 'Female', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('3891-PUQOD', 'Female', 0, 'No', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('4445-ZJNMU', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('5712-VBOXD', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('7873-CVMAW', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('1017-FBQMM', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('6918-UMQCG', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('4391-LNRXK', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('4896-CPRPF', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('2187-PKZAY', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('4203-QGNZA', 'Female', 0, 'No', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('6579-JPICP', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('7694-VLBWQ', 'Male', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('3133-PZNSR', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('9356-AXGMP', 'Male', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('9097-ZUBYC', 'Male', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('0840-DCNZE', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('8780-IHCRN', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('3285-UCQVC', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('1833-VGRUM', 'Female', 1, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('7446-SFAOA', 'Female', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('0836-SEYLU', 'Male', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('1752-OZXFY', 'Male', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('5240-CAOYT', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('2887-JPYLU', 'Female', 0, 'No', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('3021-VLNRJ', 'Female', 0, 'No', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('6257-RJOHI', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('4910-AQFFX', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('0396-YCHWO', 'Male', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('5482-PLVPE', 'Female', 1, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('1830-GGFNM', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('7951-VRDVK', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('3977-QCRSL', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('2615-YVMYX', 'Male', 1, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('0323-XWWTN', 'Male', 0, 'No', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('6974-DAFLI', 'Female', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('0224-HJAPT', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('2386-LAHRK', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('9541-ZPSEA', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('1193-RTSLK', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('3351-NGXYI', 'Female', 1, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('9359-UGBTK', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('9788-HNGUT', 'Male', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('7855-DIWPO', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('5222-JCXZT', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('0975-VOOVL', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('4419-UJMUS', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('4424-TKOPW', 'Male', 1, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('6797-LNAQX', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('6770-XUAGN', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('2640-LYMOV', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('7928-VJYAB', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('6821-BUXUX', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('8917-SZTTJ', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('0947-MUGVO', 'Male', 1, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('8727-XDPUD', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('7305-ZWMAJ', 'Male', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('3413-DHLPB', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('2884-GBPFB', 'Female', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('7480-QNVZJ', 'Male', 1, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('1696-HXOWK', 'Female', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('4480-QQRHC', 'Female', 1, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('8461-EFQYM', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('2429-AYKKO', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('4690-PKDQG', 'Female', 1, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('8961-QDZZJ', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('9330-VOFSZ', 'Female', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('0174-QRVVY', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('8785-EPNCG', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('9115-YQHGA', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('9194-GFVOI', 'Female', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('6595-COKXZ', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('3154-CFSZG', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('0679-TDGAK', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('6434-TTGJP', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('6631-HMANX', 'Male', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('0665-XHDJU', 'Male', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('3428-MMGUB', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('5570-PTWEH', 'Female', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('5712-PTIWW', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('8821-XNHVZ', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('1173-XZPYF', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('3545-CNWRG', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('4806-DXQCE', 'Female', 1, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('0685-MLYYM', 'Female', 1, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('1075-BGWOH', 'Male', 1, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('8443-WVPSS', 'Male', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('4114-QMKVN', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('2038-LLMLM', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('5605-XNWEN', 'Male', 1, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('0426-TIRNE', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('0559-CKHUS', 'Female', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('0203-HHYIJ', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('6094-ZIVKX', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('2897-DOVND', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('8387-MOJJT', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('2587-YNLES', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('6693-FRIRW', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('5976-JCJRH', 'Male', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('6749-UTDVX', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('3552-CTCYF', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('0068-FIGTF', 'Female', 0, 'No', 'No')

INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('2761-XECQW', 'Male', 1, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('7270-BDIOA', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('0052-DCKON', 'Male', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('3235-ETOOB', 'Male', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('3865-YIOTT', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('7771-CFQRQ', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('8111-RKSPX', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('6311-UEUME', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('3963-RYFNS', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('6127-ISGTU', 'Female', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('4234-XTNEA', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('7551-JOHTI', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('3533-UVMOM', 'Male', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('6551-ZCOTS', 'Male', 1, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('9063-ZGTUY', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('4816-LXZYW', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('6937-GCDGQ', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('7321-ZNSLA', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('2057-ZBLPD', 'Female', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('0471-ARVMX', 'Female', 1, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('1984-GPTEH', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('1576-PFZIW', 'Male', 1, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('8378-LKJAF', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('2091-RFFBA', 'Female', 1, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('7153-OANIO', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('3085-QUOZK', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('3850-OKINF', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('1354-YZFNB', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('8183-ONMXC', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('3137-LUPIX', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('3705-RHRFR', 'Female', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('0083-PIVIK', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('8782-NUUOL', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('8000-REIQB', 'Female', 1, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('4191-XOVOM', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('9631-RXVJM', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('2528-HFYZX', 'Male', 1, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('4159-NAAIX', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('1697-NVVGY', 'Male', 1, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('0115-TFERT', 'Male', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('8421-WZOOW', 'Female', 1, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('3345-PBBFH', 'Male', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('6490-FGZAT', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('5317-FLPJF', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('3795-GWTRD', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('8417-GSODA', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('7850-VWJUU', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('1498-DQNRX', 'Female', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('8490-BXHEO', 'Male', 1, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('3160-TYXLT', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('3468-DRVQJ', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('4835-YSJMR', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('6217-TOWGS', 'Female', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('0048-LUMLS', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('3769-MHZNV', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('6668-CNMFP', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('0567-GGCAC', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('0260-ZDLGK', 'Female', 0, 'No', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('3308-JSGML', 'Male', 1, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('0036-IHMOT', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('9763-PDTKK', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('8727-JQFHV', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('4304-TSPVK', 'Female', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('5148-ORICT', 'Female', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('2234-XADUH', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('5383-MMTWC', 'Female', 1, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('8513-OLYGY', 'Male', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('5133-POWUA', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('6244-BESBM', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('1206-EHBDD', 'Female', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('4283-IVYCI', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('9804-ICWBG', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('4759-PXTAN', 'Female', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('2694-CIUMO', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('0219-YTZUE', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('6168-WFVVF', 'Female', 1, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('7794-JASDG', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('0468-YRPXN', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('4973-MGTON', 'Female', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('6543-JXSOO', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('1222-LRYKO', 'Male', 0, 'No', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('5917-HBSDW', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('0496-AHOOK', 'Male', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('2040-VZIKE', 'Female', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('3737-GCSPV', 'Female', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('2578-JQPHZ', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('6674-KVJHG', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('1395-OFUWC', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('6689-KXGBO', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('3389-KTRXV', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('6575-SUVOI', 'Female', 1, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('8107-KNCIM', 'Male', 1, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('4547-KQRTM', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('5566-SOEZD', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('5052-PNLOS', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('7554-NEWDD', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('9708-HPXWZ', 'Male', 1, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('5939-SXWHM', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('7351-KYHQH', 'Female', 1, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('6281-FKEWS', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('1597-FZREH', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('2919-HBCJO', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('5394-SVGJV', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('6112-KTHFQ', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('1898-JSNDC', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('7995-ZHHNZ', 'Male', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('2165-VOEGB', 'Female', 0, 'No', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('7746-QYVCO', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('5126-RCXYW', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('5951-AOFIH', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('2582-FFFZR', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('2758-RNWXS', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('9986-BONCE', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('8559-WNQZS', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('4980-URKXC', 'Male', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('3099-OONVS', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('2710-WYVXG', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('5590-BYNII', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('0265-PSUAE', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('8152-UOBNY', 'Female', 1, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('8003-EWNDZ', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('4404-HIBDJ', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('5959-BELXA', 'Male', 1, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('7643-RCHXS', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('4468-YDOVK', 'Male', 0, 'No', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('8919-FYFQZ', 'Male', 1, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('5565-FILXA', 'Female', 1, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('5815-HGGHV', 'Male', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('1552-AAGRX', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('7269-JISCY', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('5446-DKWYW', 'Female', 1, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('3506-LCJDC', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('0956-ACVZC', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('2482-CZGBB', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('6682-QJDGB', 'Male', 0, 'No', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('3128-YOVTD', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('1090-ESELR', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('9570-KYEUA', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('4707-MAXGU', 'Male', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('7872-BAAZR', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('2592-SEIFQ', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('9603-OAIHC', 'Male', 1, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('0637-UBJRP', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('5057-LCOUI', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('2754-XBHTB', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('6518-KZXCB', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('5331-RGMTT', 'Male', 1, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('1430-SFQSA', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('2889-FPWRM', 'Male', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('2251-PYLPB', 'Male', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('6599-RCLCJ', 'Male', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('5155-AZQPB', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('8167-GJLRN', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('4304-XUMGI', 'Male', 1, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('4510-HIMLV', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('5349-IECLD', 'Male', 0, 'No', 'No')

INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('2208-NQBCT', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('4694-PHWFW', 'Female', 0, 'No', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('7817-BOQPW', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('0042-RLHYP', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('9626-WEQRM', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('5035-BVCXS', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('0423-UDIJQ', 'Male', 1, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('5766-XQXMQ', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('4250-WAROZ', 'Male', 1, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('9057-MSWCO', 'Male', 1, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('6217-KDYWC', 'Male', 0, 'No', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('6390-DSAZX', 'Female', 0, 'No', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('3186-BAXNB', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('8917-FAEMR', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('8204-YJCLA', 'Male', 1, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('8714-EUHJO', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('8878-RYUKI', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('6941-KXRRV', 'Female', 1, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('1894-IGFSG', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('5899-MQZZL', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('9152-AMKAK', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('6135-OZQVA', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('3407-JMJQQ', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('4919-MOAVT', 'Male', 0, 'No', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('5825-XJOCM', 'Male', 0, 'No', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('3948-FVVRP', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('3070-DVEYC', 'Male', 1, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('6240-EURKS', 'Female', 0, 'No', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('7446-YPODE', 'Male', 1, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('2959-FENLU', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('8225-BTJAU', 'Male', 1, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('3247-MHJKM', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('2657-ALMWY', 'Female', 1, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('4452-QIIEB', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('6603-QWSPR', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('9717-IOAAF', 'Male', 0, 'No', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('7254-IQWOZ', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('2460-FPSYH', 'Female', 1, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('0617-FHSGK', 'Male', 0, 'No', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('4250-ZBWLV', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('4495-LHSSK', 'Female', 0, 'No', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('3957-LXOLK', 'Female', 1, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('5781-BKHOP', 'Female', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('6691-CCIHA', 'Female', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('3957-SQXML', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('6416-JNVRK', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('2040-OBMLJ', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('8982-NHAVY', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('9554-DFKIC', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('3797-FKOGQ', 'Male', 0, 'No', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('0691-IFBQW', 'Female', 1, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('0440-QEXBZ', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('8738-JOKAR', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('7410-KTVFV', 'Male', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('2817-LVCPP', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('6497-TILVL', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('0839-JTCUD', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('0128-MKWSG', 'Female', 0, 'No', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('3716-BDVDB', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('7159-NOKYQ', 'Male', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('7714-YXSMB', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('4070-OKWVH', 'Female', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('1689-YQBYY', 'Female', 0, 'No', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('1907-UBQFC', 'Male', 1, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('1895-QTKDO', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('3537-RYBHH', 'Female', 1, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('5414-OFQCB', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('1031-IIDEO', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('3258-SYSWS', 'Male', 1, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('0723-VSOBE', 'Female', 1, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('6188-UXBBR', 'Female', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('1941-HOSAM', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('3633-CDBUW', 'Male', 0, 'No', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('8295-KMENE', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('0125-LZQXK', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('9730-DRTMJ', 'Male', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('1047-RNXZV', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('5699-BNCAS', 'Male', 1, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('0206-TBWLC', 'Female', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('9095-HFAFX', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('3131-NWVFJ', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('0596-BQCEQ', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('5248-RPYWW', 'Female', 1, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('6362-QHAFM', 'Male', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('7394-LWLYN', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('2452-MRMZF', 'Female', 1, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('6609-MXJHJ', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('5981-ITEMU', 'Male', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('0191-EQUUH', 'Female', 0, 'No', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('9253-VIFJQ', 'Male', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('1245-HARPS', 'Female', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('5627-TVBPP', 'Female', 0, 'No', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('1137-DGOWI', 'Female', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('8812-ZRHFP', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('5223-UZAVK', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('0730-BGQGF', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('4430-UZIPO', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('3030-YDNRM', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('2025-JKFWI', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('2332-TODQS', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('3709-OIJEA', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('0930-EHUZA', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('9174-IHETN', 'Female', 0, 'No', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('5724-BIDBU', 'Male', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('1217-VASWC', 'Male', 1, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('1735-XMJVH', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('1791-PQHBB', 'Female', 0, 'No', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('1492-QGCLU', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('3327-YBAKM', 'Female', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('5206-HPJKM', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('9814-AOUDH', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('6888-SBYAI', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('1545-ACTAS', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('7634-WSWDB', 'Female', 0, 'No', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('6818-DJXAA', 'Female', 0, 'No', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('2896-TBNBE', 'Male', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('2498-XLDZR', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('5439-WIKXB', 'Male', 1, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('3393-FMZPV', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('1452-KIOVK', 'Male', 0, 'No', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('5598-IKHQQ', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('5789-LDFXO', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('6620-HVDUJ', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('8659-HDIYE', 'Female', 1, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('5760-IFJOZ', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('7442-YGZFK', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('7537-CBQUZ', 'Male', 1, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('0939-EREMR', 'Female', 0, 'No', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('7395-XWZOY', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('0292-WEGCH', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('4487-ZYJZK', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('5539-TMZLF', 'Male', 1, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('9610-WCESF', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('1264-BYWMS', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('1177-XZBJL', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('6199-IPCAO', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('3800-LYTRK', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('8869-TORSS', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('0667-NSRGI', 'Female', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('2853-CWQFQ', 'Male', 0, 'No', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('3378-AJRAO', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('9495-SKLKD', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('1450-SKCVI', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('8069-YQQAJ', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('4450-DLLMH', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('3340-QBBFM', 'Male', 1, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('5669-SRAIP', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('9220-CXRSC', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('0181-RITDD', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('7878-RTCZG', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('0708-SJDIS', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('3842-QTGDL', 'Male', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('7473-ZBDSN', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('6559-RAKOZ', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('9689-PTNPG', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('5859-HZYLF', 'Male', 0, 'Yes', 'Yes')

INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('0058-EVZWM', 'Female', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('1621-YNCJH', 'Female', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('0818-OCPZO', 'Male', 1, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('5055-BRMNE', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('0406-BPDVR', 'Female', 1, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('0979-MOZQI', 'Male', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('6229-UOLQL', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('3331-HQDTW', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('3023-GFLBR', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('5380-AFSSK', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('6036-TTFYU', 'Female', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('4636-JGAAI', 'Male', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('0193-ESZXP', 'Female', 1, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('8016-ZMGMO', 'Female', 1, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('8327-WKMIE', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('4647-XXZAM', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('2753-JMMCV', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('8701-DGLVH', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('0322-CHQRU', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('7799-DSEWS', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('2239-CGBUZ', 'Female', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('6278-FEPBZ', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('6215-NQCPY', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('0401-WDBXM', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('4573-JKNAE', 'Male', 0, 'No', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('0343-QLUZP', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('6878-GGDWG', 'Female', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('9840-DVNDC', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('0327-WFZSY', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('4770-UEZOX', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('8231-BSWXX', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('5673-FSSMF', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('8086-OVPWV', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('9680-NIAUV', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('1921-KYSAY', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('9334-GWGOW', 'Male', 1, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('6522-YRBXD', 'Male', 1, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('8819-IMISP', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('4652-ODEVH', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('0236-HFWSV', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('5849-ASHZJ', 'Male', 0, 'No', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('6486-LHTMA', 'Female', 1, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('4174-LPGTI', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('7369-TRPFD', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('6207-WIOLX', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('5947-SGKCL', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('0508-OOLTO', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('8182-PNAGI', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('2070-XYMFH', 'Female', 1, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('3530-VWVGU', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('0218-QNVAS', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('7748-UMTRK', 'Female', 1, 'No', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('4847-QNOKA', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('5537-UXXVS', 'Female', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('4727-MCYZG', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('2211-RMNHO', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('3061-BCKYI', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('4464-JCOLN', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('7459-IMVYU', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('8969-PRHFK', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('1550-EENBN', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('8619-IJNDK', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('0795-GMVQO', 'Male', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('3967-KXAPS', 'Male', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('3757-NJYBX', 'Male', 1, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('2951-QOQTK', 'Male', 0, 'No', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('1183-CANVH', 'Female', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('7520-HQWJU', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('2883-ILGWO', 'Male', 1, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('0725-CXOTM', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('3058-WQDRE', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('8931-GJJIQ', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('6786-OBWQR', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('2990-OGYTD', 'Female', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('5875-YPQFJ', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('2984-MIIZL', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('6653-CBBOM', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('2484-DGXPZ', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('7587-RZNME', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('3855-ONCAR', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('2105-PHWON', 'Female', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('4534-WGCIR', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('8815-LMFLX', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('8443-ZRDBZ', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('1591-MQJTP', 'Male', 1, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('1559-DTODC', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('4566-QVRRW', 'Female', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('5092-STPKP', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('3094-JOJAI', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('5650-VDUDS', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('3096-IZETN', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('3254-YRILK', 'Male', 1, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('7813-ZGGAW', 'Male', 1, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('5756-OZRIO', 'Male', 1, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('1016-DJTSV', 'Male', 1, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('5204-HMGYF', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('3669-LVWZB', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('2577-GVSIL', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('1444-VVSGW', 'Male', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('5419-JPRRN', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('4673-KKSLS', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('4441-NIHPT', 'Female', 1, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('3315-IKYZQ', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('4726-DLWQN', 'Male', 1, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('2682-KEVRP', 'Female', 1, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('4730-AWNAU', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('8564-LDKFL', 'Male', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('3097-IDVPU', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('5729-KLZAR', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('6352-TWCAU', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('8263-OKETD', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('6698-OXETB', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('4537-CIBHB', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('3230-JCNZS', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('0264-CNITK', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('1043-UXOVO', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('3410-YOQBQ', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('8375-DKEBR', 'Female', 1, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('4508-OEBEY', 'Male', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('0151-ONTOV', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('5884-GCYMI', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('4355-HBJHH', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('9699-UBQFS', 'Female', 1, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('7658-UYUQS', 'Male', 1, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('4220-TINQT', 'Female', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('7115-IRDHS', 'Female', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('3283-WCWXT', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('1709-EJDOX', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('7244-KXYZN', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('9762-YAQAA', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('2799-TSLAG', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('0235-KGSLC', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('9741-YLNTD', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('3791-LGQCY', 'Female', 1, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('5829-NVSQN', 'Female', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('6551-VLJMV', 'Male', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('1866-ZSLJM', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('0885-HMGPY', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('5656-JAMLX', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('7245-JMTTQ', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('2446-ZKVAF', 'Male', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('6599-CEBNN', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('5998-DZLYR', 'Female', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('4223-WOZCM', 'Male', 1, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('4992-LTJNE', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('8008-ESFLK', 'Female', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('5760-FXFVO', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('3569-EDBPQ', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('3500-NSDOA', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('8571-ZCMCX', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('6686-YPGHK', 'Male', 1, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('7168-HDQHG', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('0310-VQXAM', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('3096-WPXBT', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('2234-EOFPT', 'Male', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('6461-PPAXN', 'Female', 0, 'Yes', 'Yes')

INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('7856-GANIL', 'Male', 1, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('4415-WNGVR', 'Female', 1, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('3481-JHUZH', 'Male', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('0278-YXOOG', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('5227-JSCFE', 'Male', 1, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('2091-GPPIQ', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('9643-YBLUR', 'Male', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('9419-IPPBE', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('2877-VDUER', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('2924-KHUVI', 'Male', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('0439-IFYUN', 'Female', 1, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('2587-EKXTS', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('6661-EIPZC', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('5756-JYOJT', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('3259-FDWOY', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('1480-IVEVR', 'Male', 1, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('8070-AAWZP', 'Male', 1, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('2001-EWBQU', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('2606-RMDHZ', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('5688-KZTSN', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('5956-YHHRX', 'Male', 1, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('6563-VRERX', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('7243-LCGGZ', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('3777-XROBG', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('5081-NWSUP', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('5442-BXVND', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('0612-RTZZA', 'Female', 1, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('5103-MHMHY', 'Female', 0, 'No', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('5269-NRGDP', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('4781-ZXYGU', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('0902-RFHOF', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('8601-QACRS', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('6333-YDVLT', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('5730-RIITO', 'Female', 1, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('8125-QPFJD', 'Female', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('6270-OMFIW', 'Male', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('7879-CGSFV', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('3870-SPZSI', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('8873-GLDMH', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('5716-LIBJC', 'Female', 0, 'No', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('0224-NIJLP', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('4713-ZBURT', 'Male', 0, 'No', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('3870-MQAMG', 'Female', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('3550-SAHFP', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('4700-UBQMV', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('0727-BMPLR', 'Female', 1, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('3627-FHKBK', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('9142-KZXOP', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('5980-BDHPY', 'Male', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('4418-LZMSV', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('8123-QBNAZ', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('5743-KHMNA', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('0781-LKXBR', 'Male', 1, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('9931-KGHOA', 'Female', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('7124-UGSUR', 'Female', 1, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('5329-KRDTM', 'Male', 1, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('1024-VRZHF', 'Male', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('4482-EWFMI', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('0366-NQSHS', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('8752-STIVR', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('8878-HMWBV', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('3050-GBUSH', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('6718-BDGHG', 'Female', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('1830-IPXVJ', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('7481-ATQQS', 'Female', 1, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('5203-XEHAX', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('2740-TVLFN', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('7054-LGEQW', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('3166-PNEOF', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('4585-HETAI', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('0872-CASZJ', 'Male', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('7396-VJUZB', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('7644-OMVMY', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('5847-MXBEO', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('8398-TBIYD', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('2533-TIBIX', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('0761-AETCS', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('1447-PJGGA', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('6986-IJDHX', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('6806-YDEUL', 'Female', 1, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('3688-FTHLT', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('5202-IVJNU', 'Female', 0, 'No', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('0754-EEBDC', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('9572-MTILT', 'Male', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('0197-PNKNK', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('7217-JYHOQ', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('2030-BTZRO', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('8087-LGYHQ', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('7337-CINUD', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('1577-HKTFG', 'Female', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('8184-WMOFI', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('1293-HHSHJ', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('6051-PTVNS', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('3995-WFCSM', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('9253-QXKBE', 'Male', 1, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('2080-GKCWQ', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('2519-ERQOJ', 'Male', 1, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('3074-GQWYX', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('7660-HDPJV', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('4389-UEFCZ', 'Female', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('2856-NNASM', 'Male', 1, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('8065-YKXKD', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('8207-VVMYB', 'Female', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('6365-MTGZX', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('9391-TTOYH', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('6682-VCIXC', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('6121-VZNQB', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('2359-KMGLI', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('8433-WPJTV', 'Female', 1, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('1061-PNTHC', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('8580-AECUZ', 'Male', 1, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('1104-TNLZA', 'Male', 1, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('1442-BQPVU', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('4277-PVRAN', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('6077-BDPXA', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('5143-WMWOG', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('6005-OBZPH', 'Female', 1, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('6894-LFHLY', 'Male', 1, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('2732-ISEZX', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('1481-ZUWZA', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('2782-LFZVW', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('5293-WXJAK', 'Female', 1, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('8444-WRIDW', 'Female', 1, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('0621-TSSMU', 'Male', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('6925-BAYGL', 'Female', 1, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('3237-AJGEH', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('6904-JLBGY', 'Female', 1, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('9620-ENEJV', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('5322-TEUJK', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('9364-YKUVW', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('6463-MVYRY', 'Female', 1, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('6484-LATFU', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('8718-PTMEZ', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('7711-GQBZC', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('8722-NGNBH', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('2432-TFSMK', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('1472-TNCWL', 'Male', 0, 'No', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('0014-BMAQU', 'Male', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('2724-FJDYW', 'Male', 0, 'No', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('4693-VWVBO', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('0301-KOBTQ', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('7044-YAACC', 'Male', 1, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('8290-YWKHZ', 'Female', 1, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('5908-QMGOE', 'Male', 1, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('4795-KTRTH', 'Female', 1, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('5057-RKGLH', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('6341-JVQGF', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('4065-JJAVA', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('2018-QKYGT', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('7379-FNIUJ', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('1970-KKFWL', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('7311-MQJCH', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('5896-NPFWW', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('8791-GFXLZ', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('4979-HPRFL', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('6181-AXXYF', 'Male', 0, 'Yes', 'Yes')

INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('0475-RIJEP', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('8111-BKVDS', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('0224-RLWWD', 'Female', 1, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('6508-NJYRO', 'Male', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('3411-WLRSQ', 'Female', 1, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('8316-BBQAY', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('2150-OEGBV', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('3551-HUAZH', 'Male', 1, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('8884-FEEWR', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('5968-VXZLG', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('3070-BDOQC', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('2821-WARNZ', 'Female', 0, 'No', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('2108-XWMPY', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('8194-PEEBY', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('1832-PEUTS', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('2685-SREOM', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('2657-VPXTA', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('5067-WJEUN', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('2205-YMZZJ', 'Male', 1, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('4277-UDIEF', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('1480-BKXGA', 'Male', 1, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('4648-YPBTM', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('3097-NQYSN', 'Male', 1, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('9250-WYPLL', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('5245-VDBUR', 'Female', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('8468-FZTOE', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('7639-OPLNG', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('8631-XVRZL', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('1051-GEJLJ', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('5753-QQWPW', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('9339-FIIJL', 'Male', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('8644-XYTSV', 'Male', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('6688-UZPWD', 'Female', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('1534-OULXE', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('3902-MIVLE', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('4237-RLAQD', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('1208-DNHLN', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('0704-VCUMB', 'Female', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('2550-QHZGP', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('7817-OMJNA', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('2811-POVEX', 'Female', 1, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('9940-HPQPG', 'Female', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('2012-NWRPA', 'Female', 1, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('5176-LDKUH', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('0281-CNTZX', 'Male', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('3440-JPSCL', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('7284-BUYEC', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('4178-EGMON', 'Male', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('2373-NTKOD', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('4538-WNTMJ', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('1345-GKDZZ', 'Male', 0, 'No', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('8883-ANODQ', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('1488-SYSFC', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('5876-QMYLD', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('3908-BLSYF', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('4317-VTEOA', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('3422-GALYP', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('5461-QKNTN', 'Male', 1, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('9975-GPKZU', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('2284-VFLKH', 'Male', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('8945-MUQUF', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('5149-CUZUJ', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('9614-RMGHA', 'Male', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('5076-YVXCM', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('5088-QZLRL', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('5054-IEXZT', 'Male', 0, 'No', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('3594-BDSOA', 'Female', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('3034-ZBEQN', 'Female', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('7903-CMPEY', 'Male', 1, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('8654-DHAOW', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('2039-JONDJ', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('7623-TRNQN', 'Male', 0, 'No', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('8821-KVZKQ', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('1596-BBVTG', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('4702-HDRKD', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('1501-SGHBW', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('0422-OHQHQ', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('2866-IKBTM', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('5201-CBWYG', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('2642-MAWLJ', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('1240-KNSEZ', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('5286-YHCVC', 'Male', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('8469-SNFFH', 'Male', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('9732-KPKBW', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('9357-UJRUN', 'Male', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('0022-TCJCI', 'Male', 1, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('2829-HYVZP', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('5846-QFDFI', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('0722-SVSFK', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('0947-IDHRQ', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('9903-LYSAB', 'Male', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('3156-QLHBO', 'Male', 0, 'No', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('5321-NTRKC', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('1087-UDSIH', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('7096-ZNBZI', 'Female', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('7399-QHBJS', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('0749-IRGQE', 'Female', 1, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('2960-NKRSO', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('4654-ULTTN', 'Male', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('9715-WZCLW', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('6681-ZSEXG', 'Male', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('9025-AOMKI', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('5077-DXTCG', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('4012-ZTHBR', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('7683-CBDKJ', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('0708-LGSMF', 'Male', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('5519-NPHVG', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('6908-VVYHM', 'Male', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('0215-BQKGS', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('4236-UJPWO', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('7777-UNYHB', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('6815-ABQFQ', 'Male', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('0248-PGHBZ', 'Female', 1, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('2626-URJFX', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('9058-HRZSV', 'Female', 1, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('3716-LRGXK', 'Male', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('2568-OIADY', 'Female', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('7606-BPHHN', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('3253-HKOKL', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('3606-TWKGI', 'Male', 1, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('4007-NHVHI', 'Female', 1, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('4807-IZYOZ', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('0274-JKUJR', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('5935-FCCNB', 'Female', 1, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('2333-KWEWW', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('7103-IPXPJ', 'Male', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('6035-BXTTY', 'Female', 1, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('3765-JXVKY', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('2927-QRRQV', 'Male', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('3181-MIZBN', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('0968-GSIKN', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('0422-UXFAP', 'Female', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('4016-BJKTZ', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('9327-QSDED', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('7841-FCRQD', 'Female', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('7054-DMVAS', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('1092-WPIVQ', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('8763-KIAFH', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('2898-MRKPI', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('0603-TPMIB', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('8023-QHAIO', 'Female', 1, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('0795-XCCTE', 'Male', 1, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('2453-SAFNS', 'Female', 1, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('5176-LMJXE', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('6598-KELSS', 'Male', 0, 'No', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('6257-DTAYD', 'Male', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('2672-OJQZP', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('1320-HTRDR', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('9236-NDUCW', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('0277-ORXQS', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('9412-ARGBX', 'Female', 0, 'No', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('8634-MPHTR', 'Male', 1, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('1599-EAHXY', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('2911-IJORQ', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('2911-WDXMV', 'Male', 0, 'No', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('1775-KWJKQ', 'Male', 0, 'Yes', 'Yes')

INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('4398-HSCJH', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('7595-EHCDL', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('5215-LNLDJ', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('7677-SJJJK', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('9992-RRAMN', 'Male', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('6242-FEGFD', 'Male', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('3956-CJUST', 'Female', 1, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('4844-JJWUY', 'Female', 1, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('3703-TTEPD', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('4282-YMKNA', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('6103-QCKFX', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('4631-OACRM', 'Male', 1, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('3470-OBUET', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('2929-QNSRW', 'Female', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('7853-OETYL', 'Female', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('5318-YKDPV', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('4238-HFHSN', 'Male', 1, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('9209-NWPGU', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('5022-JNQEQ', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('6007-TCTST', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('8357-EQXFO', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('3589-PPVKW', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('1574-DYCWE', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('4999-IEZLT', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('4403-BWPAY', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('1494-EJZDW', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('9766-HGEDE', 'Female', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('4724-WXVWF', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('5469-NUJUR', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('1724-IQWNM', 'Male', 0, 'No', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('8043-PNYSD', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('6734-FQAJX', 'Male', 1, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('9786-YWNHU', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('8760-ZRHKE', 'Female', 1, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('2703-AMTUL', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('4583-PARNH', 'Male', 1, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('6942-LBFDP', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('7203-OYKCT', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('9143-CANJF', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('1723-HKXJQ', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('6619-RPLQZ', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('4791-QRGMF', 'Male', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('6728-VOIFY', 'Female', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('2081-KJSQF', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('3397-AVTKU', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('6365-HITVU', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('2604-XVDAM', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('0487-VVUVK', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('6656-GULJQ', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('6599-SFQVE', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('6754-WKSHP', 'Male', 0, 'No', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('6199-IWKGC', 'Female', 1, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('6221-AVQYL', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('5630-IXDXV', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('7340-KEFQE', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('5542-NKVRU', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('4553-DVPZG', 'Female', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('1925-GMVBW', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('9822-BIIGN', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('9172-ANCRX', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('4695-VADHF', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('3930-ZGWVE', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('1084-MNSMJ', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('3733-UOCWF', 'Male', 1, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('8242-JSVBO', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('3804-RVTGV', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('3904-UKFRE', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('7248-VZQLC', 'Female', 1, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('0257-KXZGU', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('2737-WFVYW', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('5649-TJHOV', 'Male', 1, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('4324-BZCKL', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('5494-HECPR', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('1396-QWFBJ', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('0547-HURJB', 'Male', 0, 'No', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('7239-HZZCX', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('4698-KVLLG', 'Female', 1, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('0319-QZTCO', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('4056-QHXHZ', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('0415-MOSGF', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('6432-TWQLB', 'Male', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('1069-XAIEM', 'Female', 1, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('1767-CJKBA', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('9068-VPWQQ', 'Male', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('8818-XYFCQ', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('8747-UDCOI', 'Female', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('9825-YCXWZ', 'Female', 1, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('2114-MGINA', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('2074-GKOWZ', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('2282-YGNOR', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('8229-MYEJZ', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('4883-QICIH', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('9788-YTFGE', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('3429-IFLEM', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('7649-PHJVR', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('0816-TSPHQ', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('8267-KFGYD', 'Male', 0, 'No', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('9801-NOSHQ', 'Male', 0, 'No', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('7182-OVLBJ', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('4059-IIEBK', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('9258-CNWAC', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('5318-IXUZF', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('8039-ACLPL', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('4817-KEQSP', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('9391-EOYLI', 'Male', 1, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('7963-GQRMY', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('2227-JRSJX', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('3981-QSVQI', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('8076-FEZKJ', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('6304-IJFSQ', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('2834-SPCJV', 'Male', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('1231-YNDEK', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('1866-NXPSP', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('9548-LIGTA', 'Male', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('7064-JHXCE', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('2388-LAESQ', 'Female', 1, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('6300-BWMJX', 'Female', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('4486-EFAEB', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('3161-GETRM', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('9828-AOQLM', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('2433-KMEAS', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('7014-ZZXAW', 'Female', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('4554-YGZIH', 'Male', 1, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('6969-MVBAI', 'Female', 1, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('6376-GAHQE', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('9430-NKQLY', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('4009-ALQFH', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('0023-HGHWL', 'Male', 1, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('1686-STUHN', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('3588-WSTTJ', 'Female', 1, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('2538-OIMXF', 'Female', 0, 'No', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('3806-YAZOV', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('9127-QRZMH', 'Male', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('7607-QKKTJ', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('8665-UTDHZ', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('7398-HPYZQ', 'Male', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('4647-MUZON', 'Female', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('6856-RAURS', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('7250-EQKIY', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('8709-KRDVL', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('6701-YVNQG', 'Male', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('2639-UGMAZ', 'Male', 1, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('2983-ZANRP', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('0508-SQWPL', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('1834-ABKHQ', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('0280-XJGEX', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('0519-XUZJU', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('7434-SHXLS', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('3012-VFFMN', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('7268-IGMFD', 'Male', 1, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('9717-QEBGU', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('5151-HQRDG', 'Male', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('2565-JSLRY', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('0234-TEVTT', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('6862-CQUMB', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('7823-JSOAG', 'Male', 0, 'No', 'No')

INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('0336-PIKEI', 'Male', 1, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('4013-UBXWQ', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('8606-CIQUL', 'Male', 1, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('3404-JNXAX', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('2665-NPTGL', 'Female', 1, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('9278-VZKCD', 'Female', 1, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('9620-QJREV', 'Male', 0, 'No', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('0827-ITJPH', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('0137-UDEUO', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('3878-AVSOQ', 'Female', 1, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('1271-SJBGZ', 'Male', 1, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('0619-OLYUR', 'Male', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('7531-GQHME', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('5178-LMXOP', 'Male', 1, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('2364-UFROM', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('3570-YUEKJ', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('9048-JVYVF', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('4154-AQUGT', 'Male', 1, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('2612-RANWT', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('3768-NLUBH', 'Male', 1, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('9606-PBKBQ', 'Male', 1, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('3442-ZHHCC', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('5726-CVNYA', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('7839-QRKXN', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('5296-BFCYD', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('1960-UYCNN', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('0928-JMXNP', 'Male', 1, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('6185-TASNN', 'Male', 1, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('4750-ZRXIU', 'Female', 1, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('3274-NSDWE', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('5887-IKKYO', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('3439-GVUSX', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('8224-DWCKX', 'Male', 1, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('0266-GMEAO', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('9681-OXGVC', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('2466-FCCPT', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('9046-JBFWA', 'Male', 0, 'No', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('2455-USLMV', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('0326-VDYXE', 'Female', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('6332-FBZRI', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('9631-XEYKE', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('4786-UKSNZ', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('9931-DCEZH', 'Male', 0, 'No', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('4962-CHQPW', 'Male', 0, 'No', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('1602-IJQQE', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('4717-GHADL', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('2522-WLNSF', 'Female', 1, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('9742-XOKTS', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('9958-MEKUC', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('2265-CYWIV', 'Female', 1, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('2123-AGEEN', 'Female', 1, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('2750-BJLSB', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('9496-IVVRP', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('9412-GHEEC', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('2474-BRUCM', 'Male', 1, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('8510-BBWMU', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('5899-OUVKV', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('6134-KWTBV', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('4488-KQFDT', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('3884-UEBXB', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('8735-SDUFN', 'Female', 1, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('8046-DNVTL', 'Male', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('5276-KQWHG', 'Female', 1, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('5090-EMGTC', 'Female', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('5543-QDCRY', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('5248-YGIJN', 'Male', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('8597-CTXVJ', 'Male', 0, 'No', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('9668-PUGNU', 'Male', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('2519-FAKOD', 'Male', 0, 'No', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('4325-NFSKC', 'Male', 1, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('7379-POKDZ', 'Male', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('1548-ARAGG', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('5175-AOBHI', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('9512-UIBFX', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('5313-FPXWG', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('5889-LFOLL', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('2789-HQBOU', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('0875-CABNR', 'Female', 1, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('0487-RPVUM', 'Male', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('1680-VDCWW', 'Male', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('4139-SUGLD', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('4661-NJEUX', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('4079-WWQQQ', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('1236-WFCDV', 'Male', 1, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('6330-JKLPC', 'Male', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('1004-NOZNR', 'Male', 1, 'No', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('5650-YLIBA', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('0690-SRQID', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('3179-GBRWV', 'Male', 1, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('8966-OIQHG', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('1084-UQCHV', 'Male', 0, 'No', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('6507-ZJSUR', 'Male', 1, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('6114-TCFID', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('7025-WCBNE', 'Male', 1, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('9052-VKDUW', 'Female', 1, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('5999-LCXAO', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('0277-BKSQP', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('5593-SUAOO', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('9965-YOKZB', 'Male', 1, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('9026-RNUJS', 'Male', 1, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('8922-LIEGH', 'Female', 1, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('6993-OHLXR', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('7762-ONLJY', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('7216-KAOID', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('9873-MNDKV', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('3565-UNOCC', 'Female', 1, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('7061-OVMIM', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('0675-NCDYU', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('5740-YHGTW', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('9881-VCZEP', 'Female', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('8901-HJXTF', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('1563-IWQEX', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('2886-KEFUM', 'Female', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('6845-RGTYS', 'Female', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('0742-LAFQK', 'Male', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('5366-OBVMR', 'Female', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('0310-SUCIN', 'Female', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('9787-XVQIU', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('6752-APNJL', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('3427-GGZZI', 'Female', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('2984-TBYKU', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('2368-GAKKQ', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('4295-YURET', 'Female', 1, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('8671-KKKOS', 'Female', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('7017-VFULY', 'Female', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('6519-ZHPXP', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('3865-ZYKAD', 'Male', 1, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('2654-VBVPB', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('6532-YLWSI', 'Female', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('4716-MRVEN', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('4950-BDEUX', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('4123-DVHPH', 'Male', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('1169-WCVAK', 'Male', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('3642-GKTCT', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('5515-RUGKN', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('6481-ESCNL', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('2419-FSORS', 'Male', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('0107-YHINA', 'Male', 0, 'No', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('8160-HOWOX', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('3890-RTCMS', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('3787-TRIAL', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('2187-LZGPL', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('9134-CEQMF', 'Male', 1, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('4377-VDHYI', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('9053-JZFKV', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('8849-PRIQJ', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('7901-IIDQV', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('8246-SHFGA', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('2843-CQMEG', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('6635-CPNUN', 'Male', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('4083-BFNYK', 'Female', 1, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('2321-OMBXY', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('7493-TPUWZ', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('8809-RIHDD', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('0302-JOIVN', 'Female', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('4462-CYWMH', 'Male', 1, 'Yes', 'No')

INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('5322-ZSMZY', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('3066-RRJIO', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('2469-DTSGX', 'Female', 1, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('5061-PBXFW', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('7128-GGCNO', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('3597-MVHJT', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('4302-ZYFEL', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('1273-MTETI', 'Female', 1, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('6986-IXNDM', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('2277-AXSDC', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('6729-FZWSY', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('1156-ZFYDO', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('9386-LDCZR', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('3623-FQBOX', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('5948-UJZLF', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('9928-BZVLZ', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('7746-AWNQW', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('2107-FBPTK', 'Female', 1, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('1965-DDBWU', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('6302-JGYRJ', 'Male', 0, 'No', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('6502-KUGLL', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('9866-OCCKE', 'Female', 1, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('9173-IVZVP', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('3893-JRNFS', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('4137-JOPHL', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('4323-OHFOW', 'Female', 1, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('1972-XMUWV', 'Female', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('1915-IOFGU', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('7982-VCELR', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('0699-NDKJM', 'Female', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('4633-MKHYU', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('9269-CQOOL', 'Male', 0, 'No', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('2995-YWTCD', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('5989-AXPUC', 'Female', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('1771-OADNZ', 'Male', 1, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('2739-CACDQ', 'Female', 1, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('8029-XYPWT', 'Male', 1, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('3801-HMYNL', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('6898-RBTLU', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('4822-NGOCH', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('1116-DXXDF', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('1306-RPWXZ', 'Female', 0, 'No', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('5934-RMPOV', 'Female', 0, 'No', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('6897-RWMUB', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('7893-IXHRQ', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('1875-QIVME', 'Female', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('4291-YZODP', 'Female', 0, 'No', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('1635-NZATJ', 'Male', 1, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('9847-HNVGP', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('3519-ZKXGG', 'Female', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('8092-NLTGF', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('1371-WEPDS', 'Male', 1, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('8317-BVKSO', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('2692-AQCPF', 'Female', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('0434-CSFON', 'Female', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('2120-SMPEX', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('3295-YVUSR', 'Male', 1, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('4785-QRJHC', 'Male', 1, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('5793-YOLJN', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('1656-DRSMG', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('9073-ZZIAY', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('0447-BEMNG', 'Female', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('0365-GXEZS', 'Male', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('6339-TBELP', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('9470-XCCEM', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('8224-IVVPA', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('1568-LJSZU', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('9770-LXDBK', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('5006-MXVRN', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('0440-UEDAI', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('0431-APWVY', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('5399-ZIMKF', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('2428-ZMCTB', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('0121-SNYRK', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('8456-QDAVC', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('4644-PIZRT', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('4827-USJHP', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('6621-NRZAK', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('0744-BIKKF', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('1455-HFBXA', 'Male', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('7328-ZJAJO', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('6440-DKQGE', 'Male', 0, 'No', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('3452-GWUIN', 'Female', 1, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('9746-MDMBK', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('9388-ZEYVT', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('3474-BAFSJ', 'Male', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('9102-OXKFY', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('7517-LDMPS', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('6968-URWQU', 'Male', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('8060-HIWJJ', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('4020-KIUDI', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('1363-TXLSL', 'Male', 1, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('7527-QNRUS', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('8651-ENBZX', 'Female', 1, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('3892-NXAZG', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('8740-XLHDR', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('1163-VIPRI', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('6218-KNUBD', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('8640-SDGKB', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('2249-YPRNG', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('4785-FCIFB', 'Female', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('3419-SNJJD', 'Female', 1, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('2121-JAFOM', 'Female', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('3389-YGYAI', 'Female', 1, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('9033-EOXWV', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('6179-GJPSO', 'Female', 1, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('9667-EQRXU', 'Female', 1, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('7824-PANSQ', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('2361-UPSND', 'Female', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('9360-OMDZZ', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('7614-QVWQL', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('0644-OQMDK', 'Male', 1, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('8865-TNMNX', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('1114-CENIM', 'Male', 0, 'No', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('3933-DQPWX', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('7716-YTYHG', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('7927-AUXBZ', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('5630-AHZIL', 'Female', 0, 'No', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('2320-JRSDE', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('9013-AQORL', 'Female', 0, 'No', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('3301-LSLWQ', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('6734-CKRSM', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('7228-PAQPD', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('5628-RKIFK', 'Female', 1, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('5346-BZCHP', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('0739-UUAJR', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('9795-SHUHB', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('9391-LMANN', 'Male', 0, 'No', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('8519-IMDHU', 'Male', 1, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('0621-JFHOL', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('4011-ARPHK', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('6384-VMJHP', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('4338-EYCER', 'Male', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('4074-SJFFA', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('6504-VBLFL', 'Male', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('3457-PQBYH', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('4505-EXZHB', 'Female', 1, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('1429-UYJSV', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('4654-GGUII', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('4029-HPFVY', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('4547-FZJWE', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('7341-LXCAF', 'Male', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('2408-WITXK', 'Female', 1, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('2988-GBIVW', 'Female', 1, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('2589-AYCRP', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('7684-XSZIY', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('7632-MNYOY', 'Male', 1, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('2720-WGKHP', 'Male', 1, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('1121-QSIVB', 'Female', 0, 'No', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('4597-ELFTS', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('5600-PDUJF', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('3452-FLHYD', 'Male', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('7435-ZNUYY', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('3926-CUQZX', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('9651-GTSAQ', 'Female', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('1113-IUJYX', 'Female', 0, 'Yes', 'No')

INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('0263-FJTQO', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('0871-URUWO', 'Male', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('4412-YLTKF', 'Female', 1, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('7392-YYPYJ', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('9435-JMLSX', 'Male', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('7109-MFBYV', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('1608-GMEWB', 'Male', 1, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('4311-QTTAI', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('1169-SAOCL', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('9146-JRIOX', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('4690-LLKUA', 'Male', 1, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('8165-ZJRNM', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('6322-PJJDJ', 'Male', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('0052-YNYOT', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('3689-MOZGR', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('3644-QXEHN', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('9802-CAQUT', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('0104-PPXDV', 'Male', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('9548-ZMVTX', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('0021-IKXGC', 'Female', 1, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('4785-NKHCX', 'Male', 1, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('9695-IDRZR', 'Female', 0, 'No', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('3810-DVDQQ', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('7921-LMDFQ', 'Male', 1, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('8976-OQHGT', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('0697-ZMSWS', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('9189-JWSHV', 'Female', 1, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('4023-RTIQM', 'Female', 1, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('4349-GFQHK', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('8080-DDEMJ', 'Male', 1, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('9871-ELEYA', 'Female', 0, 'No', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('8685-WHQPW', 'Female', 1, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('1855-CFULU', 'Female', 1, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('9848-JQJTX', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('5345-BMKWB', 'Male', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('9136-ALYBR', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('0495-RVCBF', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('2712-SYWAY', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('9846-GKXAS', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('1932-UEDCX', 'Male', 1, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('3567-PQTSO', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('4685-ERGHK', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('0233-FTHAV', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('6166-YIPFO', 'Male', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('0674-DGMAQ', 'Male', 1, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('7064-FRRSW', 'Male', 1, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('1431-CYWMH', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('6723-CEGQI', 'Female', 0, 'No', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('9359-JANWS', 'Female', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('8562-GHPPI', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('1013-QCWAM', 'Female', 1, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('4043-MKDTV', 'Male', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('3211-ILJTT', 'Male', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('4208-UFFGW', 'Male', 1, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('1810-BOHSY', 'Male', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('1047-NNCBF', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('5945-AZYHT', 'Male', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('2659-VXMWZ', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('5564-NEMQO', 'Female', 1, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('4301-VVZKA', 'Male', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('9220-ZNKJI', 'Female', 1, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('4431-EDMIQ', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('8100-HZZLJ', 'Female', 0, 'No', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('4351-QLCSU', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('4815-GBTCD', 'Female', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('5135-GRQJV', 'Male', 1, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('8133-ANHHJ', 'Female', 1, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('3927-NLNRY', 'Male', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('4611-ANLQC', 'Female', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('1265-XTECC', 'Female', 1, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('3259-KNMRR', 'Male', 1, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('5445-UTODQ', 'Female', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('6569-KTMDU', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('2969-WGHQO', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('2560-WBWXF', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('6849-OYAMU', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('3420-YJLQT', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('0266-CLZKZ', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('5196-WPYOW', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('9609-BENEA', 'Male', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('6465-GSRCL', 'Female', 0, 'No', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('7321-PKUYW', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('7622-FWGEW', 'Male', 1, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('5133-VRSAB', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('4883-KCPZJ', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('5003-XZWWO', 'Male', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('8741-LQOBK', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('6408-OTUBZ', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('0430-IHCDJ', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('7011-CVEUC', 'Male', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('5871-DGTXZ', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('1907-YLNYW', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('9575-IWCAZ', 'Male', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('2637-FKFSY', 'Female', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('1357-MVDOZ', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('1379-FRVEB', 'Male', 0, 'No', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('0634-SZPQA', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('9214-EKVXR', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('6967-PEJLL', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('5457-COLHT', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('8766-PAFNE', 'Male', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('5590-ZSKRV', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('6505-OZNPG', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('5641-DMBFJ', 'Female', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('9831-BPFRI', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('2322-VCZHZ', 'Male', 1, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('1764-VUUMT', 'Male', 0, 'No', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('6418-HNFED', 'Male', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('6437-UKHMV', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('1272-ILHFG', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('1591-NFNLQ', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('7234-KMNRQ', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('1310-QRITU', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('8178-EYZUO', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('1400-MMYXY', 'Male', 1, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('9953-ZMKSM', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('1527-SXDPN', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('1703-MGIAB', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('7156-MXBJE', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('8232-UTFOZ', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('3486-HOOGQ', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('7356-AYNJP', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('6685-XSHHU', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('5590-YRFJT', 'Female', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('6265-SXWBU', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('6891-JPYFF', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('6656-JWRQX', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('7743-EXURX', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('6127-IYJOZ', 'Male', 1, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('2576-HXMPA', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('8022-BECSI', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('0786-VSSUD', 'Male', 1, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('9924-JPRMC', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('9314-QDMDW', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('5339-PXDVH', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('2017-CCBLH', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('5020-ZSTTY', 'Female', 1, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('5930-GBIWP', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('6961-VCPMC', 'Male', 1, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('0254-WWRKD', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('5248-KWLAR', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('1302-UHBDD', 'Male', 1, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('9158-VCTQB', 'Female', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('7273-TEFQD', 'Male', 1, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('6537-OTKMY', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('6298-QDFNH', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('8854-CCVSQ', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('9734-YWGEX', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('9040-KZVWO', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('0308-GIQJT', 'Male', 1, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('0307-BCOPK', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('3219-JQRSL', 'Female', 1, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('1839-UMACK', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('5014-WUQMG', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('0420-TXVSG', 'Male', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('6633-MPWBS', 'Male', 0, 'No', 'No')

INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('4013-GUXND', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('2361-FJWNO', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('5404-GGUKR', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('9065-ZCPQX', 'Male', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('5597-GLBUC', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('8819-ZBYNA', 'Female', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('1131-ALZWV', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('0013-EXCHZ', 'Female', 1, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('0962-CQPWQ', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('7030-FZTFM', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('3923-CSIHK', 'Female', 1, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('9800-OUIGR', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('6080-TCMYC', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('0635-WKOLD', 'Male', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('5696-CEIQJ', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('4840-ORQXB', 'Female', 1, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('3774-VBNXY', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('8875-AKBYH', 'Male', 1, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('7375-WMVMT', 'Male', 1, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('1163-ONYEY', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('1814-WFGVS', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('1337-BOZWO', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('9470-YFUYI', 'Male', 1, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('6374-AFWOX', 'Male', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('3190-ITQXP', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('6195-MELTI', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('2200-DSAAL', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('7537-RBWEA', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('1087-GRUYI', 'Male', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('9029-FEGVJ', 'Female', 1, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('9588-OZDMQ', 'Female', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('9272-LSVYH', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('3910-MRQOY', 'Female', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('4616-ULAOA', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('5628-FCGYG', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('1945-XISKS', 'Female', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('4123-FCVCB', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('6402-ZFPPI', 'Female', 1, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('1200-TUZHR', 'Female', 1, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('7617-EYGLW', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('4293-ETKAP', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('7580-UGXNC', 'Female', 1, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('7599-NTMDP', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('0362-ZBZWJ', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('7190-XHTWJ', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('3950-VPYJB', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('8512-WIWYV', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('8782-LKFPK', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('1251-KRREG', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('4361-BKAXE', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('4373-MAVJG', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('5018-GWURO', 'Female', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('8972-HJWNV', 'Female', 1, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('7706-DZNKK', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('5039-LZRQT', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('5360-LJCNJ', 'Female', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('9092-GDZKO', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('0959-WHOKV', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('5312-TSZVC', 'Female', 0, 'No', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('1063-DHQJF', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('5934-TSSAU', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('8496-EJAUI', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('5135-RDDQL', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('2256-YLYLP', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('0318-QUUOB', 'Male', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('5087-SUURX', 'Female', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('0114-IGABW', 'Female', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('5003-OKNNK', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('5647-URDKA', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('9961-JBNMK', 'Male', 1, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('3462-BJQQA', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('9309-BZGNT', 'Male', 1, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('1209-VFFOC', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('7814-LEEVE', 'Female', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('4636-TVXVG', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('4000-VGMQP', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('2952-QAYZF', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('5567-WSELE', 'Male', 1, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('9659-QEQSY', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('5624-BQSSA', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('7020-OZKXZ', 'Female', 1, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('0599-XNYDO', 'Female', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('6987-XQSJT', 'Female', 1, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('5495-GPSRW', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('6583-SZVGP', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('8904-OPDCK', 'Male', 1, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('0248-IPDFW', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('1478-VPOAD', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('7601-WFVZV', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('8859-YSTWS', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('1622-HSHSF', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('9938-ZREHM', 'Female', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('9441-QHEVC', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('8874-EJNSR', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('3446-QDSZF', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('8277-RVRSV', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('6082-GLJIX', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('0742-MOABM', 'Male', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('6922-NCEDI', 'Male', 0, 'No', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('3884-HCSWG', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('6893-ODYYE', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('0794-YVSGE', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('9494-MRNYX', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('7267-FRMJW', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('1987-AUELQ', 'Female', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('6286-ZHAOK', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('7508-MYBOG', 'Male', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('6388-TABGU', 'Male', 0, 'No', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('0420-BWTPW', 'Male', 0, 'No', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('8058-DMYRU', 'Male', 1, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('5734-EJKXG', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('4111-BNXIF', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('8050-DVOJX', 'Male', 1, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('7975-JMZNT', 'Male', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('3384-CTMSF', 'Male', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('2782-JEEBU', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('5649-RXQTV', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('4824-GUCBY', 'Female', 1, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('6394-HHHZM', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('9405-GPBBG', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('3896-RCYYE', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('8774-GSBUN', 'Male', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('5338-YHWYT', 'Male', 0, 'No', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('4750-UKWJK', 'Female', 1, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('1866-RZZQS', 'Male', 1, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('2360-RDGRO', 'Male', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('3079-BCHLN', 'Male', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('3943-KDREE', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('2691-NZETQ', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('5394-MEITZ', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('4826-XTSOH', 'Male', 1, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('3249-VHRIP', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('2079-FBMZK', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('9770-KXGQU', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('3522-CDKHF', 'Female', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('8199-ZLLSA', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('7083-YNSKY', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('5533-RJFTJ', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('6214-EDAKZ', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('8984-EYLLL', 'Male', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('3744-ZRRDZ', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('2454-RPBRZ', 'Female', 1, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('4760-THGOT', 'Female', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('7073-QETQY', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('5980-NOPLP', 'Female', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('4933-IKULF', 'Female', 1, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('4749-VFKVB', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('8276-MQBYC', 'Male', 1, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('4083-EUGRJ', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('9518-RWHZL', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('9552-TGUZV', 'Male', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('8647-SDTWQ', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('4560-WQAQW', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('4942-VZZOM', 'Male', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('9629-NHXFW', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('2226-ICFDO', 'Female', 0, 'Yes', 'Yes')

INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('5233-AOZUF', 'Female', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('4236-XPXAV', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('6198-RTPMF', 'Female', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('3580-GICBM', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('2311-QYMUQ', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('8902-ZEOVF', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('9592-ERDKV', 'Male', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('6464-KEXXH', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('5256-SKJGO', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('5249-QYHEX', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('1784-BXEFA', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('1262-OPMFY', 'Female', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('9972-VAFJJ', 'Female', 1, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('8620-RJPZN', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('9522-ZSINC', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('2188-SXWVT', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('3486-KHMLI', 'Male', 0, 'No', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('3115-CZMZD', 'Male', 0, 'No', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('7175-NTIXE', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('2920-RNCEZ', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('2516-VQRRV', 'Female', 1, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('2888-ADFAO', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('2190-PHBHR', 'Female', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('1254-IZEYF', 'Female', 1, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('2520-SGTTA', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('9646-NMHXE', 'Male', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('8749-TZYEC', 'Male', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('9708-KFDBY', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('0778-NELLA', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('8676-OOQEJ', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('1580-BMCMR', 'Male', 1, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('7730-IUTDZ', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('2351-BKRZW', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('3255-GRXMG', 'Male', 0, 'No', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('0420-HLGXF', 'Female', 1, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('3292-PBZEJ', 'Male', 1, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('7854-FOKSF', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('4806-HIPDW', 'Female', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('7233-IOQNP', 'Female', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('8332-OSJDW', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('2252-NKNSI', 'Male', 0, 'No', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('8200-LGKSR', 'Male', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('6308-CQRBU', 'Female', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('0730-KOAVE', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('1897-RCFUM', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('0807-ZABDG', 'Female', 0, 'No', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('8909-BOLNL', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('4322-RCYMT', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('5465-BUBFA', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('6979-ZNSFF', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('0626-QXNGV', 'Female', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('1184-PJVDB', 'Male', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('3863-IUBJR', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('0536-ACXIP', 'Female', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('4248-QPAVC', 'Female', 1, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('1032-MAELW', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('6771-XWBDM', 'Female', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('9710-ZUSHQ', 'Female', 1, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('6876-ADESB', 'Male', 0, 'No', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('6777-TGHTM', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('3229-USWAR', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('8624-GIOUT', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('6695-AMZUF', 'Female', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('2451-YMUXS', 'Male', 1, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('6407-GSJNL', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('2988-PLAHS', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('5032-MIYKT', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('1088-AUUZZ', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('1583-IHQZE', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('7587-AOVVU', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('1448-CYWKC', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('5850-BDWCY', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('7503-EPSZW', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('4828-FAZPK', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('3410-MHHUM', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('6648-INWPS', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('1328-EUZHC', 'Female', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('2122-SZZZD', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('1028-FFNJK', 'Male', 1, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('4747-LCAQL', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('3677-TNKIO', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('2235-ZGKPT', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('0815-MFZGM', 'Female', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('5774-XZTQC', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('2916-BQZLN', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('0999-QXNSA', 'Male', 1, 'No', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('7919-ZODZZ', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('8903-WMRNW', 'Female', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('2027-FECZV', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('1218-VKFPE', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('6979-TNDEU', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('4182-BGSIQ', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('0531-ZZJWQ', 'Male', 1, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('9110-HSGTV', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('4616-EWBNJ', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('7740-KKCXF', 'Male', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('2400-XIWIO', 'Female', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('9378-FXTIZ', 'Female', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('3716-UVSPD', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('6261-LHRTG', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('7845-URHJN', 'Female', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('6838-HVLXG', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('5956-VKDTT', 'Female', 1, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('6522-OIQSX', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('1751-NCDLI', 'Male', 1, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('4829-AUOAX', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('7426-RHZGU', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('7409-JURKQ', 'Female', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('8807-ARQET', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('3097-FQTVJ', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('8756-RDDLT', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('9560-BBZXK', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('4381-MHQDC', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('5295-PCJOO', 'Male', 0, 'No', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('6013-BHCAW', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('3672-YITQD', 'Male', 1, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('9753-OYLBX', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('1965-AKTSX', 'Female', 1, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('9101-BWFSS', 'Female', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('9445-ZUEQE', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('1682-VCOIO', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('8676-TRMJS', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('4480-MBMLB', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('8155-IBNHG', 'Female', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('7207-RMRDB', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('3606-SBKRY', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('6741-QRLUP', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('2969-VAPYH', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('8361-LBRDI', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('0207-MDKNV', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('1384-RCUXW', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('2082-CEFLT', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('6854-EXGSF', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('9237-HQITU', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('5117-ZSMHQ', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('5619-XZZKR', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('3889-VWBID', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('6728-CZFEI', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('5639-NTUPK', 'Male', 0, 'No', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('1552-TKMXS', 'Female', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('2480-SQIOB', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('0237-YFUTL', 'Female', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('9842-EFSYY', 'Female', 0, 'No', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('7501-VTYLJ', 'Female', 0, 'No', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('0386-CWRGM', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('3685-YLCMQ', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('2233-TXSIU', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('7977-HXJKU', 'Male', 0, 'No', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('7851-WZEKY', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('2378-YIZKA', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('6030-REHUX', 'Female', 1, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('2129-ALKBS', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('2926-JEJJC', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('9821-POOTN', 'Male', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('7905-TVXTA', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('3190-FZATL', 'Male', 0, 'No', 'Yes')

INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('7272-QDCKA', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('4138-NAXED', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('1453-RZFON', 'Female', 0, 'No', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('8792-AOROI', 'Female', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('5056-FIMPT', 'Female', 0, 'No', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('5572-ZDXHY', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('7010-ZMVBF', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('7994-XIRTR', 'Male', 1, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('5228-EXCET', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('1170-SASML', 'Female', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('8165-CBKXO', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('9451-WLYRI', 'Female', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('9039-ZVJDC', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('5148-HKFIR', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('9318-NKNFC', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('7931-PXHFC', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('6131-JLWZM', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('7529-ZDFXI', 'Male', 1, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('7167-PCEYD', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('4680-KUTAJ', 'Female', 1, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('1629-DQQVB', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('7964-VEXDG', 'Male', 0, 'No', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('6615-ZGEDR', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('4458-KVRBJ', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('9600-NAXZN', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('7492-TAFJD', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('3050-RLLXC', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('0550-DCXLH', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('5156-UMKOW', 'Female', 0, 'No', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('4526-RMTLL', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('9985-MWVIX', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('5882-CMAZQ', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('4830-FAXFM', 'Male', 0, 'No', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('4472-LVYGI', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('3173-WSSUE', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('7511-YMXVQ', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('9747-DDZOS', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('3896-ZVNET', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('6837-BJYDQ', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('9801-GDWGV', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('7710-JSYOA', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('5478-JJVZK', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('9828-QHFBK', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('4079-ULGFR', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('5804-JMYIO', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('2085-JVGAD', 'Male', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('5377-NDTOU', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('7016-NVRIC', 'Male', 1, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('1642-HMARX', 'Female', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('5811-IWXYM', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('0411-EZJZE', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('6772-KSATR', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('8207-DMRVL', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('3223-WZWJM', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('6357-JJPQT', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('2792-VPPET', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('6168-YBYNP', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('8059-UDZFY', 'Female', 1, 'No', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('0869-PAPRP', 'Female', 1, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('1482-OXZSY', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('5175-WLYXL', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('9489-JMTTN', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('9027-YFHQJ', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('4827-LTQRJ', 'Female', 1, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('3363-DTIVD', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('3199-XGZCY', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('4298-OYIFC', 'Male', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('6994-FGRHH', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('2404-JIBFC', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('1015-OWJKI', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('7233-DRTRF', 'Male', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('4860-YZGZM', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('4854-CIDCF', 'Female', 1, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('9507-HSMMZ', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('5115-GZDEL', 'Male', 0, 'No', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('5539-HIVAK', 'Female', 1, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('3982-DQLUS', 'Male', 1, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('4957-SREEC', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('2338-BQEZT', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('7695-PKLCZ', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('4475-NVTLU', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('8778-LMWTJ', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('9298-WGMRW', 'Female', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('9974-JFBHQ', 'Male', 0, 'No', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('7101-HRBLJ', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('9978-HYCIN', 'Male', 1, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('4745-LSPLO', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('1038-RQOST', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('3144-AUDBS', 'Female', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('1371-OJCEK', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('8566-YPRGL', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('7860-UXCRM', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('7993-PYKOF', 'Male', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('6616-AALSR', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('4955-VCWBI', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('9555-SAHUZ', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('1612-EOHDH', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('1755-RMCXH', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('2959-MJHIC', 'Male', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('0136-IFMYD', 'Male', 1, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('9398-MMQTO', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('8707-HOEDG', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('2391-SOORI', 'Male', 0, 'No', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('7047-FWEYA', 'Female', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('7615-ESMYF', 'Female', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('9565-FLVCG', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('0480-BIXDE', 'Female', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('8992-OBVDG', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('6339-RZCBJ', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('1792-UXAFY', 'Female', 1, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('6139-ZZRBQ', 'Male', 1, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('9644-KVCNC', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('1492-KGETH', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('3347-YJZZE', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('6260-ONULR', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('5093-FEGLU', 'Female', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('6892-BOGQE', 'Female', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('4878-BUNFV', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('6120-RJKLU', 'Female', 1, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('0019-GFNTW', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('0201-OAMXR', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('2208-NKVVH', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('6345-ULYRW', 'Male', 1, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('2212-LYASK', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('7774-OJSXI', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('5063-IUOKK', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('9172-JITSM', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('9764-REAFF', 'Female', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('5364-XYIRR', 'Male', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('7503-ZGUZJ', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('6394-MFYNG', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('6439-PKTRR', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('3243-ZHOHY', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('4199-QHJNM', 'Male', 1, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('7622-NXQZR', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('8404-GFGCZ', 'Male', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('3976-HXHCE', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('7089-XXAYG', 'Male', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('5327-CNLUQ', 'Male', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('8107-RZLNV', 'Male', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('1143-NMNQJ', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('0880-FVFWF', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('9500-WBGRP', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('3030-YZADT', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('2402-TAIRZ', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('9060-HJJRW', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('0394-YONDK', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('2832-KJCRD', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('0376-YMCJC', 'Male', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('1269-FOYWN', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('3717-FDJFU', 'Male', 0, 'No', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('1060-ENTOF', 'Female', 1, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('1293-BSEUN', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('9979-RGMZT', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('6950-TWMYB', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('0440-MOGPM', 'Female', 0, 'No', 'No')

INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('8652-YHIYU', 'Female', 0, 'No', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('6386-SZZKH', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('9076-AXYIK', 'Male', 1, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('3278-FSIXX', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('6408-WHTEF', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('6032-IGALN', 'Female', 0, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('0684-AOSIH', 'Male', 0, 'Yes', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('5982-PSMKW', 'Female', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('8044-BGWPI', 'Male', 0, 'Yes', 'Yes')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('7450-NWRTR', 'Male', 1, 'No', 'No')
INSERT INTO customer ( customerID, gender, SeniorCitizen, Partner, Dependents ) VALUES  ('4795-UXVCJ', 'Male', 0, 'No', 'No')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('7242-QZLXF', 1, 'No', 'No phone service', 'DSL', 'No', 'No', 'No', 'No', 'No', 'No', 'Month-to-month', 'Yes', 'Electronic check', 25.3, '25.3')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('8325-QRPZR', 7, 'Yes', 'No', 'Fiber optic', 'No', 'No', 'Yes', 'No', 'No', 'No', 'Month-to-month', 'Yes', 'Electronic check', 75.15, '525')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('7874-ECPQJ', 4, 'Yes', 'No', 'No', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'Month-to-month', 'Yes', 'Bank transfer (automatic)', 20.05, '85.5')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('2476-YGEFM', 29, 'Yes', 'Yes', 'Fiber optic', 'No', 'No', 'No', 'No', 'No', 'No', 'Month-to-month', 'Yes', 'Credit card (automatic)', 76.0, '2215.25')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('2276-YDAVZ', 3, 'Yes', 'Yes', 'Fiber optic', 'No', 'No', 'No', 'No', 'No', 'No', 'Month-to-month', 'Yes', 'Credit card (automatic)', 75.1, '270.7')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('0661-XEYAN', 1, 'No', 'No phone service', 'DSL', 'No', 'No', 'No', 'No', 'No', 'No', 'Month-to-month', 'Yes', 'Mailed check', 25.8, '25.8')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('1397-XKKWR', 7, 'No', 'No phone service', 'DSL', 'Yes', 'No', 'Yes', 'No', 'No', 'No', 'One year', 'No', 'Mailed check', 35.3, '264.8')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('9249-FXSCK', 52, 'Yes', 'Yes', 'Fiber optic', 'Yes', 'Yes', 'No', 'Yes', 'Yes', 'Yes', 'One year', 'Yes', 'Credit card (automatic)', 111.25, '5916.45')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('4718-WXBGI', 72, 'Yes', 'Yes', 'DSL', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Two year', 'Yes', 'Credit card (automatic)', 91.95, '6614.9')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('0486-HECZI', 55, 'Yes', 'Yes', 'Fiber optic', 'Yes', 'Yes', 'No', 'No', 'Yes', 'No', 'Month-to-month', 'Yes', 'Electronic check', 96.75, '5238.9')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('7291-CDTMJ', 1, 'Yes', 'No', 'No', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'Month-to-month', 'Yes', 'Bank transfer (automatic)', 19.65, '19.65')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('7196-LIWRH', 6, 'Yes', 'No', 'No', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'Two year', 'No', 'Mailed check', 19.55, '124.45')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('0625-AFOHS', 29, 'Yes', 'No', 'No', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'Two year', 'No', 'Mailed check', 20.2, '558.8')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('5656-MJEFC', 42, 'No', 'No phone service', 'DSL', 'Yes', 'No', 'Yes', 'Yes', 'Yes', 'No', 'Two year', 'No', 'Credit card (automatic)', 48.15, '2032.3')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('5640-CAXOA', 30, 'No', 'No phone service', 'DSL', 'No', 'No', 'No', 'Yes', 'No', 'Yes', 'One year', 'Yes', 'Credit card (automatic)', 40.35, '1187.05')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('3946-MHCZW', 1, 'Yes', 'No', 'DSL', 'No', 'No', 'Yes', 'No', 'No', 'No', 'Month-to-month', 'No', 'Mailed check', 50.9, '50.9')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('8374-UULRV', 72, 'Yes', 'Yes', 'DSL', 'Yes', 'Yes', 'No', 'Yes', 'Yes', 'Yes', 'Two year', 'No', 'Credit card (automatic)', 86.05, '6309.65')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('2108-YKQTY', 4, 'Yes', 'No', 'DSL', 'No', 'Yes', 'No', 'No', 'No', 'No', 'Month-to-month', 'No', 'Credit card (automatic)', 50.7, '151.3')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('2862-PFNIK', 1, 'No', 'No phone service', 'DSL', 'No', 'No', 'No', 'No', 'No', 'No', 'Month-to-month', 'Yes', 'Electronic check', 24.7, '24.7')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('2856-HYAPG', 1, 'Yes', 'No', 'Fiber optic', 'No', 'No', 'No', 'No', 'No', 'No', 'Month-to-month', 'No', 'Electronic check', 68.65, '68.65')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('3707-GNWHM', 1, 'Yes', 'Yes', 'Fiber optic', 'No', 'No', 'No', 'No', 'No', 'No', 'Month-to-month', 'Yes', 'Mailed check', 74.25, '74.25')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('2363-BJLSL', 62, 'Yes', 'No', 'DSL', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Month-to-month', 'Yes', 'Bank transfer (automatic)', 80.4, '4981.15')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('3663-MITLP', 15, 'Yes', 'No', 'Fiber optic', 'No', 'Yes', 'Yes', 'No', 'Yes', 'Yes', 'Month-to-month', 'Yes', 'Electronic check', 101.25, '1457.25')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('3373-YZZYM', 1, 'Yes', 'No', 'No', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'Month-to-month', 'No', 'Mailed check', 19.2, '19.2')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('5848-FHRFC', 68, 'Yes', 'No', 'No', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'Two year', 'No', 'Bank transfer (automatic)', 20.05, '1386.9')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('0840-DFEZH', 7, 'Yes', 'Yes', 'Fiber optic', 'No', 'No', 'No', 'No', 'No', 'No', 'Month-to-month', 'Yes', 'Electronic check', 75.35, '564.65')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('5879-HMFFH', 72, 'Yes', 'Yes', 'DSL', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Two year', 'No', 'Bank transfer (automatic)', 88.05, '6520.8')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('4723-BEGSG', 72, 'Yes', 'Yes', 'DSL', 'Yes', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'Two year', 'No', 'Credit card (automatic)', 86.65, '6094.25')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('3976-BWUCK', 30, 'Yes', 'Yes', 'Fiber optic', 'No', 'Yes', 'No', 'Yes', 'Yes', 'No', 'Month-to-month', 'Yes', 'Credit card (automatic)', 94.1, '2804.45')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('7120-RFMVS', 1, 'Yes', 'Yes', 'Fiber optic', 'No', 'No', 'No', 'No', 'Yes', 'No', 'Month-to-month', 'No', 'Electronic check', 84.5, '84.5')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('8292-FRFZQ', 39, 'No', 'No phone service', 'DSL', 'Yes', 'Yes', 'No', 'Yes', 'No', 'No', 'One year', 'No', 'Bank transfer (automatic)', 41.15, '1700.9')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('9480-BQJEI', 62, 'Yes', 'Yes', 'Fiber optic', 'Yes', 'Yes', 'No', 'No', 'No', 'Yes', 'One year', 'Yes', 'Bank transfer (automatic)', 92.3, '5731.45')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('4350-ZTLPI', 53, 'Yes', 'Yes', 'Fiber optic', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'One year', 'Yes', 'Bank transfer (automatic)', 108.95, '5718.2')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('3763-GCZHZ', 66, 'Yes', 'Yes', 'Fiber optic', 'No', 'Yes', 'No', 'Yes', 'Yes', 'Yes', 'One year', 'Yes', 'Electronic check', 104.05, '6890')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('1658-XUHBX', 59, 'Yes', 'Yes', 'Fiber optic', 'No', 'No', 'Yes', 'No', 'No', 'Yes', 'Month-to-month', 'Yes', 'Credit card (automatic)', 88.75, '5348.65')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('2507-QZPQS', 15, 'Yes', 'Yes', 'Fiber optic', 'No', 'Yes', 'No', 'Yes', 'No', 'Yes', 'Month-to-month', 'No', 'Electronic check', 95.7, '1451.1')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('0564-JJHGS', 9, 'Yes', 'Yes', 'Fiber optic', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'Month-to-month', 'Yes', 'Electronic check', 95.5, '829.1')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('9750-BOOHV', 32, 'No', 'No phone service', 'DSL', 'Yes', 'No', 'No', 'No', 'No', 'No', 'One year', 'No', 'Mailed check', 30.15, '927.65')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('8773-HHUOZ', 17, 'Yes', 'No', 'DSL', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'Month-to-month', 'Yes', 'Mailed check', 64.7, '1093.1')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('1335-MXCSE', 55, 'Yes', 'No', 'DSL', 'No', 'No', 'Yes', 'Yes', 'No', 'No', 'Two year', 'Yes', 'Credit card (automatic)', 55.25, '3119.9')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('6029-CSMJE', 17, 'No', 'No phone service', 'DSL', 'No', 'No', 'No', 'No', 'No', 'No', 'Month-to-month', 'Yes', 'Mailed check', 25.65, '440.2')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('8707-RMEZH', 69, 'Yes', 'No', 'Fiber optic', 'Yes', 'Yes', 'No', 'No', 'No', 'Yes', 'One year', 'No', 'Credit card (automatic)', 87.3, '6055.55')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('0771-CHWSK', 66, 'Yes', 'Yes', 'DSL', 'Yes', 'Yes', 'Yes', 'No', 'No', 'Yes', 'Two year', 'Yes', 'Credit card (automatic)', 74.6, '4798.4')

INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('4774-HHGGS', 30, 'Yes', 'No', 'No', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'Two year', 'No', 'Mailed check', 19.05, '637.55')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('4501-VCPFK', 26, 'No', 'No phone service', 'DSL', 'No', 'No', 'Yes', 'Yes', 'No', 'No', 'Month-to-month', 'No', 'Electronic check', 35.75, '1022.5')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('5089-IFSDP', 58, 'Yes', 'Yes', 'Fiber optic', 'Yes', 'Yes', 'Yes', 'No', 'Yes', 'Yes', 'Two year', 'Yes', 'Bank transfer (automatic)', 109.45, '6144.55')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('9526-BIHHD', 1, 'No', 'No phone service', 'DSL', 'Yes', 'No', 'No', 'No', 'No', 'No', 'Month-to-month', 'No', 'Mailed check', 29.7, '29.7')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('5174-RNGBH', 9, 'Yes', 'No', 'DSL', 'No', 'Yes', 'No', 'Yes', 'Yes', 'No', 'Month-to-month', 'No', 'Mailed check', 66.25, '620.55')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('3696-XRIEN', 50, 'Yes', 'Yes', 'DSL', 'Yes', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'One year', 'Yes', 'Credit card (automatic)', 82.5, '4179.1')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('6174-NRBTZ', 46, 'No', 'No phone service', 'DSL', 'Yes', 'No', 'No', 'No', 'No', 'No', 'One year', 'Yes', 'Bank transfer (automatic)', 30.75, '1489.3')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('8660-BUETV', 3, 'Yes', 'No', 'DSL', 'No', 'No', 'No', 'No', 'No', 'No', 'Month-to-month', 'No', 'Mailed check', 44.75, '148.05')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('1596-OQSPS', 11, 'Yes', 'No', 'DSL', 'No', 'Yes', 'No', 'No', 'No', 'No', 'Month-to-month', 'No', 'Electronic check', 51.1, '531.15')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('7147-AYBAA', 37, 'Yes', 'No', 'Fiber optic', 'No', 'No', 'No', 'No', 'No', 'No', 'Month-to-month', 'Yes', 'Mailed check', 70.35, '2552.9')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('0156-FVPTA', 22, 'Yes', 'No', 'DSL', 'Yes', 'No', 'No', 'Yes', 'No', 'No', 'Month-to-month', 'Yes', 'Electronic check', 54.2, '1152.7')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('3873-WOSBC', 67, 'Yes', 'Yes', 'No', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'Two year', 'No', 'Credit card (automatic)', 25.6, '1784.9')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('8048-DSDFQ', 1, 'Yes', 'No', 'No', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'Month-to-month', 'No', 'Mailed check', 20.2, '20.2')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('5939-XAIXZ', 19, 'Yes', 'Yes', 'DSL', 'No', 'No', 'Yes', 'No', 'No', 'No', 'Month-to-month', 'Yes', 'Mailed check', 56.1, '1033.9')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('0709-TVGUR', 9, 'Yes', 'Yes', 'Fiber optic', 'No', 'No', 'No', 'No', 'No', 'No', 'Month-to-month', 'Yes', 'Electronic check', 74.55, '622.9')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('4686-GEFRM', 70, 'Yes', 'Yes', 'Fiber optic', 'No', 'Yes', 'Yes', 'Yes', 'No', 'Yes', 'Two year', 'Yes', 'Bank transfer (automatic)', 98.7, '6858.9')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('1845-ZLLIG', 1, 'Yes', 'No', 'DSL', 'No', 'Yes', 'No', 'No', 'No', 'No', 'Month-to-month', 'Yes', 'Mailed check', 50.15, '50.15')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('8350-NYMVI', 39, 'No', 'No phone service', 'DSL', 'No', 'Yes', 'Yes', 'Yes', 'No', 'No', 'Month-to-month', 'No', 'Bank transfer (automatic)', 41.1, '1597.05')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('5028-GZLDO', 2, 'Yes', 'No', 'Fiber optic', 'No', 'No', 'No', 'No', 'No', 'No', 'Month-to-month', 'No', 'Credit card (automatic)', 70.7, '140.7')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('1125-SNVCK', 49, 'Yes', 'No', 'DSL', 'No', 'No', 'No', 'No', 'No', 'No', 'Month-to-month', 'No', 'Mailed check', 43.8, '2106.05')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('7319-VENRZ', 7, 'Yes', 'No', 'DSL', 'No', 'No', 'Yes', 'Yes', 'Yes', 'No', 'Month-to-month', 'No', 'Bank transfer (automatic)', 64.3, '445.95')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('3165-HDOEW', 1, 'Yes', 'No', 'DSL', 'No', 'No', 'No', 'No', 'No', 'No', 'Month-to-month', 'Yes', 'Mailed check', 45.85, '45.85')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('1095-WGNGG', 61, 'Yes', 'Yes', 'Fiber optic', 'No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'Two year', 'Yes', 'Bank transfer (automatic)', 101.05, '5971.25')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('6959-UWKHF', 1, 'Yes', 'No', 'DSL', 'No', 'No', 'No', 'No', 'No', 'No', 'Month-to-month', 'Yes', 'Electronic check', 42.9, '42.9')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('0093-EXYQL', 40, 'Yes', 'No', 'Fiber optic', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'Month-to-month', 'Yes', 'Electronic check', 91.55, '3673.6')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('3612-YVGSJ', 71, 'Yes', 'Yes', 'No', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'Two year', 'Yes', 'Credit card (automatic)', 24.45, '1681.6')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('8565-CLBZW', 24, 'Yes', 'Yes', 'Fiber optic', 'No', 'No', 'Yes', 'No', 'Yes', 'No', 'Month-to-month', 'Yes', 'Mailed check', 89.85, '2165.05')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('8967-SZQAS', 14, 'Yes', 'No', 'DSL', 'No', 'Yes', 'No', 'No', 'No', 'No', 'Month-to-month', 'No', 'Electronic check', 50.45, '765.45')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('7789-CRUVC', 61, 'Yes', 'Yes', 'Fiber optic', 'Yes', 'Yes', 'Yes', 'Yes', 'No', 'No', 'Month-to-month', 'Yes', 'Credit card (automatic)', 94.2, '5895.45')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('0134-XWXCE', 44, 'Yes', 'No', 'DSL', 'No', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'One year', 'No', 'Bank transfer (automatic)', 74.85, '3268.05')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('0505-SPOOW', 70, 'Yes', 'No', 'No', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'Two year', 'No', 'Bank transfer (automatic)', 19.8, '1397.65')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('7801-KICAO', 18, 'Yes', 'Yes', 'Fiber optic', 'No', 'No', 'No', 'No', 'No', 'No', 'Month-to-month', 'Yes', 'Electronic check', 74.15, '1345.75')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('7603-USHJS', 12, 'Yes', 'Yes', 'Fiber optic', 'No', 'No', 'No', 'No', 'No', 'No', 'Month-to-month', 'Yes', 'Credit card (automatic)', 73.75, '871.4')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('9659-ZTWSM', 66, 'Yes', 'Yes', 'Fiber optic', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'One year', 'Yes', 'Bank transfer (automatic)', 107.35, '7051.95')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('8434-VGEQQ', 61, 'Yes', 'No', 'No', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'Two year', 'No', 'Credit card (automatic)', 20.55, '1305.95')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('7621-VPNET', 42, 'Yes', 'Yes', 'Fiber optic', 'No', 'No', 'Yes', 'Yes', 'No', 'No', 'Month-to-month', 'Yes', 'Credit card (automatic)', 85.9, '3729.75')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('1732-FEKLD', 54, 'Yes', 'Yes', 'Fiber optic', 'No', 'Yes', 'Yes', 'No', 'Yes', 'No', 'One year', 'Yes', 'Bank transfer (automatic)', 94.75, '5121.75')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('3195-TQDZX', 3, 'Yes', 'No', 'No', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'Month-to-month', 'Yes', 'Electronic check', 20.25, '61.45')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('1122-YJBCS', 69, 'Yes', 'No', 'DSL', 'Yes', 'Yes', 'No', 'No', 'No', 'No', 'One year', 'Yes', 'Credit card (automatic)', 53.65, '3804.4')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('6184-DYUOB', 3, 'Yes', 'No', 'No', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'Month-to-month', 'Yes', 'Mailed check', 19.6, '55.25')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('6711-FLDFB', 7, 'Yes', 'Yes', 'Fiber optic', 'No', 'No', 'No', 'No', 'No', 'No', 'Month-to-month', 'Yes', 'Electronic check', 74.9, '541.15')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('5821-MMEIL', 57, 'Yes', 'No', 'No', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'Two year', 'No', 'Bank transfer (automatic)', 19.9, '1115.6')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('9685-WKZGT', 14, 'Yes', 'Yes', 'Fiber optic', 'No', 'No', 'No', 'No', 'No', 'No', 'Month-to-month', 'Yes', 'Electronic check', 74.95, '1036.75')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('4905-JEFDW', 11, 'No', 'No phone service', 'DSL', 'No', 'No', 'Yes', 'No', 'Yes', 'No', 'One year', 'Yes', 'Electronic check', 41.6, '470.6')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('6260-XLACS', 4, 'Yes', 'No', 'No', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'One year', 'No', 'Mailed check', 19.7, '117.8')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('8597-CWYHH', 43, 'Yes', 'Yes', 'Fiber optic', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'One year', 'No', 'Mailed check', 94.35, '3921.3')

INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('8735-IJJEG', 14, 'Yes', 'No', 'DSL', 'No', 'No', 'Yes', 'No', 'No', 'No', 'Month-to-month', 'No', 'Credit card (automatic)', 50.2, '668.85')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('8050-XGRVL', 62, 'Yes', 'No', 'DSL', 'Yes', 'No', 'Yes', 'No', 'No', 'No', 'One year', 'No', 'Credit card (automatic)', 54.75, '3425.35')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('4846-WHAFZ', 37, 'Yes', 'Yes', 'Fiber optic', 'No', 'No', 'No', 'No', 'No', 'No', 'Month-to-month', 'Yes', 'Electronic check', 76.5, '2868.15')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('6907-CQGPN', 29, 'No', 'No phone service', 'DSL', 'No', 'Yes', 'No', 'Yes', 'No', 'No', 'Month-to-month', 'No', 'Electronic check', 34.3, '1004.75')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('3970-XGJDU', 62, 'Yes', 'No', 'No', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'Two year', 'Yes', 'Credit card (automatic)', 19.2, '1123.65')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('8631-WUXGY', 46, 'Yes', 'No', 'Fiber optic', 'No', 'Yes', 'Yes', 'No', 'Yes', 'Yes', 'Month-to-month', 'Yes', 'Electronic check', 99.8, '4391.25')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('7218-HKQFK', 2, 'Yes', 'No', 'Fiber optic', 'No', 'No', 'No', 'Yes', 'Yes', 'Yes', 'Month-to-month', 'Yes', 'Electronic check', 94.2, '167.5')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('6212-ATMLK', 50, 'Yes', 'Yes', 'Fiber optic', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'Month-to-month', 'Yes', 'Electronic check', 95.7, '4729.75')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('8625-AZYZY', 24, 'Yes', 'Yes', 'Fiber optic', 'No', 'Yes', 'Yes', 'No', 'Yes', 'Yes', 'Month-to-month', 'Yes', 'Electronic check', 104.65, '2542.45')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('7740-BTPUX', 55, 'Yes', 'Yes', 'Fiber optic', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Two year', 'Yes', 'Electronic check', 113.6, '6292.7')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('8869-LIHMK', 64, 'Yes', 'Yes', 'Fiber optic', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Two year', 'Yes', 'Bank transfer (automatic)', 115.1, '7334.05')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('4951-UKAAQ', 4, 'Yes', 'Yes', 'Fiber optic', 'No', 'Yes', 'No', 'No', 'No', 'Yes', 'Month-to-month', 'Yes', 'Electronic check', 88.95, '355.2')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('6624-JDRDS', 6, 'No', 'No phone service', 'DSL', 'Yes', 'No', 'No', 'No', 'No', 'No', 'Month-to-month', 'No', 'Bank transfer (automatic)', 29.45, '161.45')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('9248-OJYKK', 1, 'Yes', 'Yes', 'Fiber optic', 'No', 'No', 'No', 'No', 'No', 'No', 'Month-to-month', 'Yes', 'Electronic check', 76.45, '76.45')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('0513-RBGPE', 37, 'Yes', 'Yes', 'DSL', 'Yes', 'No', 'Yes', 'Yes', 'No', 'No', 'Two year', 'Yes', 'Credit card (automatic)', 62.8, '2278.75')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('3836-FZSDJ', 71, 'Yes', 'Yes', 'No', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'Two year', 'No', 'Bank transfer (automatic)', 24.85, '1901')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('1301-LOPVR', 29, 'No', 'No phone service', 'DSL', 'Yes', 'Yes', 'Yes', 'Yes', 'No', 'Yes', 'One year', 'Yes', 'Credit card (automatic)', 55.35, '1636.95')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('7479-NITWS', 7, 'Yes', 'Yes', 'Fiber optic', 'No', 'No', 'Yes', 'No', 'Yes', 'No', 'Month-to-month', 'Yes', 'Credit card (automatic)', 89.35, '631.85')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('3312-UUMZW', 32, 'Yes', 'Yes', 'Fiber optic', 'No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'Month-to-month', 'Yes', 'Credit card (automatic)', 98.85, '3145.9')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('0060-FUALY', 59, 'Yes', 'Yes', 'Fiber optic', 'Yes', 'Yes', 'No', 'No', 'Yes', 'No', 'Month-to-month', 'Yes', 'Electronic check', 94.75, '5597.65')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('2985-JUUBZ', 40, 'Yes', 'Yes', 'DSL', 'No', 'No', 'Yes', 'No', 'Yes', 'Yes', 'Month-to-month', 'Yes', 'Electronic check', 74.55, '3015.75')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('5016-ETTFF', 10, 'No', 'No phone service', 'DSL', 'No', 'No', 'Yes', 'No', 'No', 'No', 'Month-to-month', 'No', 'Mailed check', 29.5, '255.25')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('1998-VHJHK', 27, 'Yes', 'No', 'No', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'One year', 'No', 'Mailed check', 19.15, '501.35')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('1925-TIBLE', 7, 'Yes', 'Yes', 'Fiber optic', 'No', 'No', 'No', 'No', 'Yes', 'No', 'Month-to-month', 'Yes', 'Electronic check', 86.5, '582.5')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('0485-ZBSLN', 65, 'Yes', 'Yes', 'No', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'Two year', 'No', 'Credit card (automatic)', 24.75, '1715.1')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('4817-QRJSX', 10, 'Yes', 'Yes', 'Fiber optic', 'No', 'Yes', 'No', 'No', 'No', 'No', 'Month-to-month', 'Yes', 'Credit card (automatic)', 81.0, '818.05')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('7299-GNVPL', 23, 'Yes', 'No', 'Fiber optic', 'Yes', 'Yes', 'No', 'Yes', 'No', 'No', 'Month-to-month', 'No', 'Mailed check', 84.4, '1936.85')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('0945-TSONX', 47, 'Yes', 'Yes', 'DSL', 'Yes', 'Yes', 'No', 'Yes', 'Yes', 'Yes', 'Two year', 'Yes', 'Credit card (automatic)', 85.3, '4107.25')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('6859-RKMZJ', 11, 'Yes', 'No', 'DSL', 'No', 'No', 'No', 'No', 'Yes', 'No', 'Month-to-month', 'Yes', 'Bank transfer (automatic)', 55.05, '608.15')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('4177-JPDFU', 12, 'No', 'No phone service', 'DSL', 'No', 'Yes', 'No', 'Yes', 'No', 'No', 'Month-to-month', 'No', 'Mailed check', 34.0, '442.45')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('4459-BBGHE', 30, 'No', 'No phone service', 'DSL', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'Month-to-month', 'Yes', 'Electronic check', 44.5, '1307.8')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('5196-SGOAK', 1, 'Yes', 'No', 'Fiber optic', 'No', 'Yes', 'No', 'No', 'No', 'No', 'Month-to-month', 'Yes', 'Electronic check', 75.7, '75.7')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('0103-CSITQ', 57, 'Yes', 'Yes', 'Fiber optic', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'One year', 'Yes', 'Bank transfer (automatic)', 109.4, '6252.7')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('7206-PQBBZ', 11, 'Yes', 'No', 'Fiber optic', 'No', 'No', 'No', 'No', 'No', 'No', 'Month-to-month', 'Yes', 'Electronic check', 70.2, '834.7')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('7727-SHVZV', 9, 'Yes', 'No', 'No', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'Month-to-month', 'No', 'Bank transfer (automatic)', 19.5, '150.35')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('2608-BHKFN', 4, 'Yes', 'No', 'Fiber optic', 'No', 'No', 'No', 'No', 'No', 'No', 'Month-to-month', 'Yes', 'Credit card (automatic)', 70.05, '266.9')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('4860-IJUDE', 13, 'Yes', 'No', 'Fiber optic', 'Yes', 'No', 'No', 'No', 'No', 'No', 'Month-to-month', 'Yes', 'Credit card (automatic)', 73.75, '956.65')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('9509-MPYOD', 35, 'Yes', 'No', 'No', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'One year', 'No', 'Mailed check', 20.75, '700.45')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('3813-DHBBB', 67, 'No', 'No phone service', 'DSL', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes', 'Two year', 'Yes', 'Bank transfer (automatic)', 50.95, '3521.7')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('8672-OAUPW', 51, 'Yes', 'No', 'DSL', 'No', 'No', 'No', 'Yes', 'No', 'No', 'One year', 'No', 'Credit card (automatic)', 47.85, '2356.75')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('9564-KCLHR', 1, 'Yes', 'No', 'DSL', 'No', 'No', 'No', 'Yes', 'No', 'No', 'Month-to-month', 'No', 'Mailed check', 51.25, '51.25')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('8659-IOOPU', 71, 'Yes', 'Yes', 'Fiber optic', 'Yes', 'No', 'Yes', 'Yes', 'No', 'Yes', 'Two year', 'No', 'Electronic check', 100.45, '7159.7')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('3312-ZWLGF', 29, 'Yes', 'Yes', 'Fiber optic', 'No', 'No', 'No', 'Yes', 'No', 'No', 'Month-to-month', 'Yes', 'Electronic check', 79.3, '2414.55')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('8267-ZNYVZ', 33, 'Yes', 'No', 'Fiber optic', 'Yes', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'One year', 'Yes', 'Electronic check', 103.75, '3361.05')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('0305-SQECB', 11, 'No', 'No phone service', 'DSL', 'Yes', 'No', 'No', 'Yes', 'No', 'No', 'One year', 'Yes', 'Mailed check', 36.05, '402.6')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('7018-WBJNK', 13, 'Yes', 'No', 'Fiber optic', 'No', 'No', 'No', 'No', 'Yes', 'No', 'Month-to-month', 'Yes', 'Credit card (automatic)', 78.3, '1033.95')

INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('1091-SOZGA', 56, 'Yes', 'Yes', 'Fiber optic', 'No', 'No', 'Yes', 'No', 'Yes', 'Yes', 'One year', 'Yes', 'Credit card (automatic)', 99.8, '5515.45')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('2155-AMQRX', 28, 'Yes', 'Yes', 'DSL', 'No', 'No', 'No', 'Yes', 'No', 'No', 'Month-to-month', 'Yes', 'Credit card (automatic)', 54.9, '1505.15')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('3704-IEAXF', 72, 'No', 'No phone service', 'DSL', 'No', 'Yes', 'No', 'Yes', 'Yes', 'Yes', 'Two year', 'No', 'Credit card (automatic)', 53.65, '3784')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('7312-XSBAT', 1, 'Yes', 'No', 'DSL', 'Yes', 'No', 'No', 'No', 'No', 'No', 'Month-to-month', 'No', 'Electronic check', 49.75, '49.75')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('4010-YLMVT', 56, 'Yes', 'Yes', 'Fiber optic', 'Yes', 'Yes', 'No', 'No', 'Yes', 'Yes', 'Month-to-month', 'Yes', 'Credit card (automatic)', 106.6, '5893.95')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('5915-ANOEI', 70, 'Yes', 'Yes', 'DSL', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'No', 'Two year', 'No', 'Mailed check', 79.15, '5536.5')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('8679-LZBMD', 44, 'Yes', 'No', 'Fiber optic', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'One year', 'Yes', 'Bank transfer (automatic)', 90.65, '3974.15')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('2372-HWUHI', 2, 'Yes', 'No', 'DSL', 'No', 'No', 'No', 'No', 'No', 'No', 'Month-to-month', 'No', 'Electronic check', 44.35, '81.25')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('7162-WPHPM', 58, 'Yes', 'Yes', 'DSL', 'Yes', 'Yes', 'Yes', 'Yes', 'No', 'No', 'Two year', 'No', 'Credit card (automatic)', 71.6, '4230.25')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('8822-KNBHV', 48, 'Yes', 'Yes', 'DSL', 'Yes', 'Yes', 'Yes', 'No', 'Yes', 'Yes', 'One year', 'Yes', 'Credit card (automatic)', 83.45, '3887.85')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('0315-LVCRK', 11, 'Yes', 'No', 'Fiber optic', 'No', 'No', 'Yes', 'No', 'No', 'Yes', 'Month-to-month', 'No', 'Electronic check', 84.8, '888.75')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('8263-QMNTJ', 72, 'Yes', 'Yes', 'Fiber optic', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Two year', 'Yes', 'Electronic check', 115.55, '8425.3')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('0526-SXDJP', 72, 'No', 'No phone service', 'DSL', 'Yes', 'Yes', 'Yes', 'No', 'No', 'No', 'Two year', 'No', 'Bank transfer (automatic)', 42.1, '2962')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('5201-USSQZ', 26, 'Yes', 'No', 'Fiber optic', 'No', 'No', 'No', 'Yes', 'No', 'Yes', 'Month-to-month', 'No', 'Credit card (automatic)', 85.9, '2196.45')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('4132-POCZS', 52, 'No', 'No phone service', 'DSL', 'Yes', 'No', 'No', 'No', 'No', 'Yes', 'Month-to-month', 'Yes', 'Electronic check', 39.9, '2020.9')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('9257-AZMTZ', 52, 'Yes', 'No', 'No', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'Two year', 'No', 'Bank transfer (automatic)', 20.1, '1078.75')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('5447-VYTKW', 27, 'Yes', 'No', 'DSL', 'Yes', 'No', 'No', 'Yes', 'No', 'No', 'Month-to-month', 'No', 'Mailed check', 53.45, '1461.45')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('5960-WPXQM', 1, 'Yes', 'No', 'Fiber optic', 'No', 'No', 'No', 'No', 'Yes', 'No', 'Month-to-month', 'Yes', 'Electronic check', 79.05, '79.05')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('2826-UWHIS', 45, 'Yes', 'Yes', 'Fiber optic', 'No', 'Yes', 'No', 'No', 'No', 'No', 'Month-to-month', 'No', 'Bank transfer (automatic)', 81.4, '3775.85')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('7251-XFOIL', 61, 'Yes', 'Yes', 'Fiber optic', 'No', 'No', 'Yes', 'No', 'No', 'Yes', 'Month-to-month', 'No', 'Mailed check', 89.2, '5500.6')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('6923-JHPMP', 2, 'Yes', 'No', 'Fiber optic', 'Yes', 'No', 'Yes', 'No', 'No', 'No', 'Month-to-month', 'Yes', 'Electronic check', 80.45, '137.1')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('1373-ORVIZ', 11, 'Yes', 'Yes', 'DSL', 'No', 'No', 'No', 'Yes', 'No', 'Yes', 'Month-to-month', 'Yes', 'Electronic check', 66.35, '740.8')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('8220-OCUFY', 21, 'Yes', 'No', 'DSL', 'Yes', 'No', 'Yes', 'Yes', 'No', 'No', 'One year', 'Yes', 'Electronic check', 60.25, '1258.35')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('9488-HGMJH', 1, 'Yes', 'No', 'Fiber optic', 'No', 'No', 'No', 'No', 'No', 'No', 'Month-to-month', 'Yes', 'Electronic check', 71.15, '71.15')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('2446-BEGGB', 6, 'Yes', 'Yes', 'Fiber optic', 'No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'Month-to-month', 'Yes', 'Electronic check', 98.25, '560.6')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('5781-RFZRP', 71, 'Yes', 'Yes', 'DSL', 'Yes', 'Yes', 'No', 'Yes', 'Yes', 'No', 'Two year', 'No', 'Credit card (automatic)', 73.5, '5357.75')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('0973-KYVNF', 72, 'Yes', 'No', 'DSL', 'Yes', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Two year', 'Yes', 'Credit card (automatic)', 70.65, '5011.15')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('3740-RLMVT', 67, 'Yes', 'No', 'DSL', 'Yes', 'Yes', 'No', 'Yes', 'No', 'No', 'One year', 'Yes', 'Bank transfer (automatic)', 60.95, '4119.4')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('5837-LXSDN', 21, 'Yes', 'No', 'DSL', 'No', 'Yes', 'No', 'No', 'Yes', 'No', 'One year', 'Yes', 'Credit card (automatic)', 58.85, '1215.45')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('0404-AHASP', 72, 'Yes', 'No', 'No', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'Two year', 'No', 'Credit card (automatic)', 19.7, '1421.9')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('1934-MKPXS', 33, 'Yes', 'No', 'No', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'One year', 'No', 'Credit card (automatic)', 20.1, '620.55')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('3049-SOLAY', 3, 'Yes', 'Yes', 'Fiber optic', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'Month-to-month', 'Yes', 'Electronic check', 95.2, '292.85')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('8914-RBTSB', 31, 'Yes', 'Yes', 'Fiber optic', 'No', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Month-to-month', 'No', 'Electronic check', 93.8, '3019.5')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('1925-LFCZZ', 55, 'No', 'No phone service', 'DSL', 'No', 'No', 'Yes', 'No', 'Yes', 'Yes', 'One year', 'Yes', 'Bank transfer (automatic)', 50.05, '2743.45')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('8372-JUXUI', 1, 'Yes', 'Yes', 'Fiber optic', 'No', 'No', 'No', 'No', 'No', 'No', 'Month-to-month', 'Yes', 'Electronic check', 74.35, '74.35')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('5863-OOKCL', 10, 'Yes', 'No', 'No', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'Month-to-month', 'No', 'Mailed check', 18.85, '163.2')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('8262-COGGB', 1, 'Yes', 'No', 'No', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'Month-to-month', 'Yes', 'Mailed check', 20.45, '20.45')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('3320-VEOYC', 14, 'Yes', 'Yes', 'Fiber optic', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'Month-to-month', 'Yes', 'Electronic check', 95.6, '1273.3')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('1096-ADRUX', 66, 'Yes', 'Yes', 'Fiber optic', 'No', 'No', 'No', 'No', 'No', 'No', 'One year', 'Yes', 'Bank transfer (automatic)', 74.25, '4859.25')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('5668-MEISB', 72, 'Yes', 'Yes', 'Fiber optic', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'No', 'Two year', 'No', 'Credit card (automatic)', 106.1, '7657.4')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('4801-JZAZL', 11, 'No', 'No phone service', 'DSL', 'Yes', 'No', 'No', 'No', 'No', 'No', 'Month-to-month', 'Yes', 'Electronic check', 29.6, '346.45')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('6578-KRMAW', 32, 'Yes', 'No', 'Fiber optic', 'Yes', 'Yes', 'Yes', 'No', 'No', 'Yes', 'Month-to-month', 'Yes', 'Credit card (automatic)', 93.4, '2979.3')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('8884-ADFVN', 7, 'Yes', 'Yes', 'Fiber optic', 'No', 'No', 'Yes', 'No', 'Yes', 'Yes', 'Month-to-month', 'Yes', 'Electronic check', 101.95, '700.85')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('6933-VLYFX', 31, 'No', 'No phone service', 'DSL', 'Yes', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'One year', 'No', 'Electronic check', 59.95, '1848.8')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('4825-XJGDM', 61, 'No', 'No phone service', 'DSL', 'Yes', 'Yes', 'Yes', 'Yes', 'No', 'No', 'One year', 'No', 'Credit card (automatic)', 43.7, '2696.55')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('1846-XWOQN', 1, 'Yes', 'No', 'Fiber optic', 'No', 'No', 'No', 'No', 'No', 'No', 'Month-to-month', 'Yes', 'Electronic check', 70.15, '70.15')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('8089-UZWLX', 71, 'Yes', 'Yes', 'Fiber optic', 'No', 'No', 'Yes', 'No', 'Yes', 'Yes', 'Two year', 'No', 'Bank transfer (automatic)', 104.05, '7413.55')

INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('4636-QRJKY', 6, 'Yes', 'Yes', 'Fiber optic', 'No', 'No', 'No', 'Yes', 'No', 'No', 'Month-to-month', 'Yes', 'Electronic check', 80.5, '502.85')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('3376-BMGFE', 4, 'Yes', 'No', 'Fiber optic', 'No', 'No', 'No', 'No', 'No', 'No', 'Month-to-month', 'Yes', 'Bank transfer (automatic)', 70.9, '273')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('5445-PZWGX', 62, 'Yes', 'Yes', 'Fiber optic', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes', 'One year', 'No', 'Electronic check', 102.0, '6529.25')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('6857-TKDJV', 67, 'Yes', 'Yes', 'No', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'Two year', 'No', 'Bank transfer (automatic)', 24.65, '1620.45')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('1567-DSCIC', 8, 'Yes', 'Yes', 'Fiber optic', 'No', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Month-to-month', 'Yes', 'Electronic check', 94.0, '773.65')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('8544-JNBOX', 72, 'Yes', 'No', 'No', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'Two year', 'Yes', 'Mailed check', 20.8, '1521.2')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('5386-THSLQ', 66, 'No', 'No phone service', 'DSL', 'No', 'Yes', 'Yes', 'No', 'Yes', 'No', 'One year', 'No', 'Bank transfer (automatic)', 45.55, '3027.25')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('6331-LWDTQ', 10, 'Yes', 'Yes', 'DSL', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'Month-to-month', 'Yes', 'Credit card (automatic)', 72.15, '794.25')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('9360-AHGNL', 43, 'Yes', 'Yes', 'Fiber optic', 'Yes', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'One year', 'Yes', 'Mailed check', 109.55, '4830.25')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('2150-UWTFY', 22, 'Yes', 'No', 'DSL', 'Yes', 'Yes', 'Yes', 'No', 'No', 'No', 'Month-to-month', 'No', 'Mailed check', 61.15, '1422.05')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('1508-DFXCU', 12, 'Yes', 'No', 'Fiber optic', 'No', 'No', 'No', 'No', 'Yes', 'No', 'Month-to-month', 'Yes', 'Electronic check', 81.45, '912')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('6143-JQKEA', 10, 'Yes', 'No', 'DSL', 'No', 'No', 'No', 'No', 'No', 'No', 'Month-to-month', 'Yes', 'Credit card (automatic)', 45.8, '436.2')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('7801-CEDNV', 27, 'Yes', 'No', 'DSL', 'Yes', 'No', 'No', 'No', 'No', 'No', 'One year', 'No', 'Credit card (automatic)', 48.7, '1421.75')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('2717-HVIZY', 8, 'Yes', 'No', 'No', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'Month-to-month', 'No', 'Mailed check', 20.05, '163.6')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('0064-SUDOG', 12, 'Yes', 'No', 'No', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'Two year', 'No', 'Bank transfer (automatic)', 20.3, '224.5')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('6164-HAQTX', 71, 'No', 'No phone service', 'DSL', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'No', 'Two year', 'No', 'Bank transfer (automatic)', 53.95, '3888.65')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('1228-FZFRV', 50, 'Yes', 'Yes', 'Fiber optic', 'Yes', 'No', 'Yes', 'No', 'Yes', 'Yes', 'Month-to-month', 'No', 'Credit card (automatic)', 105.95, '5341.8')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('1679-JRFBR', 70, 'Yes', 'Yes', 'Fiber optic', 'Yes', 'Yes', 'Yes', 'No', 'Yes', 'Yes', 'One year', 'Yes', 'Credit card (automatic)', 108.15, '7930.55')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('1919-RTPQD', 7, 'Yes', 'No', 'DSL', 'No', 'No', 'No', 'No', 'No', 'No', 'Month-to-month', 'No', 'Electronic check', 44.75, '333.65')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('7641-EUYET', 46, 'Yes', 'Yes', 'Fiber optic', 'Yes', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Month-to-month', 'Yes', 'Electronic check', 100.7, '4541.2')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('2720-FVBQP', 6, 'Yes', 'Yes', 'DSL', 'No', 'No', 'No', 'No', 'No', 'No', 'Month-to-month', 'Yes', 'Credit card (automatic)', 48.95, '273.25')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('8035-PWSEV', 6, 'Yes', 'No', 'Fiber optic', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes', 'Month-to-month', 'Yes', 'Electronic check', 89.25, '487.05')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('3547-LQRIK', 47, 'Yes', 'Yes', 'No', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'One year', 'No', 'Electronic check', 26.9, '1250.85')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('0376-OIWME', 36, 'Yes', 'No', 'Fiber optic', 'Yes', 'No', 'No', 'No', 'Yes', 'Yes', 'Month-to-month', 'Yes', 'Electronic check', 93.6, '3366.05')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('0325-XBFAC', 8, 'Yes', 'No', 'Fiber optic', 'No', 'No', 'Yes', 'No', 'Yes', 'Yes', 'Month-to-month', 'Yes', 'Electronic check', 94.7, '740.3')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('2292-XQWSV', 40, 'No', 'No phone service', 'DSL', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'One year', 'No', 'Mailed check', 60.3, '2448.5')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('2252-JHJGE', 61, 'Yes', 'Yes', 'Fiber optic', 'Yes', 'No', 'Yes', 'No', 'Yes', 'Yes', 'One year', 'No', 'Electronic check', 104.0, '6363.45')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('6176-YJWAS', 72, 'Yes', 'Yes', 'Fiber optic', 'Yes', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Two year', 'Yes', 'Credit card (automatic)', 97.95, '7114.25')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('6383-ZTSIW', 39, 'Yes', 'No', 'Fiber optic', 'Yes', 'Yes', 'No', 'No', 'Yes', 'Yes', 'One year', 'No', 'Mailed check', 99.1, '3877.95')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('4365-MSDYN', 8, 'Yes', 'No', 'No', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'Month-to-month', 'Yes', 'Bank transfer (automatic)', 19.55, '161.15')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('1455-ESIQH', 1, 'Yes', 'No', 'Fiber optic', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'Month-to-month', 'Yes', 'Electronic check', 89.1, '89.1')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('4664-NJCMS', 33, 'No', 'No phone service', 'DSL', 'Yes', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'Two year', 'No', 'Bank transfer (automatic)', 59.55, '2016.3')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('4911-BANWH', 31, 'Yes', 'Yes', 'Fiber optic', 'No', 'No', 'No', 'No', 'Yes', 'No', 'Month-to-month', 'Yes', 'Credit card (automatic)', 86.55, '2697.4')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('7394-FKDNK', 9, 'Yes', 'No', 'Fiber optic', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'Month-to-month', 'No', 'Electronic check', 89.45, '853.1')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('8285-ABVLB', 70, 'Yes', 'No', 'No', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'Two year', 'No', 'Credit card (automatic)', 19.85, '1328.35')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('4644-OBGFZ', 55, 'Yes', 'No', 'No', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'One year', 'No', 'Mailed check', 19.5, '1026.35')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('8410-BGQXN', 4, 'Yes', 'No', 'No', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'Month-to-month', 'No', 'Mailed check', 19.4, '93.4')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('4091-TVOCN', 48, 'Yes', 'Yes', 'DSL', 'Yes', 'No', 'Yes', 'No', 'Yes', 'Yes', 'One year', 'Yes', 'Credit card (automatic)', 78.75, '3682.45')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('7157-SMCFK', 61, 'Yes', 'No', 'No', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'Two year', 'No', 'Mailed check', 19.75, '1124.2')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('9799-CAYJJ', 2, 'Yes', 'No', 'Fiber optic', 'No', 'No', 'No', 'No', 'No', 'No', 'Month-to-month', 'Yes', 'Electronic check', 69.3, '153.8')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('3683-QKIUE', 6, 'Yes', 'No', 'DSL', 'No', 'No', 'No', 'Yes', 'No', 'No', 'Month-to-month', 'Yes', 'Bank transfer (automatic)', 50.8, '288.05')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('3538-WZPHD', 3, 'No', 'No phone service', 'DSL', 'No', 'Yes', 'No', 'No', 'No', 'No', 'Month-to-month', 'Yes', 'Electronic check', 29.6, '79.45')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('8205-OTCHB', 22, 'No', 'No phone service', 'DSL', 'No', 'Yes', 'Yes', 'No', 'No', 'Yes', 'One year', 'Yes', 'Bank transfer (automatic)', 43.75, '903.6')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('7674-YTAFD', 33, 'Yes', 'No', 'Fiber optic', 'No', 'Yes', 'No', 'Yes', 'No', 'No', 'One year', 'Yes', 'Bank transfer (automatic)', 79.95, '2684.85')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('1571-SAVHK', 12, 'Yes', 'Yes', 'Fiber optic', 'No', 'No', 'No', 'Yes', 'Yes', 'Yes', 'Month-to-month', 'Yes', 'Mailed check', 99.95, '1132.75')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('1779-PWPMG', 72, 'Yes', 'Yes', 'Fiber optic', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Two year', 'Yes', 'Bank transfer (automatic)', 114.65, '8333.95')

INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('0426-TIRNE', 1, 'Yes', 'No', 'No', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'Month-to-month', 'No', 'Mailed check', 20.9, '20.9')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('0559-CKHUS', 29, 'Yes', 'No', 'No', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'Two year', 'Yes', 'Mailed check', 19.55, '521.8')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('0203-HHYIJ', 25, 'Yes', 'Yes', 'No', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'One year', 'No', 'Bank transfer (automatic)', 25.3, '676.35')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('6094-ZIVKX', 68, 'Yes', 'No', 'DSL', 'Yes', 'No', 'Yes', 'No', 'No', 'No', 'One year', 'Yes', 'Credit card (automatic)', 54.45, '3674.95')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('2897-DOVND', 2, 'Yes', 'No', 'Fiber optic', 'No', 'No', 'No', 'No', 'No', 'No', 'Month-to-month', 'Yes', 'Electronic check', 69.8, '146.65')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('8387-MOJJT', 42, 'Yes', 'No', 'Fiber optic', 'No', 'No', 'No', 'No', 'Yes', 'No', 'Month-to-month', 'Yes', 'Credit card (automatic)', 77.95, '3384')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('2587-YNLES', 6, 'Yes', 'No', 'No', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'Two year', 'No', 'Mailed check', 20.1, '100.35')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('6693-FRIRW', 18, 'Yes', 'No', 'Fiber optic', 'No', 'Yes', 'Yes', 'No', 'Yes', 'Yes', 'Month-to-month', 'No', 'Credit card (automatic)', 101.3, '1794.65')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('5976-JCJRH', 10, 'Yes', 'No', 'Fiber optic', 'No', 'No', 'No', 'No', 'No', 'No', 'Month-to-month', 'Yes', 'Electronic check', 70.3, '738.2')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('6749-UTDVX', 72, 'Yes', 'Yes', 'Fiber optic', 'No', 'Yes', 'Yes', 'No', 'Yes', 'Yes', 'Two year', 'Yes', 'Electronic check', 103.65, '7634.8')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('3552-CTCYF', 63, 'Yes', 'Yes', 'Fiber optic', 'No', 'Yes', 'Yes', 'No', 'Yes', 'Yes', 'Two year', 'Yes', 'Bank transfer (automatic)', 104.8, '6597.25')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('0068-FIGTF', 27, 'Yes', 'No', 'DSL', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'One year', 'No', 'Mailed check', 78.2, '2078.95')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('5622-UEJFI', 35, 'Yes', 'Yes', 'No', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'Two year', 'Yes', 'Credit card (automatic)', 25.4, '949.8')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('9524-EGPJC', 18, 'Yes', 'Yes', 'Fiber optic', 'No', 'No', 'No', 'Yes', 'No', 'Yes', 'Month-to-month', 'Yes', 'Electronic check', 90.1, '1612.75')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('5108-ADXWO', 11, 'Yes', 'No', 'Fiber optic', 'Yes', 'No', 'No', 'No', 'No', 'No', 'Month-to-month', 'Yes', 'Electronic check', 73.5, '791.75')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('9067-SQTNS', 44, 'Yes', 'No', 'No', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'One year', 'No', 'Bank transfer (automatic)', 20.6, '926')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('3639-XJHKQ', 19, 'Yes', 'No', 'DSL', 'Yes', 'Yes', 'Yes', 'No', 'No', 'No', 'Month-to-month', 'Yes', 'Electronic check', 60.6, '1297.8')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('8197-BFWVU', 72, 'Yes', 'Yes', 'DSL', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Two year', 'Yes', 'Bank transfer (automatic)', 93.25, '6688.95')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('5843-TTHGI', 18, 'Yes', 'No', 'DSL', 'No', 'No', 'Yes', 'No', 'No', 'No', 'Month-to-month', 'Yes', 'Mailed check', 50.0, '892.7')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('5651-WYIPH', 18, 'Yes', 'No', 'DSL', 'No', 'Yes', 'No', 'No', 'No', 'No', 'Month-to-month', 'Yes', 'Credit card (automatic)', 49.85, '865.75')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('3911-RSNHI', 71, 'No', 'No phone service', 'DSL', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Two year', 'Yes', 'Credit card (automatic)', 61.4, '4310.35')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('6865-JZNKO', 30, 'Yes', 'No', 'DSL', 'Yes', 'Yes', 'No', 'No', 'No', 'No', 'Month-to-month', 'Yes', 'Bank transfer (automatic)', 55.3, '1530.6')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('3275-RHRNE', 28, 'No', 'No phone service', 'DSL', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'One year', 'Yes', 'Credit card (automatic)', 60.0, '1682.05')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('7627-JKIAZ', 37, 'Yes', 'Yes', 'Fiber optic', 'No', 'No', 'Yes', 'No', 'No', 'No', 'Month-to-month', 'Yes', 'Credit card (automatic)', 78.95, '2839.65')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('4685-TFLLS', 18, 'Yes', 'No', 'No', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'One year', 'No', 'Bank transfer (automatic)', 19.8, '342.3')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('2245-ADZFJ', 31, 'Yes', 'Yes', 'DSL', 'No', 'Yes', 'No', 'Yes', 'Yes', 'Yes', 'Two year', 'No', 'Bank transfer (automatic)', 80.55, '2471.6')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('4482-FTFFX', 5, 'Yes', 'No', 'DSL', 'No', 'No', 'Yes', 'Yes', 'No', 'No', 'Month-to-month', 'No', 'Electronic check', 56.15, '291.45')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('5419-JKZNQ', 30, 'Yes', 'Yes', 'Fiber optic', 'No', 'No', 'No', 'No', 'No', 'No', 'Month-to-month', 'No', 'Mailed check', 77.9, '2351.45')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('5915-DGNVC', 49, 'Yes', 'Yes', 'DSL', 'Yes', 'Yes', 'Yes', 'No', 'No', 'Yes', 'One year', 'No', 'Electronic check', 71.8, '3472.05')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('2957-LOLHO', 12, 'Yes', 'No', 'DSL', 'No', 'No', 'No', 'No', 'No', 'No', 'Month-to-month', 'Yes', 'Bank transfer (automatic)', 45.4, '518.9')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('2777-PHDEI', 1, 'Yes', 'No', 'Fiber optic', 'No', 'No', 'No', 'No', 'Yes', 'No', 'Month-to-month', 'No', 'Electronic check', 78.05, '78.05')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('9565-DJPIB', 4, 'Yes', 'Yes', 'Fiber optic', 'No', 'Yes', 'No', 'No', 'Yes', 'No', 'Month-to-month', 'No', 'Mailed check', 89.6, '365.65')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('4390-KYULV', 3, 'Yes', 'No', 'No', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'Month-to-month', 'Yes', 'Credit card (automatic)', 20.55, '51.15')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('1678-FYZOW', 3, 'Yes', 'No', 'Fiber optic', 'No', 'No', 'No', 'No', 'Yes', 'No', 'Month-to-month', 'Yes', 'Electronic check', 79.4, '244.65')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('7349-ALMUX', 37, 'Yes', 'No', 'DSL', 'Yes', 'Yes', 'Yes', 'Yes', 'No', 'No', 'Two year', 'No', 'Bank transfer (automatic)', 65.6, '2313.8')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('9330-DHBFL', 23, 'Yes', 'No', 'DSL', 'Yes', 'Yes', 'Yes', 'Yes', 'No', 'No', 'One year', 'Yes', 'Mailed check', 66.25, '1533.8')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('6288-LBEAR', 23, 'Yes', 'No', 'Fiber optic', 'No', 'Yes', 'No', 'Yes', 'No', 'No', 'Month-to-month', 'Yes', 'Mailed check', 79.1, '1783.75')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('9233-PSYHO', 45, 'Yes', 'Yes', 'Fiber optic', 'No', 'No', 'Yes', 'No', 'Yes', 'Yes', 'One year', 'Yes', 'Bank transfer (automatic)', 100.15, '4459.8')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('6072-NUQCB', 22, 'Yes', 'No', 'No', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'One year', 'No', 'Bank transfer (automatic)', 20.25, '488.25')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('0447-RXSGD', 24, 'Yes', 'Yes', 'Fiber optic', 'No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'Month-to-month', 'Yes', 'Bank transfer (automatic)', 99.65, '2404.85')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('9916-AYHTC', 48, 'Yes', 'No', 'No', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'Two year', 'No', 'Credit card (automatic)', 19.85, '916')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('8824-RWFXJ', 3, 'Yes', 'No', 'DSL', 'No', 'Yes', 'Yes', 'No', 'No', 'No', 'Month-to-month', 'Yes', 'Mailed check', 56.15, '168.15')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('4884-ZTHVF', 8, 'Yes', 'No', 'Fiber optic', 'No', 'Yes', 'No', 'No', 'Yes', 'No', 'Month-to-month', 'Yes', 'Electronic check', 87.1, '713.6')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('8627-EHGIP', 44, 'No', 'No phone service', 'DSL', 'No', 'Yes', 'Yes', 'No', 'Yes', 'Yes', 'One year', 'Yes', 'Mailed check', 53.95, '2375.4')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('1020-JPQOW', 56, 'Yes', 'Yes', 'Fiber optic', 'No', 'Yes', 'Yes', 'Yes', 'No', 'No', 'Month-to-month', 'No', 'Electronic check', 90.55, '5116.6')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('3976-NLDEZ', 1, 'Yes', 'No', 'No', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'Month-to-month', 'No', 'Mailed check', 20.6, '20.6')

INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('8559-WNQZS', 1, 'Yes', 'No', 'No', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'Two year', 'No', 'Mailed check', 20.45, '20.45')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('4980-URKXC', 36, 'Yes', 'No', 'No', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'One year', 'No', 'Bank transfer (automatic)', 20.85, '720.05')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('3099-OONVS', 25, 'Yes', 'No', 'DSL', 'Yes', 'No', 'No', 'Yes', 'No', 'No', 'Month-to-month', 'No', 'Electronic check', 54.3, '1296.8')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('2710-WYVXG', 3, 'Yes', 'No', 'DSL', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes', 'Two year', 'No', 'Mailed check', 71.1, '213.35')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('5590-BYNII', 22, 'Yes', 'Yes', 'Fiber optic', 'Yes', 'No', 'No', 'No', 'Yes', 'Yes', 'Month-to-month', 'Yes', 'Electronic check', 100.75, '2095')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('0265-PSUAE', 16, 'Yes', 'No', 'Fiber optic', 'Yes', 'No', 'Yes', 'No', 'Yes', 'Yes', 'Month-to-month', 'No', 'Bank transfer (automatic)', 100.7, '1522.7')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('8152-UOBNY', 50, 'Yes', 'Yes', 'Fiber optic', 'No', 'Yes', 'No', 'Yes', 'Yes', 'Yes', 'One year', 'Yes', 'Electronic check', 106.8, '5347.95')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('8003-EWNDZ', 10, 'Yes', 'No', 'No', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'Month-to-month', 'Yes', 'Electronic check', 21.2, '222.65')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('4404-HIBDJ', 25, 'Yes', 'No', 'DSL', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'No', 'One year', 'No', 'Mailed check', 74.3, '1863.8')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('5959-BELXA', 32, 'Yes', 'Yes', 'Fiber optic', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'Month-to-month', 'Yes', 'Credit card (automatic)', 96.15, '3019.25')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('7643-RCHXS', 63, 'Yes', 'No', 'No', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'Two year', 'No', 'Electronic check', 19.35, '1263.85')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('4468-YDOVK', 5, 'Yes', 'No', 'DSL', 'No', 'No', 'No', 'Yes', 'No', 'No', 'Month-to-month', 'Yes', 'Bank transfer (automatic)', 48.65, '235.2')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('8919-FYFQZ', 44, 'No', 'No phone service', 'DSL', 'No', 'Yes', 'No', 'No', 'No', 'No', 'Month-to-month', 'Yes', 'Electronic check', 30.35, '1359.7')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('5565-FILXA', 16, 'Yes', 'Yes', 'Fiber optic', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'Month-to-month', 'Yes', 'Electronic check', 96.15, '1529.2')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('5815-HGGHV', 20, 'Yes', 'No', 'DSL', 'Yes', 'No', 'No', 'Yes', 'No', 'Yes', 'One year', 'Yes', 'Mailed check', 64.15, '1274.45')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('1552-AAGRX', 30, 'Yes', 'Yes', 'Fiber optic', 'Yes', 'No', 'No', 'Yes', 'Yes', 'Yes', 'Month-to-month', 'No', 'Bank transfer (automatic)', 106.4, '3211.9')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('7269-JISCY', 55, 'Yes', 'No', 'DSL', 'No', 'No', 'No', 'No', 'No', 'No', 'One year', 'No', 'Bank transfer (automatic)', 45.05, '2462.6')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('5446-DKWYW', 61, 'Yes', 'Yes', 'DSL', 'No', 'No', 'Yes', 'No', 'Yes', 'No', 'One year', 'Yes', 'Electronic check', 65.2, '3965.05')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('3506-LCJDC', 1, 'Yes', 'No', 'No', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'Month-to-month', 'No', 'Bank transfer (automatic)', 19.95, '19.95')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('0956-ACVZC', 54, 'Yes', 'No', 'Fiber optic', 'No', 'No', 'Yes', 'No', 'Yes', 'Yes', 'One year', 'Yes', 'Credit card (automatic)', 94.1, '5060.9')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('2482-CZGBB', 10, 'Yes', 'No', 'Fiber optic', 'No', 'No', 'No', 'No', 'No', 'No', 'Month-to-month', 'Yes', 'Electronic check', 70.0, '740')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('6682-QJDGB', 40, 'Yes', 'No', 'DSL', 'Yes', 'Yes', 'No', 'No', 'No', 'No', 'Month-to-month', 'Yes', 'Mailed check', 55.25, '2139.2')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('3128-YOVTD', 51, 'Yes', 'No', 'Fiber optic', 'Yes', 'Yes', 'No', 'No', 'No', 'No', 'Month-to-month', 'Yes', 'Bank transfer (automatic)', 79.15, '4018.55')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('1090-ESELR', 72, 'Yes', 'No', 'Fiber optic', 'Yes', 'Yes', 'No', 'Yes', 'Yes', 'Yes', 'Two year', 'No', 'Bank transfer (automatic)', 105.5, '7611.55')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('9570-KYEUA', 64, 'Yes', 'Yes', 'Fiber optic', 'Yes', 'No', 'Yes', 'Yes', 'No', 'Yes', 'Two year', 'No', 'Credit card (automatic)', 99.25, '6549.45')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('4707-MAXGU', 72, 'Yes', 'Yes', 'No', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'Two year', 'No', 'Credit card (automatic)', 25.85, '1872.2')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('7872-BAAZR', 53, 'Yes', 'No', 'No', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'One year', 'No', 'Bank transfer (automatic)', 19.55, '1007.9')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('2592-SEIFQ', 3, 'No', 'No phone service', 'DSL', 'No', 'No', 'No', 'No', 'No', 'No', 'Month-to-month', 'No', 'Electronic check', 24.75, '66.95')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('9603-OAIHC', 1, 'Yes', 'No', 'Fiber optic', 'No', 'No', 'No', 'No', 'No', 'No', 'Month-to-month', 'Yes', 'Electronic check', 70.05, '70.05')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('0637-UBJRP', 13, 'Yes', 'No', 'Fiber optic', 'Yes', 'No', 'No', 'No', 'No', 'Yes', 'Month-to-month', 'No', 'Electronic check', 84.05, '1095.3')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('5057-LCOUI', 39, 'No', 'No phone service', 'DSL', 'No', 'No', 'Yes', 'No', 'Yes', 'Yes', 'Month-to-month', 'Yes', 'Electronic check', 50.75, '2011.4')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('2754-XBHTB', 9, 'Yes', 'No', 'Fiber optic', 'No', 'No', 'No', 'No', 'Yes', 'No', 'Month-to-month', 'Yes', 'Bank transfer (automatic)', 77.65, '714.15')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('6518-KZXCB', 22, 'Yes', 'Yes', 'No', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'Two year', 'No', 'Mailed check', 25.25, '566.5')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('5331-RGMTT', 54, 'Yes', 'Yes', 'Fiber optic', 'No', 'No', 'Yes', 'No', 'Yes', 'Yes', 'Month-to-month', 'Yes', 'Credit card (automatic)', 99.05, '5295.7')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('1430-SFQSA', 29, 'No', 'No phone service', 'DSL', 'Yes', 'No', 'No', 'Yes', 'No', 'No', 'One year', 'No', 'Mailed check', 35.6, '1072.6')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('2889-FPWRM', 72, 'Yes', 'Yes', 'Fiber optic', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'One year', 'Yes', 'Bank transfer (automatic)', 117.8, '8684.8')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('2251-PYLPB', 72, 'Yes', 'Yes', 'DSL', 'Yes', 'Yes', 'Yes', 'Yes', 'No', 'Yes', 'Two year', 'No', 'Credit card (automatic)', 79.55, '5810.9')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('6599-RCLCJ', 47, 'Yes', 'Yes', 'Fiber optic', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Month-to-month', 'Yes', 'Electronic check', 109.55, '5124.55')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('5155-AZQPB', 28, 'Yes', 'Yes', 'DSL', 'No', 'No', 'No', 'No', 'No', 'No', 'Month-to-month', 'No', 'Mailed check', 49.9, '1410.25')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('8167-GJLRN', 3, 'No', 'No phone service', 'DSL', 'No', 'No', 'No', 'Yes', 'No', 'No', 'Month-to-month', 'No', 'Electronic check', 30.4, '82.15')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('4304-XUMGI', 50, 'Yes', 'Yes', 'DSL', 'Yes', 'Yes', 'Yes', 'No', 'No', 'Yes', 'Two year', 'Yes', 'Bank transfer (automatic)', 75.15, '3822.45')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('4510-HIMLV', 1, 'Yes', 'No', 'Fiber optic', 'No', 'No', 'No', 'No', 'No', 'No', 'Month-to-month', 'Yes', 'Electronic check', 69.8, '69.8')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('5349-IECLD', 2, 'Yes', 'No', 'Fiber optic', 'No', 'No', 'Yes', 'No', 'Yes', 'Yes', 'Month-to-month', 'No', 'Electronic check', 94.95, '178.1')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('3717-OEAUQ', 2, 'Yes', 'No', 'Fiber optic', 'No', 'No', 'No', 'No', 'No', 'No', 'Month-to-month', 'No', 'Mailed check', 70.7, '129.2')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('1984-FCOWB', 70, 'Yes', 'Yes', 'Fiber optic', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'One year', 'Yes', 'Electronic check', 109.5, '7674.55')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('5973-EJGDP', 51, 'Yes', 'Yes', 'Fiber optic', 'No', 'Yes', 'Yes', 'Yes', 'No', 'No', 'Month-to-month', 'Yes', 'Electronic check', 87.35, '4473')

INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('2452-MRMZF', 72, 'Yes', 'Yes', 'No', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'Two year', 'Yes', 'Credit card (automatic)', 25.7, '1937.4')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('6609-MXJHJ', 30, 'Yes', 'Yes', 'No', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'Two year', 'Yes', 'Mailed check', 25.1, '789.55')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('5981-ITEMU', 40, 'Yes', 'Yes', 'Fiber optic', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'Month-to-month', 'Yes', 'Bank transfer (automatic)', 97.1, '3706.95')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('0191-EQUUH', 25, 'No', 'No phone service', 'DSL', 'Yes', 'No', 'No', 'Yes', 'No', 'No', 'Two year', 'No', 'Bank transfer (automatic)', 35.05, '844.45')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('9253-VIFJQ', 65, 'Yes', 'Yes', 'DSL', 'Yes', 'Yes', 'Yes', 'No', 'No', 'No', 'One year', 'No', 'Credit card (automatic)', 67.05, '4309.55')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('1245-HARPS', 14, 'Yes', 'No', 'No', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'Two year', 'No', 'Mailed check', 20.4, '292.4')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('5627-TVBPP', 35, 'Yes', 'No', 'No', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'One year', 'Yes', 'Credit card (automatic)', 20.1, '644.5')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('1137-DGOWI', 30, 'Yes', 'No', 'DSL', 'No', 'Yes', 'Yes', 'Yes', 'No', 'Yes', 'One year', 'No', 'Bank transfer (automatic)', 70.25, '2198.9')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('8812-ZRHFP', 30, 'Yes', 'No', 'Fiber optic', 'No', 'No', 'Yes', 'No', 'No', 'Yes', 'One year', 'No', 'Electronic check', 86.45, '2538.05')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('5223-UZAVK', 64, 'Yes', 'No', 'Fiber optic', 'Yes', 'Yes', 'No', 'No', 'Yes', 'Yes', 'One year', 'Yes', 'Credit card (automatic)', 100.3, '6603.8')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('0730-BGQGF', 71, 'Yes', 'Yes', 'DSL', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Two year', 'No', 'Credit card (automatic)', 90.3, '6287.3')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('4430-UZIPO', 3, 'No', 'No phone service', 'DSL', 'No', 'Yes', 'No', 'Yes', 'No', 'No', 'Month-to-month', 'Yes', 'Mailed check', 36.85, '108.7')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('3030-YDNRM', 8, 'Yes', 'Yes', 'Fiber optic', 'No', 'No', 'No', 'No', 'No', 'No', 'Month-to-month', 'Yes', 'Electronic check', 74.85, '572.45')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('2025-JKFWI', 13, 'Yes', 'Yes', 'Fiber optic', 'No', 'No', 'No', 'Yes', 'Yes', 'Yes', 'Month-to-month', 'Yes', 'Mailed check', 99.0, '1301.7')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('2332-TODQS', 48, 'Yes', 'Yes', 'No', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'One year', 'No', 'Credit card (automatic)', 25.05, '1171.5')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('3709-OIJEA', 26, 'Yes', 'No', 'Fiber optic', 'No', 'Yes', 'Yes', 'Yes', 'No', 'No', 'One year', 'Yes', 'Electronic check', 85.2, '2184.6')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('0930-EHUZA', 36, 'Yes', 'No', 'DSL', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'No', 'One year', 'Yes', 'Mailed check', 76.35, '2606.35')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('9174-IHETN', 50, 'Yes', 'No', 'Fiber optic', 'No', 'No', 'No', 'No', 'No', 'No', 'Two year', 'No', 'Credit card (automatic)', 70.35, '3533.6')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('5724-BIDBU', 49, 'Yes', 'Yes', 'DSL', 'Yes', 'No', 'No', 'No', 'No', 'No', 'One year', 'Yes', 'Electronic check', 55.35, '2633.95')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('1217-VASWC', 43, 'Yes', 'No', 'Fiber optic', 'No', 'Yes', 'Yes', 'No', 'Yes', 'Yes', 'One year', 'Yes', 'Bank transfer (automatic)', 100.55, '4304')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('1735-XMJVH', 8, 'Yes', 'No', 'No', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'Month-to-month', 'Yes', 'Mailed check', 19.35, '152.6')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('1791-PQHBB', 2, 'Yes', 'No', 'DSL', 'Yes', 'No', 'No', 'No', 'No', 'Yes', 'Month-to-month', 'Yes', 'Credit card (automatic)', 61.2, '125.95')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('1492-QGCLU', 53, 'Yes', 'Yes', 'DSL', 'Yes', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'Month-to-month', 'No', 'Electronic check', 85.7, '4616.1')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('3327-YBAKM', 64, 'Yes', 'No', 'Fiber optic', 'Yes', 'No', 'No', 'Yes', 'Yes', 'Yes', 'One year', 'Yes', 'Mailed check', 96.9, '6314.35')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('5206-HPJKM', 17, 'Yes', 'No', 'DSL', 'Yes', 'Yes', 'No', 'No', 'No', 'No', 'Month-to-month', 'Yes', 'Credit card (automatic)', 55.5, '934.15')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('9814-AOUDH', 53, 'Yes', 'No', 'No', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'Two year', 'No', 'Credit card (automatic)', 19.5, '1050.5')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('6888-SBYAI', 1, 'Yes', 'No', 'DSL', 'Yes', 'No', 'No', 'No', 'No', 'No', 'Month-to-month', 'Yes', 'Mailed check', 50.7, '50.7')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('1545-ACTAS', 48, 'Yes', 'No', 'Fiber optic', 'Yes', 'No', 'Yes', 'No', 'Yes', 'Yes', 'One year', 'Yes', 'Bank transfer (automatic)', 99.7, '4977.2')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('7634-WSWDB', 8, 'No', 'No phone service', 'DSL', 'Yes', 'No', 'No', 'No', 'No', 'Yes', 'Month-to-month', 'Yes', 'Electronic check', 38.5, '330.8')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('6818-DJXAA', 10, 'Yes', 'No', 'Fiber optic', 'No', 'No', 'Yes', 'Yes', 'Yes', 'No', 'Month-to-month', 'Yes', 'Electronic check', 91.1, '964.35')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('2896-TBNBE', 40, 'Yes', 'No', 'Fiber optic', 'No', 'Yes', 'Yes', 'No', 'No', 'No', 'One year', 'No', 'Electronic check', 80.8, '3132.75')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('2498-XLDZR', 32, 'Yes', 'No', 'DSL', 'Yes', 'Yes', 'Yes', 'Yes', 'No', 'Yes', 'Two year', 'No', 'Mailed check', 73.6, '2316.85')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('5439-WIKXB', 41, 'Yes', 'No', 'Fiber optic', 'No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'Month-to-month', 'Yes', 'Electronic check', 94.55, '3851.45')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('3393-FMZPV', 25, 'Yes', 'Yes', 'Fiber optic', 'No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'Month-to-month', 'Yes', 'Electronic check', 100.25, '2387.75')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('1452-KIOVK', 22, 'Yes', 'Yes', 'Fiber optic', 'No', 'Yes', 'No', 'No', 'Yes', 'No', 'Month-to-month', 'Yes', 'Credit card (automatic)', 89.1, '1949.4')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('5598-IKHQQ', 72, 'Yes', 'Yes', 'No', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'Two year', 'No', 'Credit card (automatic)', 25.45, '1866.45')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('5789-LDFXO', 24, 'Yes', 'Yes', 'No', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'One year', 'No', 'Electronic check', 24.6, '592.65')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('6620-HVDUJ', 24, 'Yes', 'No', 'DSL', 'Yes', 'Yes', 'No', 'Yes', 'No', 'No', 'Month-to-month', 'No', 'Bank transfer (automatic)', 60.45, '1440.75')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('8659-HDIYE', 64, 'Yes', 'Yes', 'DSL', 'No', 'Yes', 'Yes', 'Yes', 'No', 'Yes', 'Month-to-month', 'No', 'Credit card (automatic)', 74.65, '4869.35')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('5760-IFJOZ', 3, 'Yes', 'Yes', 'Fiber optic', 'No', 'Yes', 'Yes', 'No', 'Yes', 'Yes', 'Month-to-month', 'No', 'Mailed check', 107.95, '313.6')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('7442-YGZFK', 1, 'Yes', 'Yes', 'DSL', 'No', 'No', 'No', 'No', 'No', 'No', 'Month-to-month', 'Yes', 'Credit card (automatic)', 49.8, '49.8')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('7537-CBQUZ', 63, 'Yes', 'Yes', 'Fiber optic', 'Yes', 'Yes', 'Yes', 'No', 'Yes', 'Yes', 'Month-to-month', 'Yes', 'Bank transfer (automatic)', 109.4, '7031.45')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('0939-EREMR', 13, 'Yes', 'No', 'DSL', 'No', 'No', 'Yes', 'Yes', 'No', 'No', 'Month-to-month', 'No', 'Mailed check', 53.45, '718.1')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('7395-XWZOY', 20, 'No', 'No phone service', 'DSL', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'No', 'Month-to-month', 'Yes', 'Credit card (automatic)', 55.0, '1165.55')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('0292-WEGCH', 54, 'Yes', 'Yes', 'DSL', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Month-to-month', 'Yes', 'Electronic check', 86.2, '4524.05')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('4487-ZYJZK', 38, 'Yes', 'No', 'No', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'One year', 'No', 'Credit card (automatic)', 19.6, '763.1')

INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('4727-MCYZG', 1, 'Yes', 'No', 'DSL', 'No', 'No', 'No', 'No', 'No', 'Yes', 'Month-to-month', 'No', 'Mailed check', 55.55, '55.55')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('2211-RMNHO', 68, 'Yes', 'Yes', 'DSL', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Two year', 'No', 'Bank transfer (automatic)', 85.3, '5560')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('3061-BCKYI', 14, 'Yes', 'No', 'No', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'Month-to-month', 'No', 'Mailed check', 19.9, '283.75')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('4464-JCOLN', 2, 'Yes', 'No', 'No', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'One year', 'No', 'Mailed check', 19.85, '35.9')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('7459-IMVYU', 38, 'Yes', 'Yes', 'DSL', 'Yes', 'Yes', 'Yes', 'Yes', 'No', 'No', 'Month-to-month', 'No', 'Electronic check', 69.95, '2657.55')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('8969-PRHFK', 18, 'Yes', 'No', 'No', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'One year', 'No', 'Mailed check', 19.65, '411.25')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('1550-EENBN', 31, 'Yes', 'Yes', 'Fiber optic', 'Yes', 'Yes', 'No', 'No', 'Yes', 'Yes', 'Month-to-month', 'No', 'Electronic check', 104.35, '3205.6')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('8619-IJNDK', 71, 'Yes', 'No', 'DSL', 'Yes', 'Yes', 'Yes', 'Yes', 'No', 'No', 'Two year', 'No', 'Credit card (automatic)', 64.05, '4492.9')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('0795-GMVQO', 67, 'Yes', 'Yes', 'Fiber optic', 'Yes', 'Yes', 'Yes', 'No', 'Yes', 'Yes', 'One year', 'No', 'Credit card (automatic)', 109.9, '7332.4')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('3967-KXAPS', 72, 'Yes', 'Yes', 'DSL', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Two year', 'No', 'Credit card (automatic)', 92.3, '6719.9')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('3757-NJYBX', 32, 'Yes', 'Yes', 'Fiber optic', 'No', 'Yes', 'Yes', 'No', 'Yes', 'Yes', 'Month-to-month', 'No', 'Bank transfer (automatic)', 106.35, '3520.75')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('2951-QOQTK', 4, 'Yes', 'Yes', 'Fiber optic', 'No', 'No', 'No', 'Yes', 'No', 'No', 'Month-to-month', 'No', 'Credit card (automatic)', 80.8, '332.45')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('1183-CANVH', 23, 'Yes', 'No', 'DSL', 'No', 'No', 'No', 'Yes', 'Yes', 'No', 'One year', 'No', 'Bank transfer (automatic)', 60.0, '1347.15')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('7520-HQWJU', 66, 'Yes', 'Yes', 'DSL', 'Yes', 'Yes', 'Yes', 'No', 'No', 'No', 'Month-to-month', 'Yes', 'Bank transfer (automatic)', 67.45, '4508.65')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('2883-ILGWO', 57, 'Yes', 'Yes', 'Fiber optic', 'No', 'Yes', 'No', 'Yes', 'Yes', 'Yes', 'Month-to-month', 'Yes', 'Bank transfer (automatic)', 104.9, '5913.95')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('0725-CXOTM', 36, 'Yes', 'Yes', 'DSL', 'Yes', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'One year', 'Yes', 'Credit card (automatic)', 89.65, '3348.1')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('3058-WQDRE', 13, 'No', 'No phone service', 'DSL', 'No', 'No', 'No', 'No', 'No', 'No', 'Month-to-month', 'Yes', 'Bank transfer (automatic)', 25.15, '331.85')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('8931-GJJIQ', 9, 'Yes', 'Yes', 'Fiber optic', 'No', 'No', 'No', 'No', 'No', 'Yes', 'Month-to-month', 'Yes', 'Electronic check', 83.3, '803.3')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('6786-OBWQR', 5, 'Yes', 'No', 'Fiber optic', 'No', 'No', 'No', 'No', 'Yes', 'No', 'Month-to-month', 'Yes', 'Electronic check', 80.85, '356.1')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('2990-OGYTD', 67, 'Yes', 'Yes', 'DSL', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Two year', 'No', 'Bank transfer (automatic)', 86.15, '5883.85')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('5875-YPQFJ', 1, 'Yes', 'No', 'Fiber optic', 'No', 'No', 'No', 'No', 'No', 'No', 'Month-to-month', 'Yes', 'Electronic check', 69.9, '69.9')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('2984-MIIZL', 4, 'Yes', 'No', 'Fiber optic', 'No', 'No', 'Yes', 'No', 'No', 'No', 'Month-to-month', 'Yes', 'Bank transfer (automatic)', 74.8, '321.9')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('6653-CBBOM', 1, 'Yes', 'No', 'Fiber optic', 'No', 'No', 'No', 'No', 'No', 'No', 'Month-to-month', 'Yes', 'Electronic check', 70.3, '70.3')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('2484-DGXPZ', 31, 'Yes', 'No', 'No', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'Month-to-month', 'Yes', 'Mailed check', 19.55, '658.95')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('7587-RZNME', 3, 'Yes', 'No', 'DSL', 'No', 'No', 'No', 'No', 'No', 'No', 'Month-to-month', 'Yes', 'Electronic check', 43.3, '123.65')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('3855-ONCAR', 4, 'Yes', 'No', 'Fiber optic', 'No', 'No', 'No', 'No', 'Yes', 'No', 'Month-to-month', 'Yes', 'Mailed check', 78.9, '299.75')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('2105-PHWON', 33, 'Yes', 'Yes', 'Fiber optic', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes', 'Month-to-month', 'Yes', 'Credit card (automatic)', 95.0, '3008.15')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('4534-WGCIR', 58, 'Yes', 'Yes', 'No', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'Two year', 'No', 'Credit card (automatic)', 25.15, '1509.9')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('8815-LMFLX', 25, 'Yes', 'Yes', 'No', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'Month-to-month', 'Yes', 'Bank transfer (automatic)', 25.4, '546.85')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('8443-ZRDBZ', 4, 'Yes', 'Yes', 'Fiber optic', 'No', 'No', 'No', 'No', 'No', 'No', 'Month-to-month', 'Yes', 'Electronic check', 76.05, '318.9')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('1591-MQJTP', 51, 'Yes', 'Yes', 'Fiber optic', 'Yes', 'No', 'Yes', 'No', 'No', 'Yes', 'One year', 'Yes', 'Bank transfer (automatic)', 93.65, '4839.15')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('1559-DTODC', 19, 'No', 'No phone service', 'DSL', 'No', 'No', 'No', 'No', 'No', 'No', 'Month-to-month', 'Yes', 'Bank transfer (automatic)', 25.15, '468.35')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('4566-QVRRW', 11, 'Yes', 'No', 'DSL', 'No', 'No', 'No', 'No', 'No', 'No', 'Month-to-month', 'Yes', 'Electronic check', 44.05, '483.7')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('5092-STPKP', 24, 'Yes', 'No', 'DSL', 'Yes', 'No', 'No', 'Yes', 'No', 'No', 'Month-to-month', 'No', 'Credit card (automatic)', 56.35, '1381.2')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('3094-JOJAI', 18, 'Yes', 'Yes', 'Fiber optic', 'No', 'No', 'No', 'No', 'No', 'No', 'Month-to-month', 'No', 'Mailed check', 74.15, '1387')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('5650-VDUDS', 4, 'No', 'No phone service', 'DSL', 'No', 'No', 'No', 'No', 'No', 'No', 'Month-to-month', 'Yes', 'Mailed check', 24.25, '96.05')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('3096-IZETN', 12, 'Yes', 'No', 'Fiber optic', 'No', 'No', 'No', 'No', 'No', 'Yes', 'Month-to-month', 'No', 'Bank transfer (automatic)', 78.1, '947.3')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('3254-YRILK', 19, 'Yes', 'Yes', 'Fiber optic', 'No', 'Yes', 'No', 'No', 'Yes', 'No', 'Month-to-month', 'Yes', 'Electronic check', 88.2, '1775.8')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('7813-ZGGAW', 31, 'Yes', 'Yes', 'Fiber optic', 'No', 'No', 'Yes', 'Yes', 'Yes', 'No', 'Month-to-month', 'Yes', 'Bank transfer (automatic)', 96.6, '2877.95')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('5756-OZRIO', 61, 'Yes', 'Yes', 'DSL', 'No', 'Yes', 'No', 'No', 'No', 'Yes', 'One year', 'No', 'Bank transfer (automatic)', 64.05, '3902.6')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('1016-DJTSV', 8, 'Yes', 'No', 'Fiber optic', 'No', 'No', 'No', 'No', 'No', 'No', 'Month-to-month', 'Yes', 'Electronic check', 69.7, '572.85')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('5204-HMGYF', 49, 'Yes', 'No', 'DSL', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'One year', 'Yes', 'Mailed check', 87.2, '4345')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('3669-LVWZB', 5, 'No', 'No phone service', 'DSL', 'No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'Month-to-month', 'Yes', 'Mailed check', 51.0, '305.95')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('2577-GVSIL', 35, 'Yes', 'Yes', 'DSL', 'No', 'No', 'No', 'Yes', 'Yes', 'Yes', 'One year', 'Yes', 'Bank transfer (automatic)', 73.45, '2661.1')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('1444-VVSGW', 70, 'Yes', 'Yes', 'Fiber optic', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'One year', 'No', 'Credit card (automatic)', 115.65, '7968.85')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('5419-JPRRN', 1, 'Yes', 'Yes', 'Fiber optic', 'No', 'No', 'Yes', 'No', 'Yes', 'Yes', 'Month-to-month', 'Yes', 'Electronic check', 101.45, '101.45')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('4673-KKSLS', 31, 'Yes', 'No', 'Fiber optic', 'Yes', 'No', 'Yes', 'Yes', 'No', 'No', 'Month-to-month', 'No', 'Electronic check', 87.6, '2724.25')

INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('7243-LCGGZ', 1, 'Yes', 'No', 'No', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'Month-to-month', 'No', 'Mailed check', 20.9, '20.9')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('3777-XROBG', 58, 'Yes', 'No', 'No', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'Two year', 'No', 'Credit card (automatic)', 19.55, '1079.65')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('5081-NWSUP', 10, 'Yes', 'No', 'DSL', 'No', 'Yes', 'No', 'Yes', 'No', 'Yes', 'One year', 'No', 'Mailed check', 64.9, '685.55')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('5442-BXVND', 33, 'Yes', 'Yes', 'No', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'Month-to-month', 'No', 'Bank transfer (automatic)', 24.25, '838.5')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('0612-RTZZA', 1, 'No', 'No phone service', 'DSL', 'No', 'No', 'No', 'No', 'No', 'No', 'Month-to-month', 'No', 'Electronic check', 25.25, '25.25')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('5103-MHMHY', 1, 'Yes', 'No', 'DSL', 'No', 'No', 'No', 'No', 'No', 'No', 'Month-to-month', 'No', 'Mailed check', 45.95, '45.95')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('5269-NRGDP', 42, 'Yes', 'No', 'DSL', 'No', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'One year', 'No', 'Electronic check', 73.15, '3088.25')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('4781-ZXYGU', 1, 'Yes', 'No', 'No', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'Month-to-month', 'Yes', 'Bank transfer (automatic)', 20.15, '20.15')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('0902-RFHOF', 38, 'Yes', 'No', 'No', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'One year', 'No', 'Mailed check', 20.1, '730.1')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('8601-QACRS', 5, 'Yes', 'Yes', 'DSL', 'No', 'No', 'No', 'No', 'No', 'No', 'Month-to-month', 'Yes', 'Mailed check', 50.6, '249.95')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('6333-YDVLT', 65, 'Yes', 'Yes', 'Fiber optic', 'Yes', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'One year', 'Yes', 'Credit card (automatic)', 110.0, '7138.65')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('5730-RIITO', 43, 'No', 'No phone service', 'DSL', 'Yes', 'Yes', 'No', 'No', 'No', 'No', 'Month-to-month', 'Yes', 'Credit card (automatic)', 33.45, '1500.25')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('8125-QPFJD', 72, 'Yes', 'Yes', 'DSL', 'Yes', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'Two year', 'Yes', 'Bank transfer (automatic)', 84.9, '6065.3')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('6270-OMFIW', 60, 'Yes', 'No', 'Fiber optic', 'No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'One year', 'Yes', 'Electronic check', 94.4, '5610.25')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('7879-CGSFV', 55, 'Yes', 'No', 'Fiber optic', 'Yes', 'Yes', 'No', 'No', 'Yes', 'Yes', 'One year', 'Yes', 'Mailed check', 100.9, '5552.05')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('3870-SPZSI', 70, 'Yes', 'Yes', 'Fiber optic', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Two year', 'Yes', 'Credit card (automatic)', 113.05, '7869.05')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('8873-GLDMH', 6, 'Yes', 'Yes', 'Fiber optic', 'No', 'No', 'No', 'No', 'No', 'No', 'Month-to-month', 'Yes', 'Mailed check', 73.85, '401.3')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('5716-LIBJC', 13, 'Yes', 'Yes', 'Fiber optic', 'No', 'Yes', 'Yes', 'No', 'Yes', 'Yes', 'One year', 'Yes', 'Credit card (automatic)', 104.15, '1299.1')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('0224-NIJLP', 8, 'Yes', 'No', 'No', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'Two year', 'No', 'Mailed check', 20.15, '165.5')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('4713-ZBURT', 45, 'Yes', 'Yes', 'Fiber optic', 'No', 'No', 'Yes', 'No', 'Yes', 'Yes', 'Two year', 'No', 'Bank transfer (automatic)', 99.7, '4634.35')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('3870-MQAMG', 54, 'Yes', 'Yes', 'Fiber optic', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'One year', 'No', 'Electronic check', 110.35, '5893.15')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('3550-SAHFP', 33, 'Yes', 'Yes', 'Fiber optic', 'No', 'No', 'No', 'No', 'No', 'Yes', 'Month-to-month', 'Yes', 'Electronic check', 83.35, '2757.85')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('4700-UBQMV', 21, 'Yes', 'Yes', 'DSL', 'Yes', 'No', 'No', 'No', 'Yes', 'Yes', 'One year', 'Yes', 'Bank transfer (automatic)', 75.9, '1549.75')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('0727-BMPLR', 55, 'Yes', 'Yes', 'Fiber optic', 'No', 'No', 'Yes', 'No', 'Yes', 'Yes', 'One year', 'Yes', 'Electronic check', 100.0, '5509.3')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('3627-FHKBK', 1, 'Yes', 'No', 'Fiber optic', 'Yes', 'No', 'No', 'No', 'No', 'No', 'Month-to-month', 'No', 'Mailed check', 75.3, '75.3')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('9142-KZXOP', 44, 'Yes', 'No', 'Fiber optic', 'No', 'No', 'No', 'No', 'No', 'No', 'Month-to-month', 'No', 'Credit card (automatic)', 68.85, '2958.95')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('5980-BDHPY', 72, 'Yes', 'Yes', 'DSL', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Two year', 'Yes', 'Bank transfer (automatic)', 87.1, '6230.1')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('4418-LZMSV', 13, 'Yes', 'No', 'DSL', 'No', 'Yes', 'Yes', 'Yes', 'No', 'No', 'Month-to-month', 'No', 'Bank transfer (automatic)', 61.8, '750.1')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('8123-QBNAZ', 36, 'Yes', 'Yes', 'Fiber optic', 'Yes', 'No', 'Yes', 'No', 'Yes', 'Yes', 'Month-to-month', 'Yes', 'Credit card (automatic)', 104.5, '3684.95')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('5743-KHMNA', 71, 'Yes', 'Yes', 'No', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'Two year', 'No', 'Bank transfer (automatic)', 25.55, '1898.1')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('0781-LKXBR', 9, 'Yes', 'Yes', 'Fiber optic', 'No', 'No', 'Yes', 'No', 'Yes', 'Yes', 'Month-to-month', 'Yes', 'Electronic check', 100.5, '918.6')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('9931-KGHOA', 46, 'Yes', 'Yes', 'DSL', 'Yes', 'No', 'No', 'No', 'No', 'No', 'Month-to-month', 'No', 'Bank transfer (automatic)', 55.0, '2473.95')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('7124-UGSUR', 61, 'Yes', 'Yes', 'Fiber optic', 'No', 'Yes', 'Yes', 'No', 'Yes', 'Yes', 'One year', 'Yes', 'Credit card (automatic)', 104.4, '6405')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('5329-KRDTM', 72, 'Yes', 'Yes', 'DSL', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'No', 'Two year', 'No', 'Credit card (automatic)', 77.35, '5396.25')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('1024-VRZHF', 11, 'Yes', 'Yes', 'Fiber optic', 'No', 'No', 'No', 'No', 'No', 'No', 'Month-to-month', 'Yes', 'Electronic check', 74.95, '825.7')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('4482-EWFMI', 2, 'Yes', 'No', 'Fiber optic', 'No', 'No', 'No', 'No', 'No', 'No', 'Month-to-month', 'Yes', 'Electronic check', 69.7, '135.2')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('0366-NQSHS', 2, 'Yes', 'No', 'No', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'Month-to-month', 'No', 'Mailed check', 19.35, '46.35')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('8752-STIVR', 4, 'Yes', 'No', 'Fiber optic', 'No', 'No', 'No', 'No', 'Yes', 'No', 'Month-to-month', 'Yes', 'Electronic check', 79.0, '303.15')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('8878-HMWBV', 3, 'Yes', 'No', 'DSL', 'No', 'No', 'Yes', 'No', 'No', 'No', 'Month-to-month', 'Yes', 'Electronic check', 49.15, '169.05')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('3050-GBUSH', 3, 'No', 'No phone service', 'DSL', 'No', 'No', 'No', 'No', 'Yes', 'No', 'Month-to-month', 'Yes', 'Credit card (automatic)', 34.8, '113.95')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('6718-BDGHG', 43, 'Yes', 'Yes', 'DSL', 'No', 'No', 'No', 'Yes', 'Yes', 'No', 'One year', 'Yes', 'Bank transfer (automatic)', 64.85, '2908.2')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('1830-IPXVJ', 61, 'Yes', 'No', 'No', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'Two year', 'No', 'Credit card (automatic)', 19.75, '1311.6')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('7481-ATQQS', 49, 'Yes', 'Yes', 'Fiber optic', 'No', 'No', 'Yes', 'No', 'No', 'Yes', 'Month-to-month', 'Yes', 'Credit card (automatic)', 90.85, '4515.85')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('5203-XEHAX', 34, 'Yes', 'No', 'DSL', 'Yes', 'Yes', 'No', 'No', 'No', 'Yes', 'One year', 'No', 'Electronic check', 64.35, '2053.05')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('2740-TVLFN', 1, 'Yes', 'Yes', 'DSL', 'No', 'No', 'No', 'No', 'No', 'No', 'Month-to-month', 'Yes', 'Electronic check', 50.15, '50.15')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('7054-LGEQW', 1, 'Yes', 'No', 'DSL', 'No', 'No', 'No', 'No', 'No', 'No', 'Month-to-month', 'No', 'Mailed check', 45.95, '45.95')

INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('5334-AFQJB', 72, 'Yes', 'Yes', 'No', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'Two year', 'Yes', 'Credit card (automatic)', 25.1, '1789.9')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('0641-EVBOJ', 3, 'Yes', 'No', 'Fiber optic', 'Yes', 'No', 'No', 'Yes', 'No', 'No', 'Month-to-month', 'Yes', 'Mailed check', 82.3, '214.4')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('8015-IHCGW', 72, 'Yes', 'Yes', 'Fiber optic', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Two year', 'Yes', 'Electronic check', 115.5, '8425.15')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('8746-OQQRW', 4, 'Yes', 'Yes', 'No', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'Month-to-month', 'No', 'Mailed check', 25.25, '101.9')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('3370-HXOPH', 3, 'Yes', 'Yes', 'Fiber optic', 'No', 'No', 'No', 'No', 'No', 'No', 'Month-to-month', 'No', 'Electronic check', 76.1, '257.6')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('2722-JMONI', 1, 'Yes', 'No', 'DSL', 'Yes', 'No', 'No', 'No', 'No', 'No', 'Month-to-month', 'Yes', 'Electronic check', 49.55, '49.55')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('0475-RIJEP', 43, 'Yes', 'Yes', 'Fiber optic', 'No', 'Yes', 'No', 'No', 'No', 'No', 'Month-to-month', 'Yes', 'Electronic check', 77.85, '3365.85')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('8111-BKVDS', 10, 'No', 'No phone service', 'DSL', 'Yes', 'Yes', 'Yes', 'No', 'No', 'No', 'Month-to-month', 'No', 'Bank transfer (automatic)', 40.7, '449.3')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('0224-RLWWD', 2, 'Yes', 'No', 'DSL', 'No', 'No', 'No', 'No', 'No', 'No', 'Month-to-month', 'Yes', 'Electronic check', 44.3, '89.3')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('6508-NJYRO', 15, 'Yes', 'No', 'No', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'One year', 'No', 'Mailed check', 18.8, '294.95')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('3411-WLRSQ', 3, 'Yes', 'No', 'Fiber optic', 'No', 'Yes', 'No', 'No', 'No', 'No', 'Month-to-month', 'Yes', 'Bank transfer (automatic)', 74.6, '239.05')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('8316-BBQAY', 65, 'No', 'No phone service', 'DSL', 'Yes', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'Two year', 'No', 'Credit card (automatic)', 59.95, '3921.1')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('2150-OEGBV', 27, 'Yes', 'No', 'No', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'One year', 'No', 'Bank transfer (automatic)', 20.1, '562.6')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('3551-HUAZH', 1, 'Yes', 'Yes', 'Fiber optic', 'No', 'No', 'No', 'No', 'No', 'No', 'Month-to-month', 'Yes', 'Electronic check', 74.4, '74.4')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('8884-FEEWR', 35, 'Yes', 'No', 'No', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'One year', 'No', 'Bank transfer (automatic)', 20.6, '754')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('5968-VXZLG', 2, 'Yes', 'No', 'DSL', 'No', 'No', 'No', 'No', 'No', 'No', 'Month-to-month', 'Yes', 'Bank transfer (automatic)', 46.6, '87.9')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('3070-BDOQC', 60, 'Yes', 'No', 'Fiber optic', 'No', 'Yes', 'Yes', 'No', 'Yes', 'Yes', 'Two year', 'Yes', 'Electronic check', 99.65, '5941.05')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('2821-WARNZ', 49, 'Yes', 'No', 'No', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'One year', 'No', 'Credit card (automatic)', 19.45, '921.3')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('2108-XWMPY', 3, 'No', 'No phone service', 'DSL', 'Yes', 'Yes', 'No', 'No', 'No', 'No', 'Month-to-month', 'Yes', 'Mailed check', 35.45, '106.85')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('8194-PEEBY', 24, 'Yes', 'No', 'No', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'One year', 'No', 'Mailed check', 19.9, '533.5')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('1832-PEUTS', 62, 'Yes', 'Yes', 'Fiber optic', 'No', 'No', 'Yes', 'No', 'Yes', 'No', 'Two year', 'Yes', 'Credit card (automatic)', 89.1, '5411.65')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('2685-SREOM', 25, 'Yes', 'Yes', 'Fiber optic', 'No', 'No', 'Yes', 'No', 'No', 'Yes', 'Month-to-month', 'Yes', 'Electronic check', 89.1, '2368.4')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('2657-VPXTA', 10, 'Yes', 'No', 'Fiber optic', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'Month-to-month', 'Yes', 'Electronic check', 88.85, '929.45')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('5067-WJEUN', 67, 'Yes', 'No', 'DSL', 'Yes', 'Yes', 'No', 'No', 'No', 'No', 'Two year', 'Yes', 'Bank transfer (automatic)', 54.2, '3838.2')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('2205-YMZZJ', 7, 'Yes', 'Yes', 'Fiber optic', 'No', 'No', 'No', 'No', 'Yes', 'No', 'Month-to-month', 'Yes', 'Electronic check', 84.8, '546.95')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('4277-UDIEF', 24, 'Yes', 'Yes', 'DSL', 'Yes', 'No', 'No', 'Yes', 'Yes', 'Yes', 'Month-to-month', 'No', 'Bank transfer (automatic)', 81.0, '1923.85')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('1480-BKXGA', 72, 'Yes', 'Yes', 'Fiber optic', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Two year', 'Yes', 'Bank transfer (automatic)', 116.05, '8404.9')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('4648-YPBTM', 53, 'Yes', 'Yes', 'DSL', 'No', 'Yes', 'Yes', 'Yes', 'No', 'Yes', 'Two year', 'Yes', 'Bank transfer (automatic)', 73.9, '3958.25')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('3097-NQYSN', 2, 'Yes', 'Yes', 'Fiber optic', 'No', 'No', 'No', 'No', 'Yes', 'No', 'Month-to-month', 'Yes', 'Mailed check', 86.85, '156.35')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('9250-WYPLL', 5, 'Yes', 'Yes', 'Fiber optic', 'No', 'No', 'No', 'No', 'No', 'No', 'Month-to-month', 'No', 'Electronic check', 75.55, '413.65')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('5245-VDBUR', 52, 'No', 'No phone service', 'DSL', 'Yes', 'No', 'Yes', 'No', 'No', 'No', 'One year', 'No', 'Mailed check', 35.45, '1958.95')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('8468-FZTOE', 72, 'Yes', 'No', 'DSL', 'Yes', 'Yes', 'Yes', 'Yes', 'No', 'Yes', 'Two year', 'Yes', 'Electronic check', 74.35, '5237.4')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('7639-OPLNG', 70, 'Yes', 'Yes', 'DSL', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'No', 'Two year', 'Yes', 'Bank transfer (automatic)', 79.25, '5731.85')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('8631-XVRZL', 9, 'Yes', 'No', 'No', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'One year', 'Yes', 'Mailed check', 20.15, '163.7')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('1051-GEJLJ', 2, 'Yes', 'No', 'No', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'Month-to-month', 'No', 'Mailed check', 19.5, '27.55')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('5753-QQWPW', 28, 'Yes', 'No', 'DSL', 'Yes', 'Yes', 'No', 'Yes', 'No', 'No', 'One year', 'Yes', 'Electronic check', 59.9, '1654.7')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('9339-FIIJL', 72, 'Yes', 'Yes', 'DSL', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Two year', 'No', 'Bank transfer (automatic)', 85.95, '6151.9')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('8644-XYTSV', 42, 'No', 'No phone service', 'DSL', 'Yes', 'No', 'No', 'No', 'Yes', 'No', 'Month-to-month', 'Yes', 'Bank transfer (automatic)', 40.15, '1626.05')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('6688-UZPWD', 11, 'Yes', 'Yes', 'Fiber optic', 'No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'Month-to-month', 'Yes', 'Electronic check', 102.0, '1145.35')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('1534-OULXE', 61, 'Yes', 'No', 'DSL', 'Yes', 'No', 'No', 'No', 'No', 'No', 'One year', 'Yes', 'Bank transfer (automatic)', 49.7, '2961.4')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('3902-MIVLE', 63, 'Yes', 'Yes', 'DSL', 'Yes', 'No', 'Yes', 'Yes', 'No', 'Yes', 'Two year', 'No', 'Mailed check', 75.7, '4676.7')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('4237-RLAQD', 1, 'Yes', 'No', 'DSL', 'No', 'No', 'No', 'No', 'No', 'No', 'Month-to-month', 'Yes', 'Mailed check', 45.85, '45.85')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('1208-DNHLN', 23, 'Yes', 'Yes', 'DSL', 'No', 'No', 'No', 'No', 'No', 'No', 'One year', 'Yes', 'Credit card (automatic)', 48.35, '1067.15')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('0704-VCUMB', 61, 'Yes', 'No', 'No', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'Two year', 'No', 'Credit card (automatic)', 20.25, '1278.8')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('2550-QHZGP', 7, 'Yes', 'No', 'No', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'One year', 'No', 'Mailed check', 19.5, '128.6')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('7817-OMJNA', 14, 'Yes', 'No', 'No', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'One year', 'No', 'Bank transfer (automatic)', 20.4, '275.7')

INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('3146-MSEGF', 72, 'Yes', 'Yes', 'DSL', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Two year', 'Yes', 'Credit card (automatic)', 88.05, '6425.65')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('1045-LTCYT', 8, 'Yes', 'No', 'No', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'Month-to-month', 'No', 'Credit card (automatic)', 21.05, '139.75')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('0661-KQHNK', 6, 'Yes', 'No', 'No', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'One year', 'No', 'Credit card (automatic)', 19.0, '105.5')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('6711-VTNRE', 36, 'Yes', 'No', 'Fiber optic', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes', 'Month-to-month', 'Yes', 'Electronic check', 87.55, '3078.1')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('4312-KFRXN', 72, 'Yes', 'Yes', 'No', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'Two year', 'No', 'Mailed check', 25.4, '1710.9')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('0587-DMGBH', 8, 'Yes', 'No', 'DSL', 'Yes', 'No', 'No', 'No', 'No', 'No', 'Month-to-month', 'Yes', 'Electronic check', 49.85, '365.55')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('6725-TPKJO', 44, 'Yes', 'No', 'No', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'Two year', 'No', 'Mailed check', 20.05, '845.25')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('8630-FJLIB', 18, 'Yes', 'No', 'Fiber optic', 'No', 'No', 'No', 'No', 'No', 'No', 'Month-to-month', 'Yes', 'Electronic check', 69.8, '1221.65')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('0089-IIQKO', 39, 'Yes', 'Yes', 'Fiber optic', 'No', 'No', 'No', 'Yes', 'Yes', 'Yes', 'Month-to-month', 'Yes', 'Credit card (automatic)', 99.95, '3767.4')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('4742-DRORA', 60, 'Yes', 'Yes', 'Fiber optic', 'Yes', 'No', 'Yes', 'No', 'Yes', 'No', 'One year', 'Yes', 'Bank transfer (automatic)', 95.4, '5812')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('8779-QRDMV', 1, 'No', 'No phone service', 'DSL', 'No', 'No', 'Yes', 'No', 'No', 'Yes', 'Month-to-month', 'Yes', 'Electronic check', 39.65, '39.65')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('7047-YXDMZ', 21, 'Yes', 'No', 'No', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'Month-to-month', 'No', 'Mailed check', 20.0, '417.7')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('6901-GOGZG', 60, 'Yes', 'Yes', 'DSL', 'Yes', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'Two year', 'Yes', 'Electronic check', 84.95, '4984.85')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('0654-PQKDW', 62, 'Yes', 'No', 'DSL', 'Yes', 'No', 'Yes', 'Yes', 'Yes', 'No', 'One year', 'Yes', 'Bank transfer (automatic)', 70.75, '4263.45')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('1226-JZNKR', 8, 'Yes', 'No', 'No', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'One year', 'No', 'Electronic check', 19.8, '160.05')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('5666-MBJPT', 65, 'Yes', 'Yes', 'No', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'Two year', 'Yes', 'Bank transfer (automatic)', 25.1, '1725')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('9867-JCZSP', 17, 'Yes', 'No', 'No', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'One year', 'No', 'Mailed check', 20.75, '418.25')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('1699-UOTXU', 60, 'Yes', 'No', 'DSL', 'Yes', 'Yes', 'Yes', 'No', 'No', 'No', 'Two year', 'No', 'Electronic check', 61.4, '3638.25')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('4946-EDSEW', 11, 'Yes', 'No', 'No', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'Month-to-month', 'Yes', 'Mailed check', 19.25, '180.3')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('1796-JANOW', 2, 'Yes', 'No', 'No', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'Month-to-month', 'No', 'Mailed check', 19.95, '38.15')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('5519-YLDGW', 21, 'Yes', 'Yes', 'Fiber optic', 'Yes', 'No', 'Yes', 'No', 'Yes', 'Yes', 'Month-to-month', 'Yes', 'Electronic check', 103.9, '2254.2')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('3086-RUCRN', 66, 'Yes', 'Yes', 'Fiber optic', 'Yes', 'Yes', 'Yes', 'Yes', 'No', 'Yes', 'Month-to-month', 'Yes', 'Bank transfer (automatic)', 103.1, '6595')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('7469-LKBCI', 16, 'Yes', 'No', 'No', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'Two year', 'No', 'Credit card (automatic)', 18.95, '326.8')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('3569-VLDHH', 66, 'Yes', 'No', 'DSL', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'No', 'One year', 'Yes', 'Electronic check', 75.1, '5013')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('2933-XEUJM', 46, 'Yes', 'Yes', 'DSL', 'Yes', 'No', 'Yes', 'No', 'Yes', 'Yes', 'Two year', 'No', 'Mailed check', 79.2, '3593.8')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('5504-WSIUR', 70, 'Yes', 'Yes', 'Fiber optic', 'No', 'Yes', 'Yes', 'Yes', 'No', 'No', 'One year', 'Yes', 'Bank transfer (automatic)', 90.25, '6385.95')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('6585-WCEWR', 72, 'Yes', 'No', 'No', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'Two year', 'No', 'Electronic check', 20.35, '1354.4')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('4146-SVFUD', 1, 'Yes', 'No', 'DSL', 'No', 'No', 'No', 'No', 'No', 'No', 'Month-to-month', 'No', 'Mailed check', 44.6, '44.6')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('5701-SVCWR', 1, 'Yes', 'Yes', 'No', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'Month-to-month', 'No', 'Mailed check', 24.0, '24')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('4822-RVYBB', 8, 'Yes', 'Yes', 'Fiber optic', 'No', 'No', 'Yes', 'No', 'Yes', 'Yes', 'Month-to-month', 'Yes', 'Electronic check', 100.6, '819.4')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('8805-JNRAZ', 2, 'Yes', 'No', 'DSL', 'No', 'Yes', 'No', 'No', 'No', 'No', 'Month-to-month', 'No', 'Mailed check', 49.2, '103.7')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('3308-MHOOC', 1, 'Yes', 'No', 'No', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'Month-to-month', 'Yes', 'Mailed check', 19.2, '19.2')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('4378-BZYFP', 17, 'Yes', 'No', 'No', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'One year', 'Yes', 'Mailed check', 20.5, '365.8')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('9830-ECLEN', 58, 'No', 'No phone service', 'DSL', 'Yes', 'Yes', 'Yes', 'No', 'Yes', 'No', 'One year', 'No', 'Mailed check', 50.0, '2919.85')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('1498-NHTLT', 59, 'Yes', 'No', 'DSL', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Two year', 'Yes', 'Electronic check', 86.75, '5186')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('1513-XNPPH', 12, 'Yes', 'No', 'Fiber optic', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes', 'Month-to-month', 'Yes', 'Electronic check', 89.4, '1095.65')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('4398-HSCJH', 3, 'Yes', 'Yes', 'DSL', 'No', 'No', 'No', 'Yes', 'Yes', 'No', 'Month-to-month', 'Yes', 'Electronic check', 63.6, '155.65')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('7595-EHCDL', 32, 'No', 'No phone service', 'DSL', 'No', 'No', 'Yes', 'No', 'Yes', 'Yes', 'Month-to-month', 'No', 'Credit card (automatic)', 50.6, '1653.45')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('5215-LNLDJ', 7, 'No', 'No phone service', 'DSL', 'No', 'No', 'No', 'No', 'No', 'No', 'Month-to-month', 'Yes', 'Electronic check', 24.7, '149.05')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('7677-SJJJK', 8, 'Yes', 'No', 'No', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'One year', 'No', 'Credit card (automatic)', 19.9, '153.95')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('9992-RRAMN', 22, 'Yes', 'Yes', 'Fiber optic', 'No', 'No', 'No', 'No', 'No', 'Yes', 'Month-to-month', 'Yes', 'Electronic check', 85.1, '1873.7')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('6242-FEGFD', 66, 'Yes', 'Yes', 'Fiber optic', 'Yes', 'Yes', 'Yes', 'Yes', 'No', 'No', 'Two year', 'No', 'Mailed check', 96.6, '6424.25')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('3956-CJUST', 23, 'Yes', 'No', 'Fiber optic', 'Yes', 'No', 'No', 'No', 'No', 'No', 'Month-to-month', 'Yes', 'Bank transfer (automatic)', 75.4, '1643.55')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('4844-JJWUY', 1, 'Yes', 'No', 'Fiber optic', 'No', 'Yes', 'No', 'No', 'No', 'Yes', 'Month-to-month', 'Yes', 'Electronic check', 86.0, '86')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('3703-TTEPD', 21, 'Yes', 'No', 'DSL', 'Yes', 'No', 'Yes', 'No', 'Yes', 'No', 'Month-to-month', 'No', 'Bank transfer (automatic)', 65.35, '1424.4')

INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('5575-TPIZQ', 46, 'Yes', 'Yes', 'Fiber optic', 'Yes', 'No', 'No', 'No', 'Yes', 'No', 'Month-to-month', 'Yes', 'Credit card (automatic)', 89.15, '4245.55')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('2075-PUEPR', 55, 'Yes', 'No', 'No', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'Two year', 'No', 'Bank transfer (automatic)', 19.35, '1153.25')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('0506-LVNGN', 5, 'Yes', 'No', 'Fiber optic', 'No', 'No', 'Yes', 'No', 'No', 'No', 'Month-to-month', 'Yes', 'Credit card (automatic)', 75.55, '349.65')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('4140-MUHUG', 3, 'Yes', 'No', 'Fiber optic', 'No', 'No', 'Yes', 'No', 'Yes', 'No', 'Month-to-month', 'Yes', 'Electronic check', 86.85, '220.95')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('7968-QUXNS', 6, 'Yes', 'No', 'No', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'Month-to-month', 'No', 'Mailed check', 18.95, '110.15')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('9530-GRMJG', 70, 'Yes', 'Yes', 'DSL', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Two year', 'Yes', 'Electronic check', 84.1, '5979.7')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('2123-VSCOT', 59, 'Yes', 'Yes', 'DSL', 'No', 'No', 'Yes', 'Yes', 'Yes', 'No', 'Two year', 'Yes', 'Bank transfer (automatic)', 72.1, '4194.85')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('9411-TPQQV', 40, 'No', 'No phone service', 'DSL', 'Yes', 'No', 'No', 'Yes', 'Yes', 'Yes', 'One year', 'Yes', 'Bank transfer (automatic)', 54.55, '2236.2')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('3973-SKMLN', 71, 'Yes', 'No', 'No', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'Two year', 'Yes', 'Credit card (automatic)', 19.9, '1355.1')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('9696-RMYBA', 5, 'Yes', 'No', 'Fiber optic', 'No', 'No', 'No', 'No', 'Yes', 'No', 'Month-to-month', 'Yes', 'Mailed check', 80.1, '398.55')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('8734-DKSTZ', 10, 'Yes', 'Yes', 'Fiber optic', 'No', 'No', 'No', 'No', 'No', 'Yes', 'Month-to-month', 'No', 'Electronic check', 85.95, '858.6')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('5336-UFNZP', 65, 'Yes', 'Yes', 'Fiber optic', 'No', 'Yes', 'Yes', 'No', 'Yes', 'Yes', 'One year', 'Yes', 'Electronic check', 107.45, '7047.5')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('6180-YBIQI', 5, 'No', 'No phone service', 'DSL', 'No', 'No', 'No', 'No', 'No', 'No', 'Month-to-month', 'No', 'Mailed check', 24.3, '100.2')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('1406-PUQVY', 1, 'Yes', 'No', 'DSL', 'No', 'Yes', 'No', 'No', 'No', 'No', 'Month-to-month', 'Yes', 'Electronic check', 49.9, '49.9')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('5016-LIPDW', 57, 'Yes', 'No', 'No', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'One year', 'No', 'Mailed check', 19.4, '1061.6')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('6418-PIQSP', 62, 'Yes', 'No', 'DSL', 'Yes', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'Two year', 'No', 'Mailed check', 81.0, '4985.9')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('3280-MRDOF', 30, 'Yes', 'Yes', 'DSL', 'No', 'No', 'Yes', 'Yes', 'Yes', 'No', 'Two year', 'Yes', 'Credit card (automatic)', 69.1, '2093.9')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('3016-KSVCP', 29, 'No', 'No phone service', 'DSL', 'No', 'No', 'No', 'No', 'Yes', 'No', 'Month-to-month', 'No', 'Mailed check', 33.75, '1009.25')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('2908-WGAXL', 56, 'Yes', 'Yes', 'No', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'Two year', 'Yes', 'Credit card (automatic)', 24.95, '1468.9')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('6968-MHOMU', 58, 'No', 'No phone service', 'DSL', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'One year', 'Yes', 'Credit card (automatic)', 45.0, '2689.35')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('2851-STERV', 35, 'Yes', 'No', 'DSL', 'No', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'One year', 'Yes', 'Electronic check', 73.0, '2471.25')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('8466-PZBLH', 67, 'Yes', 'Yes', 'Fiber optic', 'Yes', 'No', 'No', 'Yes', 'Yes', 'Yes', 'Two year', 'No', 'Bank transfer (automatic)', 104.6, '6885.75')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('2126-GSEGL', 70, 'Yes', 'Yes', 'DSL', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Two year', 'Yes', 'Bank transfer (automatic)', 84.8, '5917.55')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('7508-KBIMB', 24, 'Yes', 'No', 'DSL', 'Yes', 'No', 'Yes', 'No', 'No', 'No', 'One year', 'Yes', 'Credit card (automatic)', 56.25, '1454.25')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('5575-GNVDE', 34, 'Yes', 'No', 'DSL', 'Yes', 'No', 'Yes', 'No', 'No', 'No', 'One year', 'No', 'Mailed check', 56.95, '1889.5')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('2674-MLXMN', 71, 'Yes', 'Yes', 'Fiber optic', 'No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'Month-to-month', 'Yes', 'Credit card (automatic)', 99.65, '6951.15')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('6630-UJZMY', 4, 'Yes', 'Yes', 'Fiber optic', 'No', 'No', 'No', 'No', 'Yes', 'No', 'Month-to-month', 'Yes', 'Electronic check', 83.25, '308.05')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('1871-MOWRM', 12, 'Yes', 'No', 'Fiber optic', 'Yes', 'No', 'No', 'Yes', 'No', 'No', 'Month-to-month', 'No', 'Bank transfer (automatic)', 80.85, '866.45')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('3426-NIYYL', 15, 'Yes', 'Yes', 'DSL', 'No', 'No', 'No', 'No', 'No', 'No', 'Month-to-month', 'No', 'Electronic check', 51.55, '765.5')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('5512-IDZEI', 46, 'Yes', 'Yes', 'No', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'One year', 'No', 'Electronic check', 24.9, '1174.8')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('2408-PSJVE', 44, 'Yes', 'No', 'DSL', 'No', 'Yes', 'Yes', 'Yes', 'No', 'No', 'Month-to-month', 'Yes', 'Mailed check', 61.9, '2924.05')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('3352-ALMCK', 40, 'Yes', 'Yes', 'Fiber optic', 'No', 'Yes', 'Yes', 'No', 'Yes', 'Yes', 'Month-to-month', 'Yes', 'Mailed check', 102.65, '4108.15')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('9221-OTIVJ', 14, 'Yes', 'Yes', 'Fiber optic', 'No', 'Yes', 'Yes', 'No', 'Yes', 'Yes', 'Month-to-month', 'Yes', 'Electronic check', 104.85, '1531.4')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('0993-OSGPT', 68, 'Yes', 'No', 'DSL', 'No', 'Yes', 'Yes', 'Yes', 'No', 'No', 'One year', 'Yes', 'Bank transfer (automatic)', 60.65, '3975.9')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('6603-YRDCJ', 33, 'Yes', 'No', 'DSL', 'Yes', 'Yes', 'No', 'Yes', 'No', 'No', 'Two year', 'Yes', 'Mailed check', 61.05, '2018.4')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('4709-LKHYG', 29, 'Yes', 'No', 'No', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'One year', 'No', 'Electronic check', 20.0, '540.05')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('3758-CKOQL', 59, 'Yes', 'Yes', 'Fiber optic', 'Yes', 'Yes', 'Yes', 'Yes', 'No', 'Yes', 'One year', 'Yes', 'Credit card (automatic)', 107.0, '6152.3')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('5201-FRKKS', 25, 'Yes', 'No', 'Fiber optic', 'Yes', 'No', 'No', 'No', 'No', 'No', 'Month-to-month', 'No', 'Bank transfer (automatic)', 74.3, '1952.25')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('5044-LRQAQ', 7, 'Yes', 'No', 'Fiber optic', 'No', 'No', 'No', 'No', 'No', 'No', 'Month-to-month', 'Yes', 'Bank transfer (automatic)', 69.2, '477.55')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('6557-BZXLQ', 16, 'Yes', 'No', 'Fiber optic', 'No', 'No', 'No', 'No', 'No', 'No', 'Month-to-month', 'No', 'Electronic check', 69.65, '1043.3')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('8608-OZTLB', 38, 'Yes', 'No', 'DSL', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'No', 'One year', 'No', 'Electronic check', 74.05, '2802.3')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('1436-ZMJAN', 10, 'Yes', 'No', 'DSL', 'No', 'No', 'Yes', 'No', 'Yes', 'Yes', 'Month-to-month', 'Yes', 'Credit card (automatic)', 67.8, '653.15')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('6345-FZOQH', 69, 'Yes', 'No', 'No', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'Two year', 'No', 'Mailed check', 19.9, '1363.45')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('6008-NAIXK', 54, 'No', 'No phone service', 'DSL', 'No', 'Yes', 'Yes', 'No', 'Yes', 'Yes', 'One year', 'Yes', 'Electronic check', 55.45, '2966.95')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('9677-AVKED', 53, 'Yes', 'Yes', 'DSL', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'One year', 'Yes', 'Electronic check', 84.6, '4449.75')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('5515-IDEJJ', 1, 'Yes', 'No', 'No', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'Month-to-month', 'No', 'Mailed check', 19.9, '19.9')

INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('7820-ZYGNY', 63, 'Yes', 'Yes', 'Fiber optic', 'No', 'Yes', 'No', 'No', 'No', 'Yes', 'One year', 'No', 'Credit card (automatic)', 90.45, '5825.5')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('5170-PTRKA', 49, 'No', 'No phone service', 'DSL', 'Yes', 'No', 'No', 'Yes', 'No', 'No', 'One year', 'Yes', 'Credit card (automatic)', 35.8, '1782')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('0899-LIIBW', 34, 'Yes', 'Yes', 'Fiber optic', 'No', 'No', 'Yes', 'No', 'Yes', 'Yes', 'Month-to-month', 'No', 'Electronic check', 100.85, '3527.3')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('3961-SXAXY', 1, 'Yes', 'No', 'DSL', 'No', 'No', 'No', 'No', 'No', 'No', 'Month-to-month', 'Yes', 'Bank transfer (automatic)', 44.05, '44.05')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('5727-MYATE', 72, 'Yes', 'Yes', 'DSL', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Two year', 'Yes', 'Credit card (automatic)', 90.8, '6397.6')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('9763-GRSKD', 13, 'Yes', 'No', 'DSL', 'Yes', 'No', 'No', 'No', 'No', 'No', 'Month-to-month', 'Yes', 'Mailed check', 49.95, '587.45')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('1625-JAIIY', 68, 'Yes', 'Yes', 'Fiber optic', 'No', 'No', 'No', 'No', 'Yes', 'No', 'One year', 'Yes', 'Electronic check', 83.0, '5685.8')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('4763-PGDPO', 4, 'Yes', 'No', 'Fiber optic', 'No', 'No', 'No', 'No', 'No', 'No', 'Month-to-month', 'No', 'Electronic check', 70.4, '281')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('7382-DFJTU', 18, 'Yes', 'No', 'DSL', 'No', 'No', 'Yes', 'Yes', 'No', 'No', 'Month-to-month', 'No', 'Credit card (automatic)', 55.2, '1058.1')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('5883-GTGVD', 19, 'Yes', 'Yes', 'Fiber optic', 'No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'Month-to-month', 'Yes', 'Electronic check', 99.95, '1931.75')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('7957-RYHQD', 40, 'Yes', 'No', 'Fiber optic', 'Yes', 'Yes', 'No', 'No', 'No', 'No', 'Month-to-month', 'Yes', 'Credit card (automatic)', 79.2, '3233.85')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('3423-HHXAO', 14, 'Yes', 'No', 'No', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'One year', 'Yes', 'Mailed check', 19.5, '272')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('0842-IWYCP', 46, 'Yes', 'No', 'DSL', 'No', 'No', 'No', 'No', 'No', 'No', 'Month-to-month', 'No', 'Bank transfer (automatic)', 44.95, '2168.9')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('2202-CUYXZ', 1, 'Yes', 'No', 'Fiber optic', 'No', 'No', 'Yes', 'No', 'Yes', 'No', 'Month-to-month', 'Yes', 'Electronic check', 84.85, '84.85')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('5568-DMXZS', 8, 'Yes', 'No', 'DSL', 'No', 'Yes', 'No', 'Yes', 'Yes', 'No', 'Month-to-month', 'Yes', 'Electronic check', 65.45, '554.45')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('4500-HKANN', 23, 'Yes', 'Yes', 'DSL', 'No', 'Yes', 'No', 'Yes', 'No', 'No', 'Two year', 'No', 'Mailed check', 59.7, '1414.2')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('4849-PYRLQ', 56, 'Yes', 'Yes', 'DSL', 'Yes', 'No', 'Yes', 'Yes', 'No', 'Yes', 'Two year', 'No', 'Bank transfer (automatic)', 73.25, '4054.2')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('0225-ZORZP', 3, 'Yes', 'No', 'Fiber optic', 'No', 'Yes', 'No', 'No', 'No', 'Yes', 'Month-to-month', 'No', 'Electronic check', 84.3, '235.05')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('9018-PCIOK', 55, 'Yes', 'No', 'DSL', 'No', 'Yes', 'Yes', 'No', 'No', 'Yes', 'Two year', 'Yes', 'Mailed check', 64.75, '3617.1')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('1456-TWCGB', 4, 'Yes', 'No', 'DSL', 'No', 'Yes', 'No', 'No', 'No', 'No', 'Month-to-month', 'No', 'Mailed check', 49.25, '208.45')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('7781-HVGMK', 72, 'No', 'No phone service', 'DSL', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Two year', 'Yes', 'Credit card (automatic)', 65.2, '4784.45')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('3525-DVKFN', 17, 'Yes', 'No', 'No', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'Two year', 'No', 'Mailed check', 19.4, '358.05')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('5716-EZXZN', 65, 'Yes', 'Yes', 'Fiber optic', 'Yes', 'Yes', 'No', 'Yes', 'Yes', 'No', 'Two year', 'Yes', 'Credit card (automatic)', 99.05, '6416.7')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('8305-VHZBZ', 1, 'Yes', 'No', 'No', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'Month-to-month', 'Yes', 'Mailed check', 20.2, '20.2')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('5343-SGUBI', 52, 'Yes', 'Yes', 'Fiber optic', 'No', 'Yes', 'No', 'No', 'No', 'No', 'One year', 'Yes', 'Mailed check', 80.2, '4297.6')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('6479-OAUSD', 25, 'Yes', 'No', 'No', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'One year', 'No', 'Credit card (automatic)', 19.9, '510.8')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('5443-SCMKX', 58, 'Yes', 'Yes', 'Fiber optic', 'No', 'Yes', 'Yes', 'No', 'No', 'Yes', 'One year', 'Yes', 'Electronic check', 94.3, '5610.15')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('4872-JCVCA', 71, 'No', 'No phone service', 'DSL', 'Yes', 'Yes', 'Yes', 'Yes', 'No', 'No', 'Two year', 'Yes', 'Bank transfer (automatic)', 47.6, '3377.8')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('8617-ENBDS', 3, 'Yes', 'No', 'Fiber optic', 'No', 'No', 'Yes', 'No', 'No', 'No', 'Month-to-month', 'Yes', 'Credit card (automatic)', 73.6, '232.5')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('0820-FNRNX', 17, 'Yes', 'Yes', 'DSL', 'No', 'Yes', 'Yes', 'Yes', 'No', 'No', 'Month-to-month', 'Yes', 'Mailed check', 66.7, '1077.05')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('7465-ZZRVX', 1, 'Yes', 'No', 'Fiber optic', 'No', 'No', 'No', 'No', 'No', 'No', 'Month-to-month', 'Yes', 'Electronic check', 70.35, '70.35')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('5453-AXEPF', 17, 'Yes', 'Yes', 'Fiber optic', 'No', 'Yes', 'No', 'No', 'No', 'No', 'Month-to-month', 'Yes', 'Bank transfer (automatic)', 80.5, '1336.9')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('9705-ZJBCG', 13, 'Yes', 'No', 'DSL', 'Yes', 'No', 'No', 'Yes', 'No', 'No', 'One year', 'No', 'Bank transfer (automatic)', 54.15, '701.05')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('2506-TNFCO', 1, 'Yes', 'No', 'Fiber optic', 'No', 'No', 'No', 'No', 'No', 'No', 'Month-to-month', 'Yes', 'Electronic check', 69.55, '69.55')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('8680-CGLTP', 29, 'Yes', 'No', 'DSL', 'Yes', 'Yes', 'No', 'Yes', 'No', 'No', 'One year', 'Yes', 'Electronic check', 58.75, '1696.2')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('5236-PERKL', 57, 'Yes', 'Yes', 'Fiber optic', 'Yes', 'Yes', 'Yes', 'No', 'Yes', 'Yes', 'Two year', 'Yes', 'Bank transfer (automatic)', 112.95, '6465')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('6625-UTXEW', 12, 'Yes', 'No', 'DSL', 'No', 'Yes', 'No', 'No', 'No', 'No', 'Month-to-month', 'Yes', 'Electronic check', 51.25, '612.1')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('7156-MHUGY', 13, 'Yes', 'No', 'Fiber optic', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'Month-to-month', 'Yes', 'Electronic check', 90.5, '1201.15')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('3785-KTYSH', 53, 'Yes', 'Yes', 'No', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'Two year', 'No', 'Mailed check', 24.6, '1279')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('7633-MVPUY', 57, 'Yes', 'No', 'DSL', 'Yes', 'Yes', 'No', 'Yes', 'No', 'No', 'Two year', 'Yes', 'Electronic check', 59.75, '3450.15')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('7067-KSAZT', 65, 'Yes', 'Yes', 'Fiber optic', 'No', 'Yes', 'Yes', 'No', 'Yes', 'Yes', 'One year', 'Yes', 'Electronic check', 106.25, '6979.8')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('5482-NUPNA', 4, 'Yes', 'No', 'DSL', 'Yes', 'Yes', 'No', 'Yes', 'No', 'No', 'Month-to-month', 'Yes', 'Mailed check', 60.4, '272.15')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('4522-AKYLR', 13, 'Yes', 'No', 'DSL', 'No', 'Yes', 'Yes', 'No', 'No', 'No', 'Month-to-month', 'Yes', 'Electronic check', 54.8, '731.3')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('2005-DWQZJ', 8, 'Yes', 'No', 'No', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'Two year', 'No', 'Mailed check', 19.05, '201.7')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('6377-WHAOX', 60, 'Yes', 'Yes', 'Fiber optic', 'No', 'Yes', 'Yes', 'No', 'Yes', 'Yes', 'Month-to-month', 'Yes', 'Electronic check', 106.15, '6411.25')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('3753-TSEMP', 15, 'Yes', 'No', 'Fiber optic', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'Month-to-month', 'No', 'Electronic check', 88.15, '1390.6')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('0488-GSLFR', 1, 'Yes', 'No', 'Fiber optic', 'No', 'No', 'No', 'No', 'No', 'No', 'Month-to-month', 'Yes', 'Electronic check', 69.5, '69.5')

INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('2362-IBOOY', 36, 'Yes', 'Yes', 'Fiber optic', 'No', 'No', 'No', 'No', 'No', 'Yes', 'Month-to-month', 'Yes', 'Electronic check', 84.75, '3050.15')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('0733-VUNUW', 24, 'Yes', 'Yes', 'DSL', 'Yes', 'No', 'No', 'No', 'No', 'No', 'Month-to-month', 'Yes', 'Bank transfer (automatic)', 55.65, '1400.55')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('4923-ADWXJ', 25, 'Yes', 'No', 'DSL', 'No', 'Yes', 'No', 'Yes', 'No', 'Yes', 'Month-to-month', 'Yes', 'Bank transfer (automatic)', 65.8, '1679.65')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('1403-LKLIK', 33, 'Yes', 'No', 'No', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'One year', 'No', 'Mailed check', 20.1, '579.4')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('9885-CSMWE', 1, 'Yes', 'No', 'Fiber optic', 'No', 'No', 'No', 'No', 'Yes', 'No', 'Month-to-month', 'No', 'Electronic check', 78.45, '78.45')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('5804-LEPIM', 2, 'Yes', 'No', 'Fiber optic', 'No', 'No', 'No', 'No', 'No', 'No', 'Month-to-month', 'Yes', 'Electronic check', 70.35, '139.05')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('7641-TQFHN', 39, 'Yes', 'Yes', 'Fiber optic', 'No', 'No', 'No', 'Yes', 'Yes', 'Yes', 'Two year', 'No', 'Mailed check', 100.55, '3895.35')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('4701-AHWMW', 55, 'No', 'No phone service', 'DSL', 'No', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'Month-to-month', 'Yes', 'Bank transfer (automatic)', 54.55, '2978.3')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('2824-DXNKN', 72, 'Yes', 'Yes', 'DSL', 'Yes', 'No', 'Yes', 'No', 'Yes', 'No', 'Two year', 'Yes', 'Bank transfer (automatic)', 71.45, '5025.85')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('3487-EARAT', 70, 'Yes', 'No', 'DSL', 'Yes', 'Yes', 'Yes', 'Yes', 'No', 'Yes', 'One year', 'No', 'Credit card (automatic)', 74.1, '5222.3')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('2141-RRYGO', 4, 'Yes', 'No', 'DSL', 'No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'Month-to-month', 'Yes', 'Bank transfer (automatic)', 68.65, '261.25')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('3834-XUIFC', 7, 'Yes', 'Yes', 'Fiber optic', 'No', 'No', 'No', 'No', 'No', 'Yes', 'Month-to-month', 'Yes', 'Mailed check', 85.2, '602.55')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('7647-GYYKX', 54, 'Yes', 'No', 'No', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'Two year', 'Yes', 'Bank transfer (automatic)', 20.35, '1092.35')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('4077-CROMM', 31, 'Yes', 'Yes', 'Fiber optic', 'No', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'Month-to-month', 'Yes', 'Electronic check', 104.2, '3243.45')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('4667-QONEA', 60, 'Yes', 'No', 'DSL', 'Yes', 'Yes', 'Yes', 'Yes', 'No', 'Yes', 'One year', 'Yes', 'Credit card (automatic)', 74.85, '4456.35')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('0374-AACSZ', 1, 'Yes', 'No', 'DSL', 'Yes', 'No', 'No', 'No', 'No', 'No', 'Month-to-month', 'No', 'Electronic check', 50.15, '50.15')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('5397-TUPSH', 65, 'Yes', 'No', 'Fiber optic', 'No', 'No', 'No', 'No', 'No', 'No', 'One year', 'Yes', 'Bank transfer (automatic)', 70.95, '4555.2')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('5777-ZPQNC', 12, 'Yes', 'No', 'No', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'One year', 'No', 'Electronic check', 20.15, '260.7')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('9242-TKFSV', 72, 'No', 'No phone service', 'DSL', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Two year', 'Yes', 'Credit card (automatic)', 65.1, '4754.3')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('2320-YKQBO', 7, 'Yes', 'No', 'No', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'Month-to-month', 'No', 'Mailed check', 19.3, '144.95')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('1394-SUIUH', 44, 'Yes', 'No', 'Fiber optic', 'Yes', 'Yes', 'No', 'Yes', 'No', 'No', 'Month-to-month', 'Yes', 'Electronic check', 85.15, '3670.5')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('0187-QSXOE', 7, 'Yes', 'No', 'Fiber optic', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'Month-to-month', 'Yes', 'Electronic check', 89.0, '605.45')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('9817-APLHW', 12, 'Yes', 'Yes', 'No', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'Month-to-month', 'No', 'Electronic check', 25.0, '316.2')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('0440-EKDCF', 62, 'Yes', 'No', 'DSL', 'No', 'Yes', 'Yes', 'Yes', 'No', 'No', 'Two year', 'Yes', 'Credit card (automatic)', 60.15, '3753.2')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('6231-WFGFH', 4, 'Yes', 'No', 'No', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'Month-to-month', 'Yes', 'Mailed check', 20.5, '77.6')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('2041-JIJCI', 5, 'Yes', 'Yes', 'DSL', 'No', 'Yes', 'No', 'No', 'No', 'Yes', 'Month-to-month', 'Yes', 'Electronic check', 64.0, '370.25')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('5159-YFPKQ', 2, 'Yes', 'No', 'Fiber optic', 'No', 'No', 'Yes', 'No', 'No', 'No', 'Month-to-month', 'Yes', 'Electronic check', 75.8, '160.75')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('2446-PLQVO', 1, 'Yes', 'No', 'Fiber optic', 'No', 'No', 'No', 'No', 'No', 'No', 'Month-to-month', 'Yes', 'Electronic check', 70.3, '70.3')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('7136-IHZJA', 40, 'Yes', 'No', 'DSL', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes', 'Month-to-month', 'Yes', 'Mailed check', 71.35, '2847.2')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('2049-BAFNW', 1, 'No', 'No phone service', 'DSL', 'No', 'No', 'Yes', 'Yes', 'No', 'No', 'Month-to-month', 'No', 'Mailed check', 35.9, '35.9')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('7319-ZNRTR', 25, 'Yes', 'No', 'No', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'One year', 'No', 'Electronic check', 19.6, '411.15')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('2676-OXPPQ', 6, 'Yes', 'No', 'DSL', 'Yes', 'Yes', 'No', 'No', 'No', 'No', 'Month-to-month', 'Yes', 'Bank transfer (automatic)', 55.7, '335.65')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('8728-SKJLR', 41, 'Yes', 'No', 'Fiber optic', 'No', 'No', 'No', 'Yes', 'No', 'No', 'Month-to-month', 'Yes', 'Electronic check', 74.25, '3089.1')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('8344-WFMFH', 9, 'Yes', 'No', 'DSL', 'No', 'Yes', 'No', 'No', 'No', 'No', 'Month-to-month', 'Yes', 'Electronic check', 50.1, '484.05')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('4988-IQIGL', 1, 'Yes', 'Yes', 'Fiber optic', 'No', 'No', 'No', 'No', 'No', 'No', 'Month-to-month', 'Yes', 'Electronic check', 75.35, '75.35')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('6202-DYYFX', 22, 'Yes', 'Yes', 'Fiber optic', 'No', 'No', 'No', 'No', 'No', 'No', 'One year', 'Yes', 'Credit card (automatic)', 76.0, '1783.6')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('1024-KPRBB', 38, 'Yes', 'No', 'Fiber optic', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'One year', 'Yes', 'Mailed check', 89.1, '3342')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('3934-HXCFZ', 23, 'Yes', 'Yes', 'Fiber optic', 'Yes', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Month-to-month', 'Yes', 'Electronic check', 99.25, '2186.4')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('2661-GKBTK', 60, 'Yes', 'No', 'DSL', 'No', 'Yes', 'No', 'Yes', 'Yes', 'Yes', 'Two year', 'No', 'Bank transfer (automatic)', 76.95, '4543.95')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('5499-ECUTN', 47, 'Yes', 'No', 'DSL', 'Yes', 'No', 'Yes', 'No', 'Yes', 'No', 'One year', 'Yes', 'Credit card (automatic)', 66.05, '3021.45')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('0244-LGNFY', 72, 'Yes', 'Yes', 'DSL', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Two year', 'No', 'Bank transfer (automatic)', 92.65, '6733')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('5804-HYIEZ', 70, 'Yes', 'Yes', 'Fiber optic', 'Yes', 'Yes', 'No', 'No', 'Yes', 'Yes', 'Month-to-month', 'Yes', 'Electronic check', 106.05, '7554.05')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('9617-INGJY', 1, 'Yes', 'No', 'Fiber optic', 'No', 'No', 'No', 'No', 'No', 'No', 'Month-to-month', 'Yes', 'Mailed check', 70.6, '70.6')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('4952-YSOGZ', 4, 'Yes', 'Yes', 'Fiber optic', 'No', 'No', 'No', 'No', 'No', 'Yes', 'Month-to-month', 'Yes', 'Electronic check', 85.95, '381.3')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('8584-KMVXD', 8, 'Yes', 'No', 'Fiber optic', 'No', 'Yes', 'No', 'No', 'No', 'No', 'Month-to-month', 'No', 'Electronic check', 75.6, '535.55')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('3726-TBHQT', 71, 'Yes', 'Yes', 'Fiber optic', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Two year', 'Yes', 'Bank transfer (automatic)', 114.0, '8175.9')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('4529-CKBCL', 2, 'Yes', 'No', 'Fiber optic', 'No', 'No', 'No', 'No', 'Yes', 'No', 'Month-to-month', 'Yes', 'Electronic check', 80.2, '146.05')

INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('0420-TXVSG', 66, 'Yes', 'Yes', 'DSL', 'Yes', 'Yes', 'Yes', 'No', 'No', 'No', 'Two year', 'Yes', 'Credit card (automatic)', 66.1, '4428.45')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('6633-MPWBS', 5, 'Yes', 'No', 'DSL', 'No', 'No', 'No', 'Yes', 'No', 'No', 'Month-to-month', 'Yes', 'Electronic check', 49.2, '216.9')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('8650-RHRKE', 4, 'No', 'No phone service', 'DSL', 'No', 'No', 'Yes', 'No', 'No', 'No', 'Month-to-month', 'Yes', 'Electronic check', 29.65, '118.5')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('4530-NDRKU', 42, 'Yes', 'No', 'No', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'One year', 'Yes', 'Electronic check', 19.05, '761.85')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('9955-QOPOY', 69, 'No', 'No phone service', 'DSL', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'One year', 'Yes', 'Credit card (automatic)', 60.8, '4263.4')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('3680-CTHUH', 60, 'Yes', 'Yes', 'Fiber optic', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'One year', 'Yes', 'Credit card (automatic)', 116.6, '7049.5')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('5961-VUSRV', 12, 'Yes', 'No', 'No', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'One year', 'Yes', 'Bank transfer (automatic)', 19.35, '219.35')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('1589-AGTLK', 3, 'Yes', 'No', 'DSL', 'No', 'No', 'No', 'No', 'No', 'No', 'Month-to-month', 'Yes', 'Electronic check', 45.35, '141.5')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('7055-VKGDA', 54, 'Yes', 'No', 'Fiber optic', 'Yes', 'Yes', 'No', 'Yes', 'Yes', 'Yes', 'One year', 'Yes', 'Credit card (automatic)', 105.4, '5643.4')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('1641-BYBTK', 6, 'Yes', 'No', 'No', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'Month-to-month', 'Yes', 'Mailed check', 20.2, '98.35')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('5919-VCZYM', 2, 'Yes', 'No', 'No', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'Month-to-month', 'No', 'Mailed check', 20.05, '42.7')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('0716-BQNDX', 57, 'Yes', 'Yes', 'Fiber optic', 'Yes', 'No', 'No', 'Yes', 'No', 'Yes', 'Two year', 'No', 'Electronic check', 93.75, '5625.55')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('8838-GPHZP', 63, 'Yes', 'No', 'No', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'Two year', 'Yes', 'Mailed check', 20.6, '1298.7')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('5274-XHAKY', 41, 'Yes', 'Yes', 'Fiber optic', 'Yes', 'Yes', 'No', 'No', 'Yes', 'No', 'Month-to-month', 'Yes', 'Bank transfer (automatic)', 94.3, '3893.6')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('8929-KSWIH', 25, 'Yes', 'No', 'Fiber optic', 'No', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'Two year', 'No', 'Bank transfer (automatic)', 99.3, '2513.5')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('6916-HIJSE', 65, 'Yes', 'No', 'DSL', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Two year', 'Yes', 'Bank transfer (automatic)', 84.85, '5459.2')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('2228-BZDEE', 54, 'Yes', 'No', 'No', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'Two year', 'No', 'Mailed check', 20.1, '1079.45')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('1346-PJWTK', 61, 'Yes', 'No', 'Fiber optic', 'No', 'Yes', 'Yes', 'Yes', 'No', 'Yes', 'Month-to-month', 'No', 'Credit card (automatic)', 94.15, '5731.85')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('1561-BWHIN', 19, 'Yes', 'No', 'No', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'One year', 'No', 'Mailed check', 19.8, '344.5')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('2882-DDZPG', 12, 'Yes', 'No', 'No', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'Month-to-month', 'No', 'Bank transfer (automatic)', 19.45, '227.45')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('9648-BCHKM', 18, 'Yes', 'Yes', 'No', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'Two year', 'Yes', 'Credit card (automatic)', 24.65, '471.35')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('1930-QPBVZ', 68, 'Yes', 'No', 'Fiber optic', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes', 'Two year', 'No', 'Bank transfer (automatic)', 95.1, '6683.4')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('5299-RULOA', 10, 'Yes', 'Yes', 'Fiber optic', 'Yes', 'No', 'No', 'No', 'Yes', 'Yes', 'Month-to-month', 'Yes', 'Electronic check', 100.25, '1064.65')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('1626-ERCMM', 20, 'Yes', 'Yes', 'Fiber optic', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'Month-to-month', 'Yes', 'Electronic check', 94.55, '1899.65')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('8019-ENHXU', 42, 'Yes', 'Yes', 'Fiber optic', 'No', 'Yes', 'Yes', 'Yes', 'No', 'Yes', 'Month-to-month', 'Yes', 'Electronic check', 99.45, '4138.05')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('7795-CFOCW', 45, 'No', 'No phone service', 'DSL', 'Yes', 'No', 'Yes', 'Yes', 'No', 'No', 'One year', 'No', 'Bank transfer (automatic)', 42.3, '1840.75')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('0906-QVPMS', 72, 'Yes', 'Yes', 'Fiber optic', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Two year', 'No', 'Bank transfer (automatic)', 115.15, '8349.45')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('4118-CEVPF', 35, 'Yes', 'Yes', 'Fiber optic', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'One year', 'Yes', 'Bank transfer (automatic)', 110.8, '3836.3')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('5968-XQIVE', 72, 'Yes', 'Yes', 'Fiber optic', 'No', 'Yes', 'No', 'No', 'Yes', 'No', 'One year', 'Yes', 'Electronic check', 89.7, '6588.95')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('9305-CDSKC', 8, 'Yes', 'Yes', 'Fiber optic', 'No', 'No', 'Yes', 'No', 'Yes', 'Yes', 'Month-to-month', 'Yes', 'Electronic check', 99.65, '820.5')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('3521-SYVOR', 37, 'Yes', 'No', 'DSL', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'Month-to-month', 'Yes', 'Electronic check', 64.75, '2345.2')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('5149-TGWDZ', 21, 'Yes', 'No', 'Fiber optic', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'One year', 'Yes', 'Mailed check', 104.55, '2239.4')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('1265-BCFEO', 71, 'Yes', 'Yes', 'DSL', 'No', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'Two year', 'Yes', 'Bank transfer (automatic)', 80.45, '5662.25')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('6873-UDNLD', 40, 'Yes', 'No', 'DSL', 'Yes', 'No', 'Yes', 'No', 'No', 'Yes', 'Month-to-month', 'No', 'Electronic check', 67.45, '2731')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('7143-BQIBA', 10, 'Yes', 'No', 'DSL', 'Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'Month-to-month', 'No', 'Bank transfer (automatic)', 62.25, '612.95')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('4526-ZJJTM', 25, 'Yes', 'No', 'Fiber optic', 'No', 'Yes', 'Yes', 'No', 'No', 'Yes', 'Month-to-month', 'No', 'Bank transfer (automatic)', 88.4, '2191.15')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('7576-ASEJU', 41, 'Yes', 'No', 'DSL', 'Yes', 'No', 'No', 'Yes', 'Yes', 'Yes', 'One year', 'Yes', 'Credit card (automatic)', 74.7, '3187.65')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('9190-MFJLN', 19, 'Yes', 'No', 'Fiber optic', 'No', 'No', 'Yes', 'No', 'Yes', 'Yes', 'Month-to-month', 'Yes', 'Credit card (automatic)', 95.9, '1777.9')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('6242-MBHPK', 23, 'Yes', 'No', 'Fiber optic', 'Yes', 'No', 'No', 'No', 'Yes', 'Yes', 'Month-to-month', 'Yes', 'Electronic check', 95.1, '2326.05')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('1400-WIVLL', 57, 'Yes', 'Yes', 'Fiber optic', 'No', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'Two year', 'No', 'Electronic check', 107.95, '5969.85')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('3489-HHPFY', 2, 'Yes', 'Yes', 'Fiber optic', 'No', 'No', 'No', 'No', 'Yes', 'No', 'Month-to-month', 'Yes', 'Electronic check', 84.05, '134.05')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('7560-QJAVJ', 70, 'Yes', 'No', 'DSL', 'Yes', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'Two year', 'No', 'Bank transfer (automatic)', 79.6, '5589.45')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('3722-WPXTK', 1, 'Yes', 'No', 'Fiber optic', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'Month-to-month', 'Yes', 'Electronic check', 88.35, '88.35')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('0748-RDGGM', 70, 'Yes', 'No', 'Fiber optic', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'One year', 'Yes', 'Bank transfer (automatic)', 109.5, '7534.65')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('6719-FGEDO', 72, 'Yes', 'Yes', 'Fiber optic', 'Yes', 'Yes', 'Yes', 'Yes', 'No', 'No', 'Two year', 'Yes', 'Bank transfer (automatic)', 97.0, '7104.2')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('5130-IEKQT', 25, 'Yes', 'Yes', 'Fiber optic', 'No', 'Yes', 'Yes', 'No', 'Yes', 'Yes', 'Month-to-month', 'No', 'Mailed check', 105.95, '2655.25')

INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('2782-JEEBU', 21, 'No', 'No phone service', 'DSL', 'No', 'Yes', 'No', 'Yes', 'No', 'No', 'Month-to-month', 'Yes', 'Mailed check', 36.0, '780.15')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('5649-RXQTV', 51, 'Yes', 'No', 'Fiber optic', 'No', 'Yes', 'Yes', 'No', 'Yes', 'Yes', 'Month-to-month', 'Yes', 'Electronic check', 99.0, '5038.15')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('4824-GUCBY', 22, 'Yes', 'No', 'Fiber optic', 'Yes', 'Yes', 'No', 'No', 'No', 'No', 'Month-to-month', 'No', 'Electronic check', 81.7, '1820.9')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('6394-HHHZM', 3, 'Yes', 'No', 'No', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'Month-to-month', 'No', 'Mailed check', 20.7, '57.5')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('9405-GPBBG', 64, 'Yes', 'Yes', 'Fiber optic', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Two year', 'Yes', 'Credit card (automatic)', 110.5, '7069.25')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('3896-RCYYE', 67, 'No', 'No phone service', 'DSL', 'No', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'Month-to-month', 'Yes', 'Credit card (automatic)', 53.4, '3579.15')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('8774-GSBUN', 72, 'Yes', 'Yes', 'No', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'Two year', 'No', 'Mailed check', 25.4, '1797.1')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('5338-YHWYT', 37, 'Yes', 'No', 'DSL', 'Yes', 'Yes', 'No', 'Yes', 'No', 'No', 'Two year', 'No', 'Credit card (automatic)', 61.45, '2302.35')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('4750-UKWJK', 37, 'Yes', 'No', 'No', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'One year', 'No', 'Mailed check', 19.6, '727.8')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('1866-RZZQS', 41, 'Yes', 'Yes', 'Fiber optic', 'No', 'No', 'Yes', 'No', 'Yes', 'Yes', 'Month-to-month', 'Yes', 'Electronic check', 98.4, '4187.75')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('2360-RDGRO', 65, 'Yes', 'Yes', 'Fiber optic', 'Yes', 'No', 'Yes', 'No', 'Yes', 'Yes', 'Month-to-month', 'Yes', 'Electronic check', 104.25, '6812.95')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('3079-BCHLN', 47, 'Yes', 'No', 'No', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'One year', 'No', 'Bank transfer (automatic)', 19.9, '942.95')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('3943-KDREE', 26, 'Yes', 'Yes', 'Fiber optic', 'No', 'No', 'No', 'No', 'No', 'No', 'Month-to-month', 'Yes', 'Bank transfer (automatic)', 74.95, '1834.95')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('2691-NZETQ', 9, 'Yes', 'Yes', 'Fiber optic', 'No', 'No', 'No', 'No', 'Yes', 'No', 'Month-to-month', 'Yes', 'Electronic check', 85.35, '758.6')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('5394-MEITZ', 60, 'Yes', 'No', 'DSL', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Two year', 'Yes', 'Bank transfer (automatic)', 80.6, '4946.7')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('4826-XTSOH', 1, 'Yes', 'Yes', 'Fiber optic', 'No', 'No', 'No', 'No', 'Yes', 'No', 'Month-to-month', 'Yes', 'Electronic check', 86.05, '86.05')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('3249-VHRIP', 62, 'No', 'No phone service', 'DSL', 'No', 'Yes', 'Yes', 'No', 'No', 'Yes', 'Two year', 'Yes', 'Credit card (automatic)', 43.6, '2748.7')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('2079-FBMZK', 6, 'Yes', 'No', 'Fiber optic', 'No', 'No', 'No', 'No', 'No', 'No', 'Month-to-month', 'Yes', 'Mailed check', 69.25, '418.4')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('9770-KXGQU', 53, 'Yes', 'Yes', 'Fiber optic', 'Yes', 'Yes', 'Yes', 'No', 'Yes', 'No', 'One year', 'No', 'Mailed check', 98.6, '5311.85')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('3522-CDKHF', 32, 'Yes', 'No', 'Fiber optic', 'Yes', 'No', 'No', 'No', 'No', 'No', 'Month-to-month', 'Yes', 'Bank transfer (automatic)', 75.5, '2324.7')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('8199-ZLLSA', 67, 'Yes', 'Yes', 'Fiber optic', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'One year', 'Yes', 'Bank transfer (automatic)', 118.35, '7804.15')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('7083-YNSKY', 15, 'Yes', 'Yes', 'No', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'Month-to-month', 'Yes', 'Credit card (automatic)', 25.4, '399.6')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('5533-RJFTJ', 49, 'No', 'No phone service', 'DSL', 'No', 'No', 'Yes', 'No', 'No', 'No', 'Month-to-month', 'Yes', 'Bank transfer (automatic)', 30.2, '1453.1')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('6214-EDAKZ', 22, 'Yes', 'No', 'DSL', 'No', 'Yes', 'No', 'Yes', 'No', 'No', 'Month-to-month', 'No', 'Electronic check', 55.15, '1206.05')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('8984-EYLLL', 64, 'Yes', 'Yes', 'Fiber optic', 'No', 'Yes', 'No', 'Yes', 'Yes', 'Yes', 'Two year', 'Yes', 'Electronic check', 105.25, '6823.4')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('3744-ZRRDZ', 21, 'Yes', 'Yes', 'Fiber optic', 'No', 'Yes', 'No', 'No', 'No', 'No', 'Month-to-month', 'Yes', 'Electronic check', 82.35, '1852.85')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('2454-RPBRZ', 12, 'Yes', 'Yes', 'Fiber optic', 'No', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Month-to-month', 'Yes', 'Electronic check', 98.1, '1060.2')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('4760-THGOT', 43, 'Yes', 'Yes', 'Fiber optic', 'Yes', 'Yes', 'No', 'No', 'No', 'Yes', 'Month-to-month', 'Yes', 'Electronic check', 94.1, '4107.3')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('7073-QETQY', 66, 'Yes', 'No', 'No', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'One year', 'Yes', 'Electronic check', 20.35, '1359.5')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('5980-NOPLP', 44, 'Yes', 'Yes', 'Fiber optic', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'Month-to-month', 'Yes', 'Electronic check', 96.1, '4364.1')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('4933-IKULF', 17, 'Yes', 'No', 'No', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'One year', 'No', 'Mailed check', 20.65, '330.6')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('4749-VFKVB', 1, 'Yes', 'Yes', 'DSL', 'No', 'No', 'No', 'No', 'No', 'No', 'Month-to-month', 'Yes', 'Mailed check', 50.1, '50.1')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('8276-MQBYC', 51, 'Yes', 'Yes', 'Fiber optic', 'No', 'No', 'Yes', 'No', 'Yes', 'Yes', 'Month-to-month', 'Yes', 'Electronic check', 97.8, '4913.3')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('4083-EUGRJ', 9, 'Yes', 'No', 'No', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'Month-to-month', 'No', 'Mailed check', 20.25, '178.5')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('9518-RWHZL', 64, 'Yes', 'Yes', 'Fiber optic', 'No', 'No', 'Yes', 'No', 'Yes', 'Yes', 'One year', 'Yes', 'Credit card (automatic)', 100.05, '6254.2')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('9552-TGUZV', 8, 'Yes', 'No', 'Fiber optic', 'Yes', 'No', 'No', 'No', 'No', 'No', 'Month-to-month', 'Yes', 'Mailed check', 75.0, '658.1')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('8647-SDTWQ', 57, 'Yes', 'Yes', 'Fiber optic', 'No', 'No', 'No', 'No', 'No', 'No', 'Month-to-month', 'Yes', 'Electronic check', 74.3, '4018.35')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('4560-WQAQW', 59, 'Yes', 'Yes', 'DSL', 'Yes', 'No', 'No', 'Yes', 'No', 'Yes', 'One year', 'No', 'Bank transfer (automatic)', 68.7, '4070.95')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('4942-VZZOM', 64, 'Yes', 'Yes', 'DSL', 'Yes', 'No', 'No', 'No', 'Yes', 'No', 'One year', 'Yes', 'Credit card (automatic)', 66.15, '4392.5')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('9629-NHXFW', 1, 'Yes', 'No', 'No', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'Month-to-month', 'Yes', 'Mailed check', 19.4, '19.4')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('2226-ICFDO', 72, 'Yes', 'Yes', 'DSL', 'Yes', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'Two year', 'Yes', 'Credit card (automatic)', 85.9, '6110.75')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('2867-UIMSS', 1, 'Yes', 'No', 'Fiber optic', 'No', 'No', 'No', 'No', 'No', 'Yes', 'Month-to-month', 'No', 'Electronic check', 80.5, '80.5')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('6814-ZPWFQ', 51, 'Yes', 'Yes', 'No', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'One year', 'No', 'Bank transfer (automatic)', 25.0, '1260.7')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('4471-KXAUH', 42, 'Yes', 'Yes', 'Fiber optic', 'No', 'No', 'Yes', 'Yes', 'No', 'No', 'Month-to-month', 'Yes', 'Electronic check', 84.3, '3588.4')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('3090-QFUVD', 1, 'Yes', 'No', 'No', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'Month-to-month', 'No', 'Credit card (automatic)', 20.3, '20.3')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('6766-HFKLA', 56, 'Yes', 'Yes', 'Fiber optic', 'No', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'Two year', 'No', 'Bank transfer (automatic)', 103.2, '5744.35')

INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('3677-TNKIO', 14, 'Yes', 'No', 'Fiber optic', 'No', 'No', 'No', 'No', 'No', 'No', 'Month-to-month', 'Yes', 'Credit card (automatic)', 71.0, '914')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('2235-ZGKPT', 4, 'Yes', 'Yes', 'DSL', 'No', 'No', 'No', 'No', 'No', 'No', 'Month-to-month', 'No', 'Mailed check', 50.85, '239.55')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('0815-MFZGM', 42, 'Yes', 'No', 'Fiber optic', 'No', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'Two year', 'Yes', 'Credit card (automatic)', 99.0, '4135')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('5774-XZTQC', 7, 'Yes', 'No', 'No', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'Month-to-month', 'No', 'Mailed check', 20.45, '150.75')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('2916-BQZLN', 19, 'Yes', 'Yes', 'Fiber optic', 'Yes', 'No', 'Yes', 'No', 'No', 'No', 'Month-to-month', 'Yes', 'Electronic check', 84.75, '1651.95')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('0999-QXNSA', 7, 'Yes', 'No', 'DSL', 'No', 'No', 'No', 'No', 'No', 'No', 'Month-to-month', 'Yes', 'Mailed check', 45.75, '344.2')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('7919-ZODZZ', 10, 'Yes', 'No', 'DSL', 'No', 'Yes', 'Yes', 'No', 'No', 'Yes', 'One year', 'Yes', 'Mailed check', 65.9, '660.05')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('8903-WMRNW', 15, 'Yes', 'No', 'Fiber optic', 'Yes', 'No', 'Yes', 'No', 'Yes', 'Yes', 'Month-to-month', 'No', 'Electronic check', 101.75, '1669.4')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('2027-FECZV', 12, 'Yes', 'Yes', 'Fiber optic', 'No', 'Yes', 'Yes', 'No', 'Yes', 'Yes', 'Month-to-month', 'Yes', 'Electronic check', 106.7, '1253.9')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('1218-VKFPE', 12, 'Yes', 'No', 'No', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'Month-to-month', 'No', 'Mailed check', 19.0, '233.55')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('6979-TNDEU', 8, 'Yes', 'No', 'No', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'Month-to-month', 'No', 'Mailed check', 19.2, '156.85')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('4182-BGSIQ', 10, 'Yes', 'No', 'No', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'Month-to-month', 'Yes', 'Bank transfer (automatic)', 19.8, '196.75')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('0531-ZZJWQ', 55, 'Yes', 'Yes', 'Fiber optic', 'No', 'No', 'No', 'No', 'No', 'No', 'Month-to-month', 'Yes', 'Electronic check', 74.0, '4052.4')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('9110-HSGTV', 69, 'Yes', 'No', 'DSL', 'Yes', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'Two year', 'Yes', 'Credit card (automatic)', 82.45, '5555.3')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('4616-EWBNJ', 16, 'Yes', 'No', 'No', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'One year', 'No', 'Bank transfer (automatic)', 20.1, '318.6')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('7740-KKCXF', 51, 'No', 'No phone service', 'DSL', 'No', 'Yes', 'No', 'No', 'No', 'No', 'Month-to-month', 'Yes', 'Credit card (automatic)', 30.05, '1529.45')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('2400-XIWIO', 71, 'Yes', 'Yes', 'DSL', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Two year', 'No', 'Electronic check', 90.1, '6310.9')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('9378-FXTIZ', 54, 'Yes', 'Yes', 'DSL', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'One year', 'Yes', 'Credit card (automatic)', 70.15, '3715.65')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('3716-UVSPD', 1, 'Yes', 'No', 'DSL', 'No', 'No', 'No', 'Yes', 'No', 'No', 'Month-to-month', 'Yes', 'Electronic check', 49.3, '49.3')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('6261-LHRTG', 26, 'Yes', 'No', 'DSL', 'No', 'Yes', 'Yes', 'No', 'No', 'No', 'Month-to-month', 'Yes', 'Credit card (automatic)', 54.75, '1406.9')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('7845-URHJN', 8, 'Yes', 'No', 'No', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'Month-to-month', 'No', 'Bank transfer (automatic)', 20.15, '156.25')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('6838-HVLXG', 12, 'Yes', 'No', 'No', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'Month-to-month', 'No', 'Mailed check', 20.3, '246.7')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('5956-VKDTT', 5, 'Yes', 'Yes', 'Fiber optic', 'No', 'No', 'No', 'No', 'No', 'No', 'Month-to-month', 'Yes', 'Electronic check', 74.35, '334.8')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('6522-OIQSX', 69, 'No', 'No phone service', 'DSL', 'No', 'Yes', 'Yes', 'No', 'Yes', 'Yes', 'Two year', 'Yes', 'Credit card (automatic)', 54.95, '3772.5')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('1751-NCDLI', 46, 'Yes', 'Yes', 'Fiber optic', 'No', 'No', 'Yes', 'No', 'Yes', 'Yes', 'Month-to-month', 'Yes', 'Electronic check', 98.85, '4564.9')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('4829-AUOAX', 46, 'Yes', 'Yes', 'Fiber optic', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'Month-to-month', 'No', 'Bank transfer (automatic)', 96.05, '4399.5')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('7426-RHZGU', 9, 'Yes', 'No', 'Fiber optic', 'No', 'No', 'No', 'Yes', 'Yes', 'Yes', 'Month-to-month', 'Yes', 'Bank transfer (automatic)', 95.9, '827.45')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('7409-JURKQ', 53, 'Yes', 'Yes', 'Fiber optic', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'One year', 'Yes', 'Bank transfer (automatic)', 111.8, '5809.75')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('8807-ARQET', 41, 'No', 'No phone service', 'DSL', 'No', 'Yes', 'No', 'No', 'No', 'Yes', 'Month-to-month', 'Yes', 'Electronic check', 40.35, '1677.85')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('3097-FQTVJ', 41, 'Yes', 'No', 'No', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'Two year', 'No', 'Mailed check', 20.0, '810.3')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('8756-RDDLT', 68, 'No', 'No phone service', 'DSL', 'No', 'Yes', 'No', 'Yes', 'No', 'Yes', 'Month-to-month', 'No', 'Electronic check', 44.95, '3085.35')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('9560-BBZXK', 36, 'No', 'No phone service', 'DSL', 'Yes', 'No', 'No', 'No', 'No', 'No', 'Two year', 'No', 'Bank transfer (automatic)', 31.05, '1126.35')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('4381-MHQDC', 47, 'Yes', 'Yes', 'DSL', 'Yes', 'No', 'Yes', 'Yes', 'No', 'No', 'Two year', 'Yes', 'Mailed check', 65.0, '2879.9')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('5295-PCJOO', 4, 'Yes', 'No', 'DSL', 'Yes', 'No', 'No', 'No', 'No', 'No', 'Month-to-month', 'Yes', 'Electronic check', 49.4, '184.4')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('6013-BHCAW', 61, 'Yes', 'Yes', 'DSL', 'No', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'Two year', 'Yes', 'Bank transfer (automatic)', 81.0, '4976.15')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('3672-YITQD', 36, 'Yes', 'Yes', 'Fiber optic', 'No', 'No', 'No', 'No', 'No', 'Yes', 'Month-to-month', 'Yes', 'Electronic check', 84.1, '3021.6')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('9753-OYLBX', 1, 'Yes', 'No', 'No', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'Month-to-month', 'No', 'Mailed check', 20.5, '20.5')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('1965-AKTSX', 14, 'Yes', 'Yes', 'Fiber optic', 'No', 'Yes', 'No', 'No', 'No', 'No', 'Month-to-month', 'Yes', 'Electronic check', 78.95, '1101.85')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('9101-BWFSS', 50, 'Yes', 'Yes', 'Fiber optic', 'Yes', 'Yes', 'No', 'Yes', 'Yes', 'Yes', 'One year', 'No', 'Electronic check', 108.55, '5610.7')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('9445-ZUEQE', 27, 'Yes', 'Yes', 'Fiber optic', 'No', 'Yes', 'No', 'Yes', 'No', 'No', 'Month-to-month', 'Yes', 'Credit card (automatic)', 85.2, '2151.6')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('1682-VCOIO', 23, 'Yes', 'No', 'No', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'One year', 'No', 'Mailed check', 20.45, '481.1')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('8676-TRMJS', 3, 'Yes', 'Yes', 'Fiber optic', 'No', 'No', 'No', 'No', 'No', 'No', 'Month-to-month', 'No', 'Mailed check', 75.0, '209.1')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('4480-MBMLB', 36, 'Yes', 'Yes', 'Fiber optic', 'No', 'Yes', 'Yes', 'No', 'Yes', 'Yes', 'One year', 'Yes', 'Bank transfer (automatic)', 104.8, '3886.45')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('8155-IBNHG', 24, 'Yes', 'Yes', 'Fiber optic', 'No', 'No', 'No', 'No', 'No', 'No', 'Month-to-month', 'Yes', 'Credit card (automatic)', 75.4, '1747.85')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('7207-RMRDB', 65, 'Yes', 'Yes', 'Fiber optic', 'No', 'Yes', 'Yes', 'No', 'Yes', 'Yes', 'Month-to-month', 'Yes', 'Electronic check', 105.5, '6985.65')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('3606-SBKRY', 31, 'No', 'No phone service', 'DSL', 'No', 'No', 'Yes', 'No', 'Yes', 'Yes', 'One year', 'Yes', 'Electronic check', 50.05, '1523.4')

INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('6357-JJPQT', 3, 'Yes', 'No', 'Fiber optic', 'No', 'No', 'No', 'No', 'Yes', 'No', 'Month-to-month', 'Yes', 'Electronic check', 80.5, '232.35')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('2792-VPPET', 3, 'Yes', 'No', 'No', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'Month-to-month', 'Yes', 'Electronic check', 20.5, '76.95')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('6168-YBYNP', 59, 'Yes', 'Yes', 'Fiber optic', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Month-to-month', 'Yes', 'Electronic check', 111.35, '6519.75')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('8059-UDZFY', 33, 'Yes', 'Yes', 'Fiber optic', 'No', 'Yes', 'Yes', 'No', 'Yes', 'Yes', 'Month-to-month', 'Yes', 'Bank transfer (automatic)', 105.35, '3465.05')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('0869-PAPRP', 26, 'Yes', 'No', 'Fiber optic', 'No', 'No', 'Yes', 'No', 'Yes', 'No', 'Month-to-month', 'Yes', 'Credit card (automatic)', 85.7, '2067')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('1482-OXZSY', 30, 'Yes', 'Yes', 'Fiber optic', 'Yes', 'No', 'No', 'No', 'Yes', 'Yes', 'Month-to-month', 'Yes', 'Bank transfer (automatic)', 100.4, '2936.25')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('5175-WLYXL', 22, 'Yes', 'Yes', 'Fiber optic', 'No', 'Yes', 'No', 'No', 'No', 'No', 'Month-to-month', 'Yes', 'Mailed check', 78.85, '1600.25')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('9489-JMTTN', 72, 'Yes', 'Yes', 'DSL', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Two year', 'No', 'Credit card (automatic)', 89.75, '6595.9')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('9027-YFHQJ', 7, 'Yes', 'Yes', 'No', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'Month-to-month', 'Yes', 'Bank transfer (automatic)', 25.05, '152.95')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('4827-LTQRJ', 66, 'Yes', 'Yes', 'Fiber optic', 'Yes', 'Yes', 'No', 'Yes', 'Yes', 'Yes', 'One year', 'Yes', 'Credit card (automatic)', 110.6, '7210.85')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('3363-DTIVD', 71, 'Yes', 'Yes', 'Fiber optic', 'Yes', 'No', 'Yes', 'No', 'Yes', 'Yes', 'Two year', 'No', 'Electronic check', 105.55, '7405.5')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('3199-XGZCY', 8, 'Yes', 'Yes', 'Fiber optic', 'No', 'No', 'No', 'No', 'No', 'No', 'Month-to-month', 'Yes', 'Electronic check', 75.25, '576.7')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('4298-OYIFC', 15, 'Yes', 'Yes', 'Fiber optic', 'No', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'Month-to-month', 'Yes', 'Electronic check', 103.45, '1539.8')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('6994-FGRHH', 70, 'Yes', 'No', 'Fiber optic', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'One year', 'Yes', 'Electronic check', 106.15, '7475.1')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('2404-JIBFC', 55, 'Yes', 'Yes', 'DSL', 'Yes', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'Two year', 'Yes', 'Bank transfer (automatic)', 85.1, '4657.95')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('1015-OWJKI', 1, 'Yes', 'No', 'No', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'Month-to-month', 'No', 'Mailed check', 19.05, '19.05')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('7233-DRTRF', 63, 'Yes', 'Yes', 'Fiber optic', 'No', 'Yes', 'Yes', 'No', 'Yes', 'Yes', 'Month-to-month', 'Yes', 'Electronic check', 102.4, '6444.05')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('4860-YZGZM', 10, 'Yes', 'No', 'No', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'Month-to-month', 'No', 'Electronic check', 20.0, '185.4')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('4854-CIDCF', 3, 'Yes', 'No', 'Fiber optic', 'No', 'No', 'Yes', 'No', 'No', 'No', 'Month-to-month', 'No', 'Electronic check', 73.85, '196.4')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('9507-HSMMZ', 54, 'Yes', 'No', 'No', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'Two year', 'No', 'Mailed check', 20.0, '1149.65')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('5115-GZDEL', 72, 'No', 'No phone service', 'DSL', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Two year', 'No', 'Credit card (automatic)', 67.2, '4671.7')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('5539-HIVAK', 28, 'Yes', 'Yes', 'No', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'Month-to-month', 'No', 'Mailed check', 25.7, '734.6')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('3982-DQLUS', 65, 'Yes', 'Yes', 'Fiber optic', 'Yes', 'Yes', 'No', 'No', 'No', 'No', 'Month-to-month', 'Yes', 'Electronic check', 85.75, '5688.45')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('4957-SREEC', 70, 'Yes', 'No', 'No', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'Two year', 'No', 'Credit card (automatic)', 20.35, '1458.1')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('2338-BQEZT', 55, 'Yes', 'No', 'DSL', 'Yes', 'No', 'No', 'No', 'No', 'No', 'Month-to-month', 'Yes', 'Credit card (automatic)', 50.55, '2832.75')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('7695-PKLCZ', 68, 'Yes', 'No', 'No', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'Two year', 'No', 'Credit card (automatic)', 20.5, '1424.9')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('4475-NVTLU', 45, 'Yes', 'No', 'No', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'Two year', 'No', 'Electronic check', 19.2, '903.7')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('8778-LMWTJ', 9, 'Yes', 'No', 'Fiber optic', 'Yes', 'No', 'No', 'No', 'No', 'No', 'Month-to-month', 'Yes', 'Electronic check', 74.85, '708.2')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('9298-WGMRW', 72, 'Yes', 'Yes', 'Fiber optic', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Two year', 'Yes', 'Bank transfer (automatic)', 115.5, '8312.75')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('9974-JFBHQ', 64, 'Yes', 'No', 'Fiber optic', 'No', 'Yes', 'No', 'Yes', 'Yes', 'Yes', 'Month-to-month', 'Yes', 'Credit card (automatic)', 99.15, '6171.2')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('7101-HRBLJ', 72, 'Yes', 'No', 'DSL', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Two year', 'Yes', 'Bank transfer (automatic)', 83.7, '6096.9')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('9978-HYCIN', 47, 'Yes', 'No', 'Fiber optic', 'No', 'Yes', 'No', 'No', 'Yes', 'No', 'One year', 'Yes', 'Bank transfer (automatic)', 84.95, '4018.05')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('4745-LSPLO', 1, 'Yes', 'No', 'No', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'Month-to-month', 'No', 'Mailed check', 20.5, '20.5')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('1038-RQOST', 19, 'Yes', 'No', 'No', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'Month-to-month', 'No', 'Mailed check', 20.6, '414.95')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('3144-AUDBS', 6, 'Yes', 'No', 'DSL', 'No', 'No', 'No', 'Yes', 'No', 'No', 'Month-to-month', 'Yes', 'Electronic check', 49.15, '270.8')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('1371-OJCEK', 48, 'Yes', 'Yes', 'No', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'One year', 'No', 'Bank transfer (automatic)', 24.35, '1133.7')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('8566-YPRGL', 1, 'Yes', 'No', 'No', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'Month-to-month', 'Yes', 'Mailed check', 19.5, '19.5')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('7860-UXCRM', 63, 'Yes', 'No', 'DSL', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'No', 'Two year', 'No', 'Credit card (automatic)', 74.5, '4674.55')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('7993-PYKOF', 8, 'Yes', 'No', 'Fiber optic', 'Yes', 'No', 'No', 'No', 'No', 'No', 'Month-to-month', 'No', 'Electronic check', 75.0, '632.95')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('6616-AALSR', 65, 'Yes', 'Yes', 'Fiber optic', 'Yes', 'No', 'Yes', 'No', 'Yes', 'Yes', 'Two year', 'Yes', 'Credit card (automatic)', 104.3, '6725.3')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('4955-VCWBI', 43, 'Yes', 'No', 'No', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'One year', 'No', 'Mailed check', 20.0, '817.95')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('9555-SAHUZ', 38, 'Yes', 'No', 'DSL', 'Yes', 'Yes', 'No', 'No', 'No', 'No', 'Month-to-month', 'No', 'Electronic check', 54.5, '2076.05')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('1612-EOHDH', 1, 'Yes', 'No', 'DSL', 'No', 'No', 'No', 'No', 'No', 'No', 'Month-to-month', 'No', 'Electronic check', 45.15, '45.15')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('1755-RMCXH', 2, 'Yes', 'No', 'No', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'No internet service', 'Month-to-month', 'No', 'Mailed check', 20.3, '40.25')
INSERT INTO account_info ( customerID, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges ) VALUES  ('2959-MJHIC', 4, 'Yes', 'No', 'Fiber optic', 'No', 'No', 'No', 'No', 'Yes', 'No', 'Month-to-month', 'Yes', 'Electronic check', 80.35, '307.4')

INSERT INTO target_info ( customerID, Churn ) VALUES  ('5640-CAXOA', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3946-MHCZW', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8374-UULRV', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2108-YKQTY', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2862-PFNIK', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2856-HYAPG', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3707-GNWHM', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2363-BJLSL', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3663-MITLP', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3373-YZZYM', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5848-FHRFC', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0840-DFEZH', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5879-HMFFH', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4723-BEGSG', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3976-BWUCK', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7120-RFMVS', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8292-FRFZQ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9480-BQJEI', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4350-ZTLPI', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3763-GCZHZ', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1658-XUHBX', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2507-QZPQS', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0564-JJHGS', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9750-BOOHV', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8773-HHUOZ', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1335-MXCSE', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6029-CSMJE', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8707-RMEZH', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0771-CHWSK', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3703-KBKZP', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9477-LGWQI', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4893-GYUJU', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2393-DIVAI', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0872-JCPIB', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9909-IDLEK', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4086-WITJG', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2874-YXVVA', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0057-QBUQH', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4676-MQUEA', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0580-PIQHM', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5243-SAOTC', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8347-GDTMP', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5012-YSPJJ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5288-AHOUP', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7488-MXJIV', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9867-XOBQA', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2511-ALLCS', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5578-NKCXI', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1223-UNPKS', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9087-EYCPR', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5924-SNGKP', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1101-SSWAG', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0082-LDZUE', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2003-CKLOR', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0679-IDSTG', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7729-JTEEC', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1550-LOAHA', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8336-TAVKX', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9114-VEPUF', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2688-BHGOG', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2038-OEQZH', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4767-HZZHQ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0093-XWZFY', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5519-TEEUH', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1088-CNNKB', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1813-JLKWR', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4566-NECEV', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1009-IRMNA', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7410-OIEDU', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7549-MYGPK', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0056-EPFBG', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5032-USPKF', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6723-WSNTY', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1195-OIYEJ', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7964-YESJC', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5995-SNNEW', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9904-EHEVJ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7876-AEHIG', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4933-BSAIP', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2978-XXSOG', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2585-KTFRE', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4847-TAJYI', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6141-OOXUQ', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8189-DUKMV', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7752-XUSCI', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4334-HOWRP', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4445-KWOKW', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0541-FITGH', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8039-EQPIM', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6474-FVJLC', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3776-EKTKM', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7036-ZZKBD', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6696-YDAYZ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6040-CGACY', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3006-XIMLN', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7668-XCFYV', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6101-IMRMM', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7839-NUIAA', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7302-ZHMHP', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7661-CPURM', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5583-EJXRD', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7055-JCGNI', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8946-BFWSG', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7636-PEPNS', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7619-PLRLP', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2478-EEWWM', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6305-YLBMM', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4429-WYGFR', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6064-PUPMC', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1097-FSPVW', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9058-CBREO', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9239-ZBZZV', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9084-OAYKL', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5299-SJCZT', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5231-FIQPA', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7670-ZBPOQ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8749-JMNKX', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2067-QYTCF', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3129-AAQOU', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1036-GUDCL', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5375-XLDOF', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3191-CSNMG', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3874-EQOEP', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7517-SAWMO', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2609-IAICY', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2632-TACXW', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3334-CTHOL', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6513-EECDB', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4945-RVMTE', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9589-ABEPT', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4248-HCETZ', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1862-SKORY', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1135-LMECX', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7881-INRLC', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7163-OCEQI', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7634-HLQJR', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4986-MXSFP', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8066-POXGX', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5025-GOOKI', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6425-JWTDV', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8402-EIVQS', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1325-USMEC', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4049-ZPALD', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6393-WRYZE', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1971-DTCZB', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1684-FLBGS', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7508-SMHXL', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8429-XIBUM', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6061-GWWAV', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5680-LQOGP', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6050-IJRHS', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0363-SVHYR', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6997-UVGOX', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5858-EAFCZ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3583-EKAPL', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7764-BDPEE', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1685-BQULA', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3329-WDIOK', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1240-HCBOH', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2122-YWVYA', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2164-SOQXL', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9306-CPCBC', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8975-SKGRX', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2894-QOJRX', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8189-XRIKE', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0506-YLVKJ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2007-QVGAW', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0253-ZTEOB', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4629-NRXKX', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8268-YDIXR', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1569-TTNYJ', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4090-KPJIP', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5312-IRCFR', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9224-VTYID', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3796-ENZGF', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0098-BOWSO', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1732-VHUBQ', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5075-JSDKI', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0620-XEFWH', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0164-APGRB', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9987-LUTYD', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5067-XJQFU', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6223-DHJGV', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0114-RSRRW', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2656-FMOKZ', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6568-POCUI', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7445-WMRBW', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2209-XADXF', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2523-EWWZL', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4903-UYAVB', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2294-SALNE', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2460-NGXBJ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4238-JSSWH', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6352-GIGGQ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5524-KHNJP', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9127-FHJBZ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1360-XFJMR', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6147-CBCRA', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4565-EVZMJ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0011-IGKFF', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7989-VCQOH', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0378-CJKPV', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8999-BOHSE', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5533-NHFRF', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6627-CFOSN', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1641-RQDAY', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2143-LJULT', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1142-IHLOO', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2931-VUVJN', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1116-FRYVH', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8051-HJRLT', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9347-AERRL', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2037-SGXHH', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8748-HFWBO', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7576-OYWBN', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2675-DHUTR', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6844-DZKRF', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0867-LDTTC', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0019-EFAEP', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6689-VRRTK', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2332-EFBJY', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5311-IHLEI', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2990-HWIML', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7134-HBPBS', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6510-UPNKS', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9565-JSNFM', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3946-JEWRQ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8540-ZQGEA', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7718-RXDGG', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5609-CEBID', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7916-VCCPB', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6457-GIRWB', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6366-ZGQGL', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5310-NOOVA', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0727-BNRLG', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6172-FECYY', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5944-UGLLK', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1015-JPFYW', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3982-XWFZQ', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4316-XCSLJ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9050-IKDZA', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6728-DKUCO', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0536-BGFMZ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8992-JQYUN', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3540-RZJYU', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5481-NTDOH', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0897-FEGMU', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2530-FMFXO', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8467-WYNSR', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4976-LNFVV', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1051-EQPZR', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4307-KWMXE', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1769-GRUIK', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4774-HHGGS', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4501-VCPFK', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5089-IFSDP', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9526-BIHHD', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5174-RNGBH', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3696-XRIEN', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6174-NRBTZ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8660-BUETV', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1596-OQSPS', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7147-AYBAA', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0156-FVPTA', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3873-WOSBC', 'No')

INSERT INTO target_info ( customerID, Churn ) VALUES  ('5027-XWQHA', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9443-JUBUO', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2325-ZUSFD', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6953-PBDIN', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3247-ZVOUO', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6629-CZTTH', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2176-LVPNX', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9505-SQFSW', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1705-GUHPV', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7978-DKUQH', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7608-RGIRO', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3807-BPOMJ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1960-UOTYM', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9560-ARGQJ', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5294-DMSFH', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2485-ITVKB', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7967-HYCDE', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2135-DQWAQ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5396-IZEPB', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6022-UGGSO', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7971-HLVXI', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7021-XSNYE', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1986-PHGZF', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5118-MUEYH', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3841-NFECX', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3494-JCHRQ', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5440-VHLUL', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3154-HMWUU', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0616-ATFGB', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2607-FBDFF', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3717-LNXKW', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1336-EZFZY', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7954-MLBUN', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6646-JPPHA', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0013-SMEOE', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9878-TNQGW', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9777-IQHWP', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0570-BFQHT', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5285-MVEHD', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9093-FPDLG', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2848-YXSMW', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0970-QXPXW', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2522-AHJXR', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9373-WSLOY', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4277-BWBML', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6156-UZDLF', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0378-TOVMS', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2436-QBZFP', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3402-XRIUO', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4929-BSTRX', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0285-INHLN', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4501-EQDRN', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0337-CNPZE', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2272-QAGFO', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5027-QPKTE', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5423-BHIXO', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1338-CECEE', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2718-GAXQD', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4521-WFJAI', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3336-JORSO', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5485-WUYWF', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8868-WOZGU', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7246-ZGQDF', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2967-MXRAV', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4512-ZUIYL', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8361-LTMKD', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2697-NQBPF', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6872-HXFNF', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1386-ZIKUV', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2330-PQGDQ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1930-BZLHI', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2999-AANRQ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5198-EFNBM', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8185-UPYBR', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5780-INQIK', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6791-YBNAK', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5931-FLJJF', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6131-FOYAS', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5985-TBABQ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4998-IKFSE', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0980-FEXWF', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6075-SLNIL', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7279-BUYWN', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5337-IIWKZ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3605-JISKB', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2267-WTPYD', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6797-UCJHZ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2716-GFZOR', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5393-HJZSM', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8203-XJZRC', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7013-PSXHK', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5312-UXESG', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6741-EGCBI', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6204-IEUXJ', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6353-BRMMA', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2344-JMOGN', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2077-MPJQO', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8091-TTVAX', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6900-RBKER', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8319-QBEHW', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9860-LISIZ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5206-XZZQI', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9529-OFXHY', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1725-MIMXW', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4324-AHJKS', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2133-TSRRM', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2809-ZMYOQ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4032-RMHCI', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8409-WQJUX', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1536-YHDOE', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1140-UKVZG', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2987-BJXIK', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3653-NCRDJ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9365-CSLBQ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8263-JQAIK', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3452-SRFEG', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5985-BEHZK', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4993-JCRGJ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1133-KXCGE', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6521-YYTYI', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6158-DWPZT', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2305-MRGLV', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7293-LSCDV', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2958-NHPPS', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2154-KVJFF', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2038-YSEZE', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2418-TPEUN', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1877-HKBQX', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1544-JJMYL', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5583-SXDAG', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8646-JCOMS', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6048-QBXKL', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8999-EXMNO', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6242-SGYTS', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4626-OZDTJ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4024-CSNBY', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4112-LUEIZ', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6252-DFGTK', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4422-QVIJA', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7766-CLTIC', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1934-SJVJK', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5260-UMPWX', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4291-TPNFG', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4803-AXVYP', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8784-CGILN', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9150-HEPMB', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8570-KLJYJ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9054-FOWNV', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0960-HUWBM', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1134-YWTYF', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3002-WQZWT', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2660-EMUBI', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2786-GCDPI', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3914-FDRHP', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0269-XFESX', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7619-ODSGN', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2043-WVTQJ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0384-RVBPI', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0378-XSZPU', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5529-GIBVH', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7322-OCWHC', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8735-IJJEG', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8050-XGRVL', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4846-WHAFZ', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6907-CQGPN', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3970-XGJDU', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8631-WUXGY', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7218-HKQFK', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6212-ATMLK', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8625-AZYZY', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7740-BTPUX', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8869-LIHMK', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4951-UKAAQ', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6624-JDRDS', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9248-OJYKK', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0513-RBGPE', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3836-FZSDJ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1301-LOPVR', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7479-NITWS', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3312-UUMZW', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0060-FUALY', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2985-JUUBZ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5016-ETTFF', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1998-VHJHK', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1925-TIBLE', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0485-ZBSLN', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4817-QRJSX', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7299-GNVPL', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0945-TSONX', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6859-RKMZJ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4177-JPDFU', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4459-BBGHE', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5196-SGOAK', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0103-CSITQ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7206-PQBBZ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7727-SHVZV', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2608-BHKFN', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4860-IJUDE', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9509-MPYOD', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3813-DHBBB', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8672-OAUPW', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9564-KCLHR', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8659-IOOPU', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3312-ZWLGF', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8267-ZNYVZ', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0305-SQECB', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7018-WBJNK', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8922-NPKBJ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7421-ZLUPA', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6982-SSHFK', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9031-ZVQPT', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0178-SZBHO', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3370-GQEAL', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3584-WKTTW', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0848-ZGQIJ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6116-RFVHN', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5229-PRWKT', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8237-ULIXL', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3915-ODIYG', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5914-XRFQB', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6476-EPYZR', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9227-YBAXE', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2171-UDMFD', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3351-NQLDI', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7838-LAZFO', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7131-ZQZNK', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9822-OAOVB', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5614-DNZCE', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7943-RQCHR', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9840-EFJQB', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7089-RKVSZ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2962-XPMCQ', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9081-WWXKP', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2982-IHMFT', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3069-SSVSN', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2968-SSGAA', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3417-TSCIC', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5320-BRKGK', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1345-ZUKID', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0750-EKNGL', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5685-IIXLY', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0516-VRYBW', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1069-QJOEE', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3174-AKMAS', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2207-NHRJK', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0623-GDISB', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7570-WELNY', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6954-OOYZZ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6496-JDSSB', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2616-FLVQC', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2865-TCHJW', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4671-VJLCL', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4525-VZCZG', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0536-ESJEP', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0270-THENM', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1636-NTNCO', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1227-UDMZR', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9000-PLFUZ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6319-IEJWJ', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9112-WSNPU', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3097-NNSPB', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1853-ARAAQ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4559-UWIHT', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5240-IJOQT', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5642-MHDQT', 'No')

INSERT INTO target_info ( customerID, Churn ) VALUES  ('7994-UYIVZ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6712-OAWRH', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2077-DDHJK', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4697-LUPSU', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3488-PGMQJ', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0030-FNXPP', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0952-KMEEH', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7594-LZNWR', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0769-MURVM', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8706-HRADD', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2873-ZLIWT', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8208-EUMTE', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6933-FHBZC', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5536-RTPWK', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3764-MNMOI', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5442-XSDCW', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5766-FTRTS', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6961-MJKBO', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5510-BOIUJ', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6917-YACBP', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6461-SZMCV', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7632-YUTXB', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8915-NNTRC', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9700-ZCLOT', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4808-YNLEU', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3324-OIRTO', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6583-KQJLK', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6870-ECSHE', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6985-HAYWX', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4184-TJFAN', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4039-PIMHX', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0064-YIJGF', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1763-WQFUK', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1094-BKOSX', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5370-IIVVL', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1488-PBLJN', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0516-UXRMT', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8510-TMWYB', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6967-QIQRV', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1349-WXNGG', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1768-ZAIFU', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0336-KXKFK', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8080-POTJR', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2190-BCXEC', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6253-GNHWH', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2011-TRQYE', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4987-GQWPO', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4735-BJKOU', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2499-AJYUA', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3936-QQFLL', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3251-YMVWZ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8879-XUAHX', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2604-IJPDU', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4320-QMLLA', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5609-IMCGG', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1820-DJFPH', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8859-AXJZP', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3284-SVCRO', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8739-XNIKG', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6810-VCAEX', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4396-KLSEH', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9079-LWTFD', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9921-EZKBY', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8404-VLQFB', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0130-SXOUN', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8780-IXSTS', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3824-RHKVR', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2359-KLTEK', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1091-SOZGA', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2155-AMQRX', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3704-IEAXF', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7312-XSBAT', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4010-YLMVT', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5915-ANOEI', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8679-LZBMD', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2372-HWUHI', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7162-WPHPM', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8822-KNBHV', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0315-LVCRK', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8263-QMNTJ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0526-SXDJP', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5201-USSQZ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4132-POCZS', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9257-AZMTZ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5447-VYTKW', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5960-WPXQM', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2826-UWHIS', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7251-XFOIL', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6923-JHPMP', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1373-ORVIZ', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8220-OCUFY', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9488-HGMJH', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2446-BEGGB', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5781-RFZRP', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0973-KYVNF', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3740-RLMVT', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5837-LXSDN', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0404-AHASP', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1934-MKPXS', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3049-SOLAY', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8914-RBTSB', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1925-LFCZZ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8372-JUXUI', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5863-OOKCL', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8262-COGGB', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3320-VEOYC', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1096-ADRUX', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5668-MEISB', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4801-JZAZL', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6578-KRMAW', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8884-ADFVN', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6933-VLYFX', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4825-XJGDM', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1846-XWOQN', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8089-UZWLX', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5940-AHUHD', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0432-CAJZV', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3249-ZPQRG', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6726-WEXXK', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2984-AFWNC', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9122-UMROB', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0238-WHBIQ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2405-LBMUW', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5153-LXKDT', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3007-FDPEA', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2791-SFVEW', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6265-FRMTQ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6680-WKXRZ', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3174-RKMOW', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0829-DDVLK', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1415-YFWLT', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7599-FKVXZ', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5692-FPTAH', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0020-INWCK', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3170-NMYVV', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8807-OPMBM', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3557-HTYWR', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7552-KEYGT', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6061-PQHMK', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6907-NZZIJ', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2252-ISRNH', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0481-SUMCB', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4737-HOBAX', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3780-YVMFA', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8908-NMQTX', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2955-BJZHG', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9776-CLUJA', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9030-QGZNL', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0268-QKIWO', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1555-HAPSU', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6435-VWCCY', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1320-GVNHT', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5275-PMFUT', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2988-QRAJY', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7274-CGTOD', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0442-ZXKVS', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1407-DIGZV', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9069-LGEUL', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9046-DQMTP', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6075-QMNRR', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5091-HFAZW', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9135-HSWOC', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7365-BVCJH', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4450-MDZFX', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7384-GHBPI', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0392-BZIUW', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3916-NRPAP', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1744-JHKYS', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2842-BCQGE', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7134-MJPDY', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5555-RNPGT', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0520-FDVVT', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0670-KDOMA', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0655-YDGFJ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8329-GWVPJ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8816-VXNZD', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0895-LMRSF', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9283-LZQOH', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9577-WJVCQ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4452-ROHMO', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4682-BLBUC', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9812-GHVRI', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7601-DHFWZ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0817-HSUSE', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4598-ZADCK', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7883-ROJOC', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6145-NNPNO', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9738-QLWTP', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9154-QDGTH', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9430-FRQOC', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7998-WNZEM', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2195-ZRVAX', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9722-UJOJR', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8224-UAXBZ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8614-VGMMV', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2904-GGUAZ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6397-JNZZG', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4598-XLKNJ', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8739-QOTTN', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1635-FJFCC', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1794-SWWKL', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0486-LGCCH', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6509-TSGWN', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4078-SAYYN', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7088-FBAWU', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5268-DSMNQ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1666-JZPZT', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9621-OUPYD', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0608-JDVEC', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0979-PHULV', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9891-NQDBD', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6169-PPETC', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8873-TMKGR', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4832-VRBMR', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2878-DHMIN', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6582-PLFUU', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3859-CVCET', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2040-LDIWQ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3511-APPBJ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3865-QBWSJ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5019-GQVCR', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5197-YPYBZ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4837-QUSFT', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0916-QOFDP', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6331-EWIEB', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5181-OABFK', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6743-HHQPF', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1391-UBDAR', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7314-OXENN', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1465-WCZVT', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3428-XZMAZ', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1093-YSWCA', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1230-QAJDW', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8605-ITULD', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2181-TIDSV', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1722-LDZJS', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5298-GSTLM', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4274-DRSQT', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9473-CBZOP', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6705-LXORM', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2778-OCLGR', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5906-CVLHP', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6137-NICCO', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8348-JLBUG', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1930-WNXSB', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6015-VVHHE', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7869-ZYDST', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0939-YAPAF', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9294-TDIPC', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6692-YQHXC', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8999-XXGNS', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1150-FTQGN', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6651-RLGGM', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5684-FJVYR', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9447-YPTBX', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2740-JFBOK', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6108-OQZDQ', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0722-TROQR', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2504-DSHIH', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6229-LSCKB', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9169-BSVIN', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9512-PHSMG', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1319-YLZJG', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0628-CNQRM', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2452-SNHFZ', 'No')

INSERT INTO target_info ( customerID, Churn ) VALUES  ('3547-LQRIK', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0376-OIWME', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0325-XBFAC', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2292-XQWSV', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2252-JHJGE', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6176-YJWAS', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6383-ZTSIW', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4365-MSDYN', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1455-ESIQH', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4664-NJCMS', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4911-BANWH', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7394-FKDNK', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8285-ABVLB', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4644-OBGFZ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8410-BGQXN', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4091-TVOCN', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7157-SMCFK', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9799-CAYJJ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3683-QKIUE', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3538-WZPHD', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8205-OTCHB', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7674-YTAFD', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1571-SAVHK', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1779-PWPMG', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3969-JQABI', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3313-QKNKB', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9086-YJYXS', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1248-DYXUB', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0621-TWIEM', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8679-JOEVF', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3424-NMNBO', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7209-JCUDS', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7952-OBOYL', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7876-DNYAP', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6549-NNDYT', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5419-KLXBN', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5028-HTLJB', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1541-ETJZO', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6999-CHVCF', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5167-ZFFMM', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6326-MTTXK', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4195-NZGTA', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5619-PTMIK', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3932-IJWDZ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7089-IVVAZ', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3387-VATUS', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5482-VXSXJ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2386-OWURY', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2625-TRCZQ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9039-RBEEE', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6765-MBQNU', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0843-WTBXE', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1448-PWKYE', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6317-YPKDH', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2027-CWDNU', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2068-WWXQZ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6110-OHIHY', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3945-GFWQL', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8645-KWHJO', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2815-CPTUL', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0516-OOHAR', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0397-GZBBC', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3580-REOAC', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8200-KLNYW', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3317-HRTNN', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9108-EQPNQ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3420-ZDBMA', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0727-IWKVK', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8168-UQWWF', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8313-AFGBW', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6351-SCJKT', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0231-LXVAP', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8328-SKJNO', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4385-GZQXV', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9513-DXHDA', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7225-IILWY', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2969-QWUBZ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2739-CCZMB', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9943-VSZUV', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4549-ZDQYY', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9885-AIBVB', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2262-SLNVK', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9408-SSNVZ', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0383-CLDDA', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6537-QLGEX', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2371-JQHZZ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9919-YLNNG', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5073-WXOYN', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2754-VDLTR', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5778-BVOFB', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6614-VBEGU', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7542-CYDDM', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1352-HNSAW', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0744-GKNGE', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9101-NTIXF', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6258-PVZWJ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7181-BQYBV', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1074-WVEVG', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1357-BIJKI', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7602-MVRMB', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2972-YDYUW', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1763-KUAAW', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8894-JVDCV', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5474-LAMUQ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0117-LFRMW', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4439-JMPMT', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9576-ANLXO', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3014-WJKSM', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4926-UMJZD', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6527-PZFPV', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7401-RUBNK', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4558-FANTW', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8990-YOZLV', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7560-QRBXH', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0040-HALCW', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2971-SGAFL', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1845-CSBRZ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4819-HJPIW', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0577-WHMEV', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7563-BIUPC', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9504-YAZWB', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6896-SRVYQ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8761-NSOBC', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4701-LKOZD', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4587-VVTOX', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0983-TATYJ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8084-OIVBS', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0402-OAMEN', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7363-QTBIW', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0230-UBYPQ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5808-TOTXO', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3186-AJIEK', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8404-VIOMB', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8040-MNRTF', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8294-UIMBA', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9506-UXUSK', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9488-FVZCC', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9415-TPKRV', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3325-FUYCG', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5055-MGMGF', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5701-YVSVF', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1439-LCGVL', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9693-XMUOB', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2626-VEEWG', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1591-XWLGB', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0533-UCAAU', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7110-BDTWG', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7493-GVFIO', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9838-BFCQT', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1746-TGTWV', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5937-EORGB', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0793-TWELN', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6243-OZGFH', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4119-ZYPZY', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7925-PNRGI', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5966-EMAZU', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9504-DSHWM', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3814-MLAXC', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5150-ITWWB', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4092-OFQZS', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1573-LGXBA', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5233-GEEAX', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2650-GYRYL', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5010-IPEAQ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5494-WOZRZ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3863-QSTYI', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0673-IGUQO', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3585-YNADK', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3891-PUQOD', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4445-ZJNMU', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5712-VBOXD', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7873-CVMAW', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1017-FBQMM', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6918-UMQCG', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4391-LNRXK', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4896-CPRPF', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2187-PKZAY', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4203-QGNZA', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6579-JPICP', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7694-VLBWQ', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3133-PZNSR', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9356-AXGMP', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9097-ZUBYC', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0840-DCNZE', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8780-IHCRN', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3285-UCQVC', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1833-VGRUM', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7446-SFAOA', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0836-SEYLU', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1752-OZXFY', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5240-CAOYT', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2887-JPYLU', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3021-VLNRJ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6257-RJOHI', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4910-AQFFX', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0396-YCHWO', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5482-PLVPE', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1830-GGFNM', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7951-VRDVK', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3977-QCRSL', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2615-YVMYX', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0323-XWWTN', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6974-DAFLI', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0224-HJAPT', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2386-LAHRK', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9541-ZPSEA', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1193-RTSLK', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3351-NGXYI', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9359-UGBTK', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9788-HNGUT', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7855-DIWPO', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5222-JCXZT', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0975-VOOVL', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4419-UJMUS', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4424-TKOPW', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6797-LNAQX', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6770-XUAGN', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2640-LYMOV', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7928-VJYAB', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6821-BUXUX', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8917-SZTTJ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0947-MUGVO', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8727-XDPUD', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7305-ZWMAJ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3413-DHLPB', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2884-GBPFB', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7480-QNVZJ', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1696-HXOWK', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4480-QQRHC', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8461-EFQYM', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2429-AYKKO', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4690-PKDQG', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8961-QDZZJ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9330-VOFSZ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0174-QRVVY', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8785-EPNCG', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9115-YQHGA', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9194-GFVOI', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6595-COKXZ', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3154-CFSZG', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0679-TDGAK', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6434-TTGJP', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6631-HMANX', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0665-XHDJU', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3428-MMGUB', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5570-PTWEH', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5712-PTIWW', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8821-XNHVZ', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1173-XZPYF', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3545-CNWRG', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4806-DXQCE', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0685-MLYYM', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1075-BGWOH', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8443-WVPSS', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4114-QMKVN', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2038-LLMLM', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5605-XNWEN', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0426-TIRNE', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0559-CKHUS', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0203-HHYIJ', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6094-ZIVKX', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2897-DOVND', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8387-MOJJT', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2587-YNLES', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6693-FRIRW', 'No')

INSERT INTO target_info ( customerID, Churn ) VALUES  ('6173-GOLSU', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5522-NYKPB', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2990-IAJSV', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6483-OATDN', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4572-DVCGN', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7787-BNTZM', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1309-XGFSN', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3810-PJUHR', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2000-DHJUY', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5995-LFTLE', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8205-VSLRB', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6928-ONTRW', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5498-IBWPI', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3845-JHAMY', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4504-YOULA', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9776-OJUZI', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3798-EPWRR', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1376-HHBDV', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9436-ZBZCT', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4797-MIWUM', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7198-GLXTC', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0455-ENTCR', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0463-WZZKO', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6849-WLEYG', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9281-CEDRU', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8861-HGGKB', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9139-WQQDY', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8204-TIFGJ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9290-SHCMB', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6734-JDTTV', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5697-GOMBF', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5644-PDMZC', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3987-KQDDU', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4176-FXYBO', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0074-HDKDG', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1635-HDGFT', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2790-XUYMV', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3982-JGSFD', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8573-CGOCC', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8515-OCTJS', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3115-JPJDD', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0562-HKHML', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4187-CINZD', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5840-NVDCG', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8610-WFCJF', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6840-RESVB', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7881-EVUAD', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1697-BCSHV', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7577-SWIFR', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7460-ITWWP', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6608-QQLVK', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2761-XECQW', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7270-BDIOA', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0052-DCKON', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3235-ETOOB', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3865-YIOTT', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7771-CFQRQ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8111-RKSPX', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6311-UEUME', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3963-RYFNS', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6127-ISGTU', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4234-XTNEA', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7551-JOHTI', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3533-UVMOM', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6551-ZCOTS', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9063-ZGTUY', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4816-LXZYW', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6937-GCDGQ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7321-ZNSLA', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2057-ZBLPD', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0471-ARVMX', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1984-GPTEH', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1576-PFZIW', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8378-LKJAF', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2091-RFFBA', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7153-OANIO', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3085-QUOZK', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3850-OKINF', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1354-YZFNB', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8183-ONMXC', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3137-LUPIX', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3705-RHRFR', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0083-PIVIK', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8782-NUUOL', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8000-REIQB', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4191-XOVOM', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9631-RXVJM', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2528-HFYZX', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4159-NAAIX', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1697-NVVGY', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0115-TFERT', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8421-WZOOW', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3345-PBBFH', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6490-FGZAT', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5317-FLPJF', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3795-GWTRD', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8417-GSODA', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7850-VWJUU', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1498-DQNRX', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8490-BXHEO', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3160-TYXLT', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3468-DRVQJ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4835-YSJMR', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6217-TOWGS', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0048-LUMLS', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3769-MHZNV', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6668-CNMFP', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0567-GGCAC', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0260-ZDLGK', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3308-JSGML', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0036-IHMOT', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9763-PDTKK', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8727-JQFHV', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4304-TSPVK', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5148-ORICT', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2234-XADUH', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5383-MMTWC', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8513-OLYGY', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5133-POWUA', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6244-BESBM', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1206-EHBDD', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4283-IVYCI', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9804-ICWBG', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4759-PXTAN', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2694-CIUMO', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0219-YTZUE', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6168-WFVVF', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7794-JASDG', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0468-YRPXN', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4973-MGTON', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6543-JXSOO', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1222-LRYKO', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5917-HBSDW', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0496-AHOOK', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2040-VZIKE', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3737-GCSPV', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2578-JQPHZ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6674-KVJHG', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1395-OFUWC', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6689-KXGBO', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3389-KTRXV', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6575-SUVOI', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8107-KNCIM', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4547-KQRTM', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5566-SOEZD', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5052-PNLOS', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7554-NEWDD', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9708-HPXWZ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5939-SXWHM', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7351-KYHQH', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6281-FKEWS', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1597-FZREH', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2919-HBCJO', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5394-SVGJV', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6112-KTHFQ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1898-JSNDC', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7995-ZHHNZ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2165-VOEGB', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7746-QYVCO', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5126-RCXYW', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5951-AOFIH', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2582-FFFZR', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2758-RNWXS', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9986-BONCE', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8559-WNQZS', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4980-URKXC', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3099-OONVS', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2710-WYVXG', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5590-BYNII', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0265-PSUAE', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8152-UOBNY', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8003-EWNDZ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4404-HIBDJ', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5959-BELXA', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7643-RCHXS', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4468-YDOVK', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8919-FYFQZ', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5565-FILXA', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5815-HGGHV', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1552-AAGRX', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7269-JISCY', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5446-DKWYW', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3506-LCJDC', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0956-ACVZC', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2482-CZGBB', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6682-QJDGB', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3128-YOVTD', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1090-ESELR', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9570-KYEUA', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4707-MAXGU', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7872-BAAZR', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2592-SEIFQ', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9603-OAIHC', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0637-UBJRP', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5057-LCOUI', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2754-XBHTB', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6518-KZXCB', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5331-RGMTT', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1430-SFQSA', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2889-FPWRM', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2251-PYLPB', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6599-RCLCJ', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5155-AZQPB', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8167-GJLRN', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4304-XUMGI', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4510-HIMLV', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5349-IECLD', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3717-OEAUQ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1984-FCOWB', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5973-EJGDP', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2378-VTKDH', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7274-RTAPZ', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0811-GSDTP', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1450-GALXR', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8380-MQINP', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9210-IAHGH', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1179-INLAT', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0756-MPZRL', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4369-NYSCF', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7017-VFHAY', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1485-YDHMM', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1041-RXHRA', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3696-DFHHB', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9917-KWRBE', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2391-IPLOP', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3669-WHAFY', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0921-OHLVP', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8514-VZHEB', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7326-RIGQZ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7951-QKZPL', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7812-FZHPE', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6322-HRPFA', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2302-OUZXB', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7029-RPUAV', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7105-BENQF', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2466-NEJOJ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1852-XEMDW', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2263-SFSQZ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5712-AHQNN', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9743-DQKQW', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8552-OBVRU', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4086-ATNFV', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2403-BCASL', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8561-NMTBD', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5448-VWNAM', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8769-KKTPH', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7831-QGOXH', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2480-JZOSN', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2982-VPSGI', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8496-DMZUK', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3858-VOBET', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4484-GLZOU', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0594-UFTUL', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0757-WCUUZ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8286-AFUYI', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2868-LLSKM', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4957-TREIR', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6416-TVAIH', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9259-PACGQ', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2676-SSLTO', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8143-ETQTI', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0831-JNISG', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3572-UOLYZ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7550-WIQVA', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7568-PODML', 'Yes')

INSERT INTO target_info ( customerID, Churn ) VALUES  ('3186-BAXNB', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8917-FAEMR', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8204-YJCLA', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8714-EUHJO', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8878-RYUKI', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6941-KXRRV', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1894-IGFSG', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5899-MQZZL', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9152-AMKAK', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6135-OZQVA', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3407-JMJQQ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4919-MOAVT', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5825-XJOCM', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3948-FVVRP', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3070-DVEYC', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6240-EURKS', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7446-YPODE', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2959-FENLU', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8225-BTJAU', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3247-MHJKM', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2657-ALMWY', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4452-QIIEB', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6603-QWSPR', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9717-IOAAF', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7254-IQWOZ', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2460-FPSYH', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0617-FHSGK', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4250-ZBWLV', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4495-LHSSK', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3957-LXOLK', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5781-BKHOP', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6691-CCIHA', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3957-SQXML', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6416-JNVRK', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2040-OBMLJ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8982-NHAVY', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9554-DFKIC', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3797-FKOGQ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0691-IFBQW', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0440-QEXBZ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8738-JOKAR', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7410-KTVFV', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2817-LVCPP', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6497-TILVL', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0839-JTCUD', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0128-MKWSG', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3716-BDVDB', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7159-NOKYQ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7714-YXSMB', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4070-OKWVH', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1689-YQBYY', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1907-UBQFC', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1895-QTKDO', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3537-RYBHH', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5414-OFQCB', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1031-IIDEO', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3258-SYSWS', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0723-VSOBE', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6188-UXBBR', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1941-HOSAM', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3633-CDBUW', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8295-KMENE', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0125-LZQXK', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9730-DRTMJ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1047-RNXZV', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5699-BNCAS', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0206-TBWLC', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9095-HFAFX', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3131-NWVFJ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0596-BQCEQ', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5248-RPYWW', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6362-QHAFM', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7394-LWLYN', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2452-MRMZF', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6609-MXJHJ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5981-ITEMU', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0191-EQUUH', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9253-VIFJQ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1245-HARPS', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5627-TVBPP', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1137-DGOWI', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8812-ZRHFP', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5223-UZAVK', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0730-BGQGF', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4430-UZIPO', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3030-YDNRM', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2025-JKFWI', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2332-TODQS', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3709-OIJEA', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0930-EHUZA', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9174-IHETN', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5724-BIDBU', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1217-VASWC', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1735-XMJVH', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1791-PQHBB', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1492-QGCLU', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3327-YBAKM', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5206-HPJKM', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9814-AOUDH', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6888-SBYAI', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1545-ACTAS', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7634-WSWDB', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6818-DJXAA', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2896-TBNBE', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2498-XLDZR', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5439-WIKXB', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3393-FMZPV', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1452-KIOVK', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5598-IKHQQ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5789-LDFXO', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6620-HVDUJ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8659-HDIYE', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5760-IFJOZ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7442-YGZFK', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7537-CBQUZ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0939-EREMR', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7395-XWZOY', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0292-WEGCH', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4487-ZYJZK', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5539-TMZLF', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9610-WCESF', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1264-BYWMS', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1177-XZBJL', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6199-IPCAO', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3800-LYTRK', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8869-TORSS', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0667-NSRGI', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2853-CWQFQ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3378-AJRAO', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9495-SKLKD', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1450-SKCVI', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8069-YQQAJ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4450-DLLMH', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3340-QBBFM', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5669-SRAIP', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9220-CXRSC', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0181-RITDD', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7878-RTCZG', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0708-SJDIS', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3842-QTGDL', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7473-ZBDSN', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6559-RAKOZ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9689-PTNPG', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5859-HZYLF', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6234-PFPXL', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6289-CPNLD', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6368-TZZDT', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3865-ZFZIB', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7164-BPTUT', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9134-WYRVP', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7663-RGWBC', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0258-NOKBL', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6469-MRVET', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2834-JKOOW', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7639-LIAYI', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4710-FDUIZ', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5835-BEQEU', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5701-GUXDC', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5795-KTGUD', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7009-LGECI', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6285-FTQBF', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0691-NIKRI', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1587-FKLZB', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1064-FBXNK', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3197-ARFOY', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8717-VCTXJ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4947-DSMXK', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4614-NUVZD', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2925-VDZHY', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7297-DVYGA', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0533-BNWKF', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6097-EQISJ', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6267-DCFFZ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5913-INRQV', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5536-SLHPM', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6838-YAUVY', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4628-CTTLA', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1867-BDVFH', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3845-FXCYS', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3223-DWFIO', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3569-JFODW', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0442-TDYUO', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9534-NSXEM', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5384-ZTTWP', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9274-UARKJ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1347-KTTTA', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0835-JKADZ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9968-FFVVH', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2369-FEVNO', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7940-UQQUG', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6959-GQEGV', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5702-SKUOB', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3640-PHQXK', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3192-NQECA', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4002-BQWPQ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4193-IBKSW', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6784-XYJAE', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1942-OQFRW', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3213-VVOLG', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2805-AUFQN', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9498-FIMXL', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3026-ATZYV', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6350-XFYGW', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6421-SZVEM', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2580-ASVVY', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7140-ADSMJ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5207-PLSTK', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0357-NVCRI', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4735-ASGMA', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1704-NRWYE', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4658-HCOHW', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4283-FUTGF', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4712-AUQZO', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0363-QJVFX', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1261-FWTTE', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5906-DVAPM', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8234-GSZYK', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4816-JBHOV', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6435-SRWBJ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9715-SBVSU', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8313-KTIHG', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7878-JGDKK', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9367-TCUYN', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1334-PDUKM', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7249-WBIYX', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0691-JVSYA', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3224-DFQNQ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7956-XQWGU', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8988-ECPJR', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4706-AXVKM', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3913-RDSJZ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0620-DLSLK', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3039-MJSLN', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1307-ATKGB', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6023-GSSXW', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0564-MUUQK', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6137-MFAJN', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9206-GVPEQ', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4395-PZMSN', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9389-ACWBI', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8775-ERLNB', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9574-RKJIF', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7315-WYOAW', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3214-IYUUQ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9618-LFJRU', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4190-MFLUW', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2150-WLKUW', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6171-ZTVYB', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7590-VHVEG', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5186-EJEGL', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5550-VFRLC', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1178-PZGAB', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0196-JTUQI', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4299-SIMNS', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0859-YGKFW', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4753-PADAS', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3638-DIMPH', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6715-OFDBP', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0177-PXBAT', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1221-GHZEP', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8809-XKHMD', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9367-WXLCH', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1976-CFOCS', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2270-CHBFN', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2085-BOJKI', 'No')

INSERT INTO target_info ( customerID, Churn ) VALUES  ('6786-OBWQR', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2990-OGYTD', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5875-YPQFJ', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2984-MIIZL', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6653-CBBOM', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2484-DGXPZ', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7587-RZNME', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3855-ONCAR', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2105-PHWON', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4534-WGCIR', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8815-LMFLX', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8443-ZRDBZ', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1591-MQJTP', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1559-DTODC', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4566-QVRRW', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5092-STPKP', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3094-JOJAI', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5650-VDUDS', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3096-IZETN', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3254-YRILK', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7813-ZGGAW', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5756-OZRIO', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1016-DJTSV', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5204-HMGYF', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3669-LVWZB', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2577-GVSIL', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1444-VVSGW', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5419-JPRRN', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4673-KKSLS', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4441-NIHPT', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3315-IKYZQ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4726-DLWQN', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2682-KEVRP', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4730-AWNAU', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8564-LDKFL', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3097-IDVPU', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5729-KLZAR', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6352-TWCAU', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8263-OKETD', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6698-OXETB', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4537-CIBHB', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3230-JCNZS', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0264-CNITK', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1043-UXOVO', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3410-YOQBQ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8375-DKEBR', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4508-OEBEY', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0151-ONTOV', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5884-GCYMI', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4355-HBJHH', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9699-UBQFS', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7658-UYUQS', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4220-TINQT', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7115-IRDHS', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3283-WCWXT', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1709-EJDOX', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7244-KXYZN', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9762-YAQAA', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2799-TSLAG', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0235-KGSLC', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9741-YLNTD', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3791-LGQCY', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5829-NVSQN', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6551-VLJMV', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1866-ZSLJM', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0885-HMGPY', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5656-JAMLX', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7245-JMTTQ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2446-ZKVAF', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6599-CEBNN', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5998-DZLYR', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4223-WOZCM', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4992-LTJNE', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8008-ESFLK', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5760-FXFVO', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3569-EDBPQ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3500-NSDOA', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8571-ZCMCX', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6686-YPGHK', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7168-HDQHG', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0310-VQXAM', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3096-WPXBT', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2234-EOFPT', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6461-PPAXN', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2809-ILCYT', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4958-XCBDQ', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5989-OMNJE', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1043-YCUTE', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7402-EYFXX', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1813-JYWTO', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7032-LMBHI', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9191-MYQKX', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1196-AMORA', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0565-IYCGT', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8148-WOCMK', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4776-XSKYQ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3935-TBRZZ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9114-DPSIA', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3143-ILDAL', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1952-DVVSW', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3871-IKPYH', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3209-ZPKFI', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4625-LAMOB', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9837-BMCLM', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4080-OGPJL', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0787-LHDYT', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3071-MVJCD', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7825-GKXMW', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6726-NNFWD', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5820-PTRYM', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7785-RDVIG', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0774-IFUVM', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2054-PJOCK', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7789-HKSBS', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6629-LADHQ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1385-TQOZW', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1452-VOQCH', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0298-XACET', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7028-DVOIQ', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5616-PRTNT', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3733-LSYCE', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9432-VOFYX', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6032-KRXXO', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1393-IMKZG', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0195-IESCP', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7562-UXTPG', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2656-TABEH', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2055-PDADH', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2890-WFBHU', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6166-ILMNY', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6551-GNYDG', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2672-DZUOY', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7142-HVGBG', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4546-FOKWR', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6313-GIDIT', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4430-YHXGG', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5146-CBVOE', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9619-GSATL', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8808-ELEHO', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9644-UMGQA', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8853-TZDGH', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3999-WRNGR', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2923-ARZLG', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0871-OPBXW', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9691-HKOVS', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1427-VERSM', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1298-PHBTI', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4662-EKDPQ', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9586-JGQKH', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6261-RCVNS', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6946-LMSQS', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2075-RMJIK', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3258-ZKPAI', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9369-XFEHK', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3536-IQCTX', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8752-IMQOS', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9850-OWRHQ', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0196-VULGZ', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5748-RNCJT', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0928-XUTSN', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7611-YKYTC', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0916-KNFAJ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2045-BMBTJ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0471-LVHGK', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1950-KSVVJ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1568-BEKZM', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3400-ESFUW', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9746-YKGXB', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6338-AVWCY', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4817-VYYWS', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7136-RVDTZ', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5141-ZUVBH', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8779-YIQQA', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4877-TSOFF', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0303-UNCIP', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6485-QXWWE', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6618-RYATB', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7872-RDDLZ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9199-PWQVC', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6992-TKNYO', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0214-JHPFW', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9313-CDOGY', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6637-KYRCV', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3521-MNKLV', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4652-NNHNY', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5472-CVMDX', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8384-FZBJK', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2519-LBNQL', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2065-MMKGR', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0002-ORFBO', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2961-VNFKL', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6038-GCYEC', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0067-DKWBL', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2804-ETQDK', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0895-DQHEW', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9239-GZHZE', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1241-FPMOF', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6283-GITPX', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6689-TCZHQ', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4825-FUREZ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4959-JOSRX', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1428-GTBJJ', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9170-GYZJC', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8690-ZVLCL', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5889-JTMUL', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4307-KTUMW', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5949-XIKAE', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5802-ADBRC', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4366-CTOUZ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1849-RJYIG', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6713-OKOMC', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8450-LUGUK', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9782-LGXMC', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1049-FYSYG', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5442-PPTJY', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0320-JDNQG', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6614-YOLAC', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8722-PRFDV', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7030-NJVDP', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0607-MVMGC', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2541-YGPKE', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9692-TUSXH', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4922-CVPDX', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1750-CSKKM', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1728-BQDMA', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7521-AFHAB', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5868-YWPDW', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1320-REHCS', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1023-BQXZE', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5832-TRLPB', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3967-VQOGC', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9661-ACXBS', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5602-BVFMK', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4323-SADQS', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1539-LNKHM', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7470-MCQTK', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5136-RGMZO', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6543-CPZMK', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9639-BUJXT', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7856-GANIL', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4415-WNGVR', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3481-JHUZH', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0278-YXOOG', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5227-JSCFE', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2091-GPPIQ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9643-YBLUR', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9419-IPPBE', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2877-VDUER', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2924-KHUVI', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0439-IFYUN', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2587-EKXTS', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6661-EIPZC', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5756-JYOJT', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3259-FDWOY', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1480-IVEVR', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8070-AAWZP', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2001-EWBQU', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2606-RMDHZ', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5688-KZTSN', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5956-YHHRX', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6563-VRERX', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7243-LCGGZ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3777-XROBG', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5081-NWSUP', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5442-BXVND', 'No')

INSERT INTO target_info ( customerID, Churn ) VALUES  ('8718-PTMEZ', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7711-GQBZC', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8722-NGNBH', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2432-TFSMK', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1472-TNCWL', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0014-BMAQU', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2724-FJDYW', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4693-VWVBO', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0301-KOBTQ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7044-YAACC', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8290-YWKHZ', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5908-QMGOE', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4795-KTRTH', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5057-RKGLH', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6341-JVQGF', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4065-JJAVA', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2018-QKYGT', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7379-FNIUJ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1970-KKFWL', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7311-MQJCH', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5896-NPFWW', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8791-GFXLZ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4979-HPRFL', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6181-AXXYF', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7908-QCBCA', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6877-TJMBR', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0975-UYDTX', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4581-LNWUM', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4957-TIALW', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4989-LIXVT', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0886-QGENL', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2799-ARNLO', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3027-YNWZU', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9578-VRMNM', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8943-URTMR', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7963-SHNDT', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8007-YYPWD', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4567-AKPIA', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6927-WTFIV', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5914-GXMDA', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7767-UXAGJ', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4827-DPADN', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5788-YPOEG', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7242-EDTYC', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1676-MQAOA', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5168-MSWXT', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1976-AZZPJ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8711-LOBKY', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9057-SIHCH', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5229-DTFYB', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6370-ZVHDV', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4818-DRBQT', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2230-XTUWL', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1066-JKSGK', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1852-QSWCD', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6625-FLENO', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1766-GKNMI', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6502-HCJTI', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2323-ARSVR', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3164-AALRN', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6064-ZATLR', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2636-OHFMN', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7096-UCLNH', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3097-PYWXL', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4719-UMSIY', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6917-IAYHD', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0112-QWPNC', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5208-HFSBT', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6473-ULUHT', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2080-SRCDE', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7504-UWHNB', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5062-CJJKH', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2272-WUSPA', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0380-ZCSBI', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6250-CGGUN', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9661-MHUMO', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5176-OLSKT', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5172-MIGPM', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6671-NGWON', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8169-SAEJD', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3585-ISXZP', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2108-GLPQB', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6029-WTIPC', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0247-SLUJI', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4116-IQRFR', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2309-OSFEU', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0458-HEUZG', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7285-KLOTR', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1241-EZFMJ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6196-HBOBZ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4872-VXRIL', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6194-HBGQN', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5681-LLOEI', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1536-HBSWP', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0988-JRWWP', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3665-JATSN', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1833-TCXKK', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0324-BRPCJ', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2002-MZHWP', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4821-SJHJV', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9581-GVBXT', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5242-UOWHD', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6892-XPFPU', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1187-WILMM', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4109-CYRBD', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0913-XWSCN', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8837-VVWLQ', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6345-HOVES', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3244-DCJWY', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8735-DCXNF', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5676-CFLYY', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8217-QYOHV', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2486-WYVVE', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2024-BASKD', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5366-IJEQJ', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6131-IUNXN', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3520-FJGCV', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1734-ZMNTZ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4228-ZGYUW', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9601-BRXPO', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4584-LBNMK', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8495-LJDFO', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7976-CICYS', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3374-PZLXD', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5696-JVVQY', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2203-GHNWN', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9489-UTFKA', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4129-LYCOI', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2257-BOVXD', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5143-EGQFK', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9833-TGFHX', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8387-UGUSU', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5365-LLFYV', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9408-HRXRK', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1565-RHDJD', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1150-WFARN', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5995-OIGLP', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0407-BDJKB', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2947-DOMLJ', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8309-IEYJD', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3900-AQPHZ', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4544-RXFMG', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1624-NALOJ', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1447-GIQMR', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2346-LOCWC', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5172-RKOCB', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2808-CHTDM', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1010-DIAUQ', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8242-PDSGJ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5520-FVEWJ', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0958-YHXGP', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2135-RXIHG', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6981-TDRFT', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5751-USDBL', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8457-XIGKN', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0111-KLBQG', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2676-ISHSF', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0436-TWFFZ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4902-OHLSK', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2560-QTSBS', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3902-FOIGH', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1352-VHKAJ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1741-WTPON', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2382-BCKQJ', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7950-XWOVN', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0191-ZHSKZ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0362-RAOQO', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4282-ACRXS', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8799-OXZMD', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9223-UCPVT', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1600-DILPE', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0810-BDHAW', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5334-AFQJB', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0641-EVBOJ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8015-IHCGW', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8746-OQQRW', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3370-HXOPH', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2722-JMONI', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0475-RIJEP', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8111-BKVDS', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0224-RLWWD', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6508-NJYRO', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3411-WLRSQ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8316-BBQAY', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2150-OEGBV', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3551-HUAZH', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8884-FEEWR', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5968-VXZLG', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3070-BDOQC', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2821-WARNZ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2108-XWMPY', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8194-PEEBY', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1832-PEUTS', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2685-SREOM', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2657-VPXTA', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5067-WJEUN', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2205-YMZZJ', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4277-UDIEF', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1480-BKXGA', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4648-YPBTM', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3097-NQYSN', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9250-WYPLL', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5245-VDBUR', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8468-FZTOE', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7639-OPLNG', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8631-XVRZL', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1051-GEJLJ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5753-QQWPW', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9339-FIIJL', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8644-XYTSV', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6688-UZPWD', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1534-OULXE', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3902-MIVLE', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4237-RLAQD', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1208-DNHLN', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0704-VCUMB', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2550-QHZGP', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7817-OMJNA', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2811-POVEX', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9940-HPQPG', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2012-NWRPA', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5176-LDKUH', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0281-CNTZX', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3440-JPSCL', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7284-BUYEC', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4178-EGMON', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2373-NTKOD', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4538-WNTMJ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1345-GKDZZ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8883-ANODQ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1488-SYSFC', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5876-QMYLD', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3908-BLSYF', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4317-VTEOA', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3422-GALYP', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5461-QKNTN', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9975-GPKZU', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2284-VFLKH', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8945-MUQUF', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5149-CUZUJ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9614-RMGHA', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5076-YVXCM', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5088-QZLRL', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5054-IEXZT', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3594-BDSOA', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3034-ZBEQN', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7903-CMPEY', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8654-DHAOW', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2039-JONDJ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7623-TRNQN', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8821-KVZKQ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1596-BBVTG', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4702-HDRKD', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1501-SGHBW', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0422-OHQHQ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2866-IKBTM', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5201-CBWYG', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2642-MAWLJ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1240-KNSEZ', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5286-YHCVC', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8469-SNFFH', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9732-KPKBW', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9357-UJRUN', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0022-TCJCI', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2829-HYVZP', 'No')

INSERT INTO target_info ( customerID, Churn ) VALUES  ('8329-UTMVM', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8715-KKTFG', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6646-VRFOL', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0877-SDMBN', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1891-QRQSA', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6543-XRMYR', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6340-DACFT', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6807-SIWJI', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7730-CLDSV', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8111-SLLHI', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0096-FCPUF', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1597-LHYNC', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8132-YPVBX', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1120-BMWUB', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0743-HRVFF', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9254-RBFON', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6372-RFVNS', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3635-QQRQD', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6253-WRFHY', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7690-KPNCU', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7398-LXGYX', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0771-WLCLA', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9578-FOMUK', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7665-NKLAV', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9725-SCPZG', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3509-GWQGF', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7114-AEOZE', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5095-AESKG', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0112-QAWRZ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5485-ITNPC', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9821-BESNZ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3705-PSNGL', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5099-BAILX', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3996-ZNWYK', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2833-SLKDQ', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3422-LYEPQ', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4612-SSVHJ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9906-NHHVC', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3011-WQKSZ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9824-QCJPK', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7317-GGVPB', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7932-WPTDS', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7112-OPOTK', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7688-AWMDX', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8474-UMLNT', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1627-AFWVJ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4931-TRZWN', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7771-ZONAT', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6861-XWTWQ', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1171-TYKUR', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0142-GVYSN', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2931-FSOHN', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9526-JAWYF', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2410-CIYFZ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5261-QSHQM', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9541-PWTWO', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1389-CXMLU', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8920-NAVAY', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2225-ZRGSG', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5678-VFNEQ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4115-UMJFQ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3506-OVLKD', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2019-HDCZY', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6048-UWKAL', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6234-RAAPL', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1910-FMXJM', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2616-UUTFK', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8751-EDEKA', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3721-WKIIL', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8985-OOPOS', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3511-BFTJW', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3134-DSHVC', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0603-OLQDC', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8612-GXIDD', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0907-HQNTS', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7754-IXRMC', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5626-MGTUK', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4836-WNFNO', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6034-YMTOB', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1696-MZVAU', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6907-FLBER', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6586-PSJOX', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5296-PSYVW', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6122-EFVKN', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4097-YODCF', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0872-NXJYS', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3146-MSEGF', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1045-LTCYT', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0661-KQHNK', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6711-VTNRE', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4312-KFRXN', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0587-DMGBH', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6725-TPKJO', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8630-FJLIB', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0089-IIQKO', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4742-DRORA', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8779-QRDMV', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7047-YXDMZ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6901-GOGZG', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0654-PQKDW', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1226-JZNKR', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5666-MBJPT', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9867-JCZSP', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1699-UOTXU', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4946-EDSEW', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1796-JANOW', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5519-YLDGW', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3086-RUCRN', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7469-LKBCI', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3569-VLDHH', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2933-XEUJM', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5504-WSIUR', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6585-WCEWR', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4146-SVFUD', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5701-SVCWR', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4822-RVYBB', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8805-JNRAZ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3308-MHOOC', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4378-BZYFP', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9830-ECLEN', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1498-NHTLT', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1513-XNPPH', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4398-HSCJH', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7595-EHCDL', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5215-LNLDJ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7677-SJJJK', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9992-RRAMN', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6242-FEGFD', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3956-CJUST', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4844-JJWUY', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3703-TTEPD', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4282-YMKNA', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6103-QCKFX', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4631-OACRM', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3470-OBUET', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2929-QNSRW', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7853-OETYL', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5318-YKDPV', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4238-HFHSN', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9209-NWPGU', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5022-JNQEQ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6007-TCTST', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8357-EQXFO', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3589-PPVKW', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1574-DYCWE', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4999-IEZLT', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4403-BWPAY', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1494-EJZDW', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9766-HGEDE', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4724-WXVWF', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5469-NUJUR', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1724-IQWNM', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8043-PNYSD', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6734-FQAJX', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9786-YWNHU', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8760-ZRHKE', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2703-AMTUL', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4583-PARNH', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6942-LBFDP', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7203-OYKCT', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9143-CANJF', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1723-HKXJQ', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6619-RPLQZ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4791-QRGMF', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6728-VOIFY', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2081-KJSQF', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3397-AVTKU', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6365-HITVU', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2604-XVDAM', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0487-VVUVK', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6656-GULJQ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6599-SFQVE', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6754-WKSHP', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6199-IWKGC', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6221-AVQYL', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5630-IXDXV', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7340-KEFQE', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5542-NKVRU', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4553-DVPZG', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1925-GMVBW', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9822-BIIGN', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9172-ANCRX', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4695-VADHF', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3930-ZGWVE', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1084-MNSMJ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3733-UOCWF', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8242-JSVBO', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3804-RVTGV', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3904-UKFRE', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7248-VZQLC', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0257-KXZGU', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2737-WFVYW', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5649-TJHOV', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4324-BZCKL', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5494-HECPR', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1396-QWFBJ', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0547-HURJB', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7239-HZZCX', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4698-KVLLG', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0319-QZTCO', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4056-QHXHZ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0415-MOSGF', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6432-TWQLB', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1069-XAIEM', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1767-CJKBA', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9068-VPWQQ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8818-XYFCQ', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8747-UDCOI', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9825-YCXWZ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2114-MGINA', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2074-GKOWZ', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2282-YGNOR', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8229-MYEJZ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4883-QICIH', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9788-YTFGE', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3429-IFLEM', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7649-PHJVR', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0816-TSPHQ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8267-KFGYD', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9801-NOSHQ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7182-OVLBJ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4059-IIEBK', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9258-CNWAC', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5318-IXUZF', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8039-ACLPL', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4817-KEQSP', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9391-EOYLI', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7963-GQRMY', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2227-JRSJX', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3981-QSVQI', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8076-FEZKJ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6304-IJFSQ', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2834-SPCJV', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1231-YNDEK', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1866-NXPSP', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9548-LIGTA', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7064-JHXCE', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2388-LAESQ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6300-BWMJX', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4486-EFAEB', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3161-GETRM', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9828-AOQLM', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2433-KMEAS', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7014-ZZXAW', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4554-YGZIH', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6969-MVBAI', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6376-GAHQE', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9430-NKQLY', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4009-ALQFH', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0023-HGHWL', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1686-STUHN', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3588-WSTTJ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2538-OIMXF', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3806-YAZOV', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9127-QRZMH', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7607-QKKTJ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8665-UTDHZ', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7398-HPYZQ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4647-MUZON', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6856-RAURS', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7250-EQKIY', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8709-KRDVL', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6701-YVNQG', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2639-UGMAZ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2983-ZANRP', 'Yes')

INSERT INTO target_info ( customerID, Churn ) VALUES  ('1702-CCFNJ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0991-BRRFB', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5575-TPIZQ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2075-PUEPR', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0506-LVNGN', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4140-MUHUG', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7968-QUXNS', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9530-GRMJG', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2123-VSCOT', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9411-TPQQV', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3973-SKMLN', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9696-RMYBA', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8734-DKSTZ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5336-UFNZP', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6180-YBIQI', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1406-PUQVY', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5016-LIPDW', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6418-PIQSP', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3280-MRDOF', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3016-KSVCP', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2908-WGAXL', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6968-MHOMU', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2851-STERV', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8466-PZBLH', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2126-GSEGL', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7508-KBIMB', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5575-GNVDE', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2674-MLXMN', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6630-UJZMY', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1871-MOWRM', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3426-NIYYL', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5512-IDZEI', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2408-PSJVE', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3352-ALMCK', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9221-OTIVJ', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0993-OSGPT', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6603-YRDCJ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4709-LKHYG', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3758-CKOQL', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5201-FRKKS', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5044-LRQAQ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6557-BZXLQ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8608-OZTLB', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1436-ZMJAN', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6345-FZOQH', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6008-NAIXK', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9677-AVKED', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5515-IDEJJ', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8591-NXRCV', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7328-OWMOM', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4716-HHKQH', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9862-KJTYK', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5120-ZBLAI', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2595-KIWPV', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1725-IQNIY', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3951-NJCVI', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1423-BMPBQ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9837-FWLCH', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3190-XFANI', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8725-JEDFD', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0164-XAIRP', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5174-ITUMV', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6519-CFDBX', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9637-CDTKZ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3692-JHONH', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6347-DCUIK', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0336-PIKEI', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4013-UBXWQ', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8606-CIQUL', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3404-JNXAX', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2665-NPTGL', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9278-VZKCD', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9620-QJREV', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0827-ITJPH', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0137-UDEUO', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3878-AVSOQ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1271-SJBGZ', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0619-OLYUR', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7531-GQHME', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5178-LMXOP', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2364-UFROM', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3570-YUEKJ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9048-JVYVF', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4154-AQUGT', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2612-RANWT', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3768-NLUBH', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9606-PBKBQ', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3442-ZHHCC', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5726-CVNYA', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7839-QRKXN', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5296-BFCYD', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1960-UYCNN', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0928-JMXNP', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6185-TASNN', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4750-ZRXIU', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3274-NSDWE', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5887-IKKYO', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3439-GVUSX', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8224-DWCKX', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0266-GMEAO', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9681-OXGVC', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2466-FCCPT', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9046-JBFWA', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2455-USLMV', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0326-VDYXE', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6332-FBZRI', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9631-XEYKE', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4786-UKSNZ', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9931-DCEZH', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4962-CHQPW', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1602-IJQQE', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4717-GHADL', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2522-WLNSF', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9742-XOKTS', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9958-MEKUC', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2265-CYWIV', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2123-AGEEN', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2750-BJLSB', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9496-IVVRP', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9412-GHEEC', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2474-BRUCM', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8510-BBWMU', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5899-OUVKV', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6134-KWTBV', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4488-KQFDT', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3884-UEBXB', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8735-SDUFN', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8046-DNVTL', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5276-KQWHG', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5090-EMGTC', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5543-QDCRY', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5248-YGIJN', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8597-CTXVJ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9668-PUGNU', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2519-FAKOD', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4325-NFSKC', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7379-POKDZ', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1548-ARAGG', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5175-AOBHI', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9512-UIBFX', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5313-FPXWG', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5889-LFOLL', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2789-HQBOU', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0875-CABNR', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0487-RPVUM', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1680-VDCWW', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4139-SUGLD', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4661-NJEUX', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4079-WWQQQ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1236-WFCDV', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6330-JKLPC', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1004-NOZNR', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5650-YLIBA', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0690-SRQID', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3179-GBRWV', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8966-OIQHG', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1084-UQCHV', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6507-ZJSUR', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6114-TCFID', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7025-WCBNE', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9052-VKDUW', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5999-LCXAO', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0277-BKSQP', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5593-SUAOO', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9965-YOKZB', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9026-RNUJS', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8922-LIEGH', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6993-OHLXR', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7762-ONLJY', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7216-KAOID', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9873-MNDKV', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3565-UNOCC', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7061-OVMIM', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0675-NCDYU', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5740-YHGTW', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9881-VCZEP', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8901-HJXTF', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1563-IWQEX', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2886-KEFUM', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6845-RGTYS', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0742-LAFQK', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5366-OBVMR', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0310-SUCIN', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9787-XVQIU', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6752-APNJL', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3427-GGZZI', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2984-TBYKU', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2368-GAKKQ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4295-YURET', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8671-KKKOS', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7017-VFULY', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6519-ZHPXP', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3865-ZYKAD', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2654-VBVPB', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6532-YLWSI', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4716-MRVEN', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4950-BDEUX', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4123-DVHPH', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1169-WCVAK', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3642-GKTCT', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5515-RUGKN', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6481-ESCNL', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2419-FSORS', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0107-YHINA', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8160-HOWOX', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3890-RTCMS', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3787-TRIAL', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2187-LZGPL', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9134-CEQMF', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4377-VDHYI', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9053-JZFKV', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8849-PRIQJ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7901-IIDQV', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8246-SHFGA', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2843-CQMEG', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6635-CPNUN', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4083-BFNYK', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2321-OMBXY', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7493-TPUWZ', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8809-RIHDD', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0302-JOIVN', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4462-CYWMH', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7964-ZRKKG', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4054-CUMIA', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5173-WXOQV', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5199-FPUSP', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9964-WBQDJ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3530-CRZSB', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6047-YHPVI', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2074-GUHPQ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5993-BQHEA', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2144-BFDSO', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5382-TEMLV', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2208-UGTGR', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0604-THJFP', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8603-IJWDN', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6457-USBER', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9350-VLHMB', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7338-ERIVA', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8670-MEFCP', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3913-FCUUW', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2632-UCGVD', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5624-RYAMH', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3118-UHVVQ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6258-NGCNG', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3717-OFRTN', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9462-MJUAW', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8149-AIQCG', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2351-RRBUE', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3108-PCCGG', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4433-JCGCG', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1131-SUEKT', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1964-SVLEA', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7486-KSRVI', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2236-HILPA', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2253-KPMNB', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3090-LETTY', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6259-WJQLC', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5923-GXUOC', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9938-TKDGL', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2157-MXBJS', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3668-QPYBK', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3521-HTQTV', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7408-OFWXJ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5074-FBGHB', 'No')

INSERT INTO target_info ( customerID, Churn ) VALUES  ('4198-VFOEA', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2450-ZKEED', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7074-STDCN', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1842-EZJMK', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0168-XZKBB', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2664-XJZNO', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3643-AHCFP', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9207-ZPANB', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5322-ZSMZY', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3066-RRJIO', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2469-DTSGX', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5061-PBXFW', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7128-GGCNO', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3597-MVHJT', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4302-ZYFEL', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1273-MTETI', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6986-IXNDM', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2277-AXSDC', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6729-FZWSY', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1156-ZFYDO', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9386-LDCZR', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3623-FQBOX', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5948-UJZLF', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9928-BZVLZ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7746-AWNQW', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2107-FBPTK', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1965-DDBWU', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6302-JGYRJ', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6502-KUGLL', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9866-OCCKE', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9173-IVZVP', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3893-JRNFS', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4137-JOPHL', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4323-OHFOW', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1972-XMUWV', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1915-IOFGU', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7982-VCELR', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0699-NDKJM', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4633-MKHYU', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9269-CQOOL', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2995-YWTCD', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5989-AXPUC', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1771-OADNZ', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2739-CACDQ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8029-XYPWT', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3801-HMYNL', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6898-RBTLU', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4822-NGOCH', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1116-DXXDF', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1306-RPWXZ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5934-RMPOV', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6897-RWMUB', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7893-IXHRQ', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1875-QIVME', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4291-YZODP', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1635-NZATJ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9847-HNVGP', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3519-ZKXGG', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8092-NLTGF', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1371-WEPDS', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8317-BVKSO', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2692-AQCPF', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0434-CSFON', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2120-SMPEX', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3295-YVUSR', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4785-QRJHC', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5793-YOLJN', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1656-DRSMG', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9073-ZZIAY', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0447-BEMNG', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0365-GXEZS', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6339-TBELP', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9470-XCCEM', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8224-IVVPA', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1568-LJSZU', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9770-LXDBK', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5006-MXVRN', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0440-UEDAI', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0431-APWVY', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5399-ZIMKF', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2428-ZMCTB', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0121-SNYRK', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8456-QDAVC', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4644-PIZRT', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4827-USJHP', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6621-NRZAK', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0744-BIKKF', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1455-HFBXA', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7328-ZJAJO', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6440-DKQGE', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3452-GWUIN', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9746-MDMBK', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9388-ZEYVT', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3474-BAFSJ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9102-OXKFY', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7517-LDMPS', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6968-URWQU', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8060-HIWJJ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4020-KIUDI', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1363-TXLSL', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7527-QNRUS', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8651-ENBZX', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3892-NXAZG', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8740-XLHDR', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1163-VIPRI', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6218-KNUBD', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8640-SDGKB', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2249-YPRNG', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4785-FCIFB', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3419-SNJJD', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2121-JAFOM', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3389-YGYAI', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9033-EOXWV', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6179-GJPSO', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9667-EQRXU', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7824-PANSQ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2361-UPSND', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9360-OMDZZ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7614-QVWQL', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0644-OQMDK', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8865-TNMNX', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1114-CENIM', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3933-DQPWX', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7716-YTYHG', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7927-AUXBZ', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5630-AHZIL', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2320-JRSDE', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9013-AQORL', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3301-LSLWQ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6734-CKRSM', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7228-PAQPD', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5628-RKIFK', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5346-BZCHP', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0739-UUAJR', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9795-SHUHB', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9391-LMANN', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8519-IMDHU', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0621-JFHOL', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4011-ARPHK', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6384-VMJHP', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4338-EYCER', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4074-SJFFA', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6504-VBLFL', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3457-PQBYH', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4505-EXZHB', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1429-UYJSV', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4654-GGUII', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4029-HPFVY', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4547-FZJWE', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7341-LXCAF', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2408-WITXK', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2988-GBIVW', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2589-AYCRP', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7684-XSZIY', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7632-MNYOY', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2720-WGKHP', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1121-QSIVB', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4597-ELFTS', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5600-PDUJF', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3452-FLHYD', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7435-ZNUYY', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3926-CUQZX', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9651-GTSAQ', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1113-IUJYX', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3745-HRPHI', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8375-KVTHK', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9972-NKTFD', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4592-IWTJI', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9058-MJLZC', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9026-LHEVG', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4623-ZKHLY', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8677-HDZEE', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3470-BTGQO', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3372-KWFBM', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6024-RUGGH', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8950-MTZNV', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6088-BXMRG', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6124-ACRHJ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9467-ROOLM', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9798-DRYDS', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2037-XJFUP', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3059-NGMXB', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6115-ZTBFQ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7975-TZMLR', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2359-QWQUL', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5955-EPOAZ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2907-ILJBN', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4619-EVPHY', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5339-TJFEK', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1334-FJSVR', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7758-UJWYS', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1785-BPHTP', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3941-XTSKM', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9381-NDKME', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2101-RANCD', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2362-IBOOY', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0733-VUNUW', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4923-ADWXJ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1403-LKLIK', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9885-CSMWE', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5804-LEPIM', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7641-TQFHN', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4701-AHWMW', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2824-DXNKN', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3487-EARAT', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2141-RRYGO', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3834-XUIFC', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7647-GYYKX', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4077-CROMM', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4667-QONEA', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0374-AACSZ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5397-TUPSH', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5777-ZPQNC', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9242-TKFSV', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2320-YKQBO', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1394-SUIUH', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0187-QSXOE', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9817-APLHW', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0440-EKDCF', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6231-WFGFH', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2041-JIJCI', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5159-YFPKQ', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2446-PLQVO', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7136-IHZJA', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2049-BAFNW', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7319-ZNRTR', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2676-OXPPQ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8728-SKJLR', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8344-WFMFH', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4988-IQIGL', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6202-DYYFX', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1024-KPRBB', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3934-HXCFZ', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2661-GKBTK', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5499-ECUTN', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0244-LGNFY', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5804-HYIEZ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9617-INGJY', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4952-YSOGZ', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8584-KMVXD', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3726-TBHQT', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4529-CKBCL', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3280-NMUVX', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0585-EGDDA', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2243-FNMMI', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1818-ESQMW', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6874-SGLHU', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8990-ZXLSU', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7398-SKNQZ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3823-KYNQY', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6885-PKOAM', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3812-LRZIR', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9362-MWODR', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0946-FKYTX', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8174-TBVCF', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0734-OXWBT', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3682-YEUWS', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4541-RMRLG', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0898-XCGTF', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5309-TAIKL', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4815-YOSUK', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5996-DAOQL', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1582-RAFML', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8258-GSTJK', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0071-NDAFP', 'No')

INSERT INTO target_info ( customerID, Churn ) VALUES  ('1013-QCWAM', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4043-MKDTV', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3211-ILJTT', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4208-UFFGW', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1810-BOHSY', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1047-NNCBF', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5945-AZYHT', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2659-VXMWZ', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5564-NEMQO', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4301-VVZKA', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9220-ZNKJI', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4431-EDMIQ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8100-HZZLJ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4351-QLCSU', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4815-GBTCD', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5135-GRQJV', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8133-ANHHJ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3927-NLNRY', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4611-ANLQC', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1265-XTECC', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3259-KNMRR', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5445-UTODQ', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6569-KTMDU', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2969-WGHQO', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2560-WBWXF', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6849-OYAMU', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3420-YJLQT', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0266-CLZKZ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5196-WPYOW', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9609-BENEA', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6465-GSRCL', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7321-PKUYW', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7622-FWGEW', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5133-VRSAB', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4883-KCPZJ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5003-XZWWO', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8741-LQOBK', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6408-OTUBZ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0430-IHCDJ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7011-CVEUC', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5871-DGTXZ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1907-YLNYW', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9575-IWCAZ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2637-FKFSY', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1357-MVDOZ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1379-FRVEB', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0634-SZPQA', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9214-EKVXR', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6967-PEJLL', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5457-COLHT', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8766-PAFNE', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5590-ZSKRV', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6505-OZNPG', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5641-DMBFJ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9831-BPFRI', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2322-VCZHZ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1764-VUUMT', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6418-HNFED', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6437-UKHMV', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1272-ILHFG', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1591-NFNLQ', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7234-KMNRQ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1310-QRITU', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8178-EYZUO', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1400-MMYXY', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9953-ZMKSM', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1527-SXDPN', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1703-MGIAB', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7156-MXBJE', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8232-UTFOZ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3486-HOOGQ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7356-AYNJP', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6685-XSHHU', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5590-YRFJT', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6265-SXWBU', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6891-JPYFF', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6656-JWRQX', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7743-EXURX', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6127-IYJOZ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2576-HXMPA', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8022-BECSI', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0786-VSSUD', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9924-JPRMC', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9314-QDMDW', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5339-PXDVH', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2017-CCBLH', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5020-ZSTTY', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5930-GBIWP', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6961-VCPMC', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0254-WWRKD', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5248-KWLAR', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1302-UHBDD', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9158-VCTQB', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7273-TEFQD', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6537-OTKMY', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6298-QDFNH', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8854-CCVSQ', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9734-YWGEX', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9040-KZVWO', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0308-GIQJT', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0307-BCOPK', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3219-JQRSL', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1839-UMACK', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5014-WUQMG', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0420-TXVSG', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6633-MPWBS', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8650-RHRKE', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4530-NDRKU', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9955-QOPOY', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3680-CTHUH', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5961-VUSRV', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1589-AGTLK', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7055-VKGDA', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1641-BYBTK', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5919-VCZYM', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0716-BQNDX', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8838-GPHZP', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5274-XHAKY', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8929-KSWIH', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6916-HIJSE', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2228-BZDEE', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1346-PJWTK', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1561-BWHIN', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2882-DDZPG', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9648-BCHKM', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1930-QPBVZ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5299-RULOA', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1626-ERCMM', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8019-ENHXU', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7795-CFOCW', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0906-QVPMS', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4118-CEVPF', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5968-XQIVE', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9305-CDSKC', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3521-SYVOR', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5149-TGWDZ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1265-BCFEO', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6873-UDNLD', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7143-BQIBA', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4526-ZJJTM', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7576-ASEJU', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9190-MFJLN', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6242-MBHPK', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1400-WIVLL', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3489-HHPFY', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7560-QJAVJ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3722-WPXTK', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0748-RDGGM', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6719-FGEDO', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5130-IEKQT', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4391-RESHN', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7941-RCJOW', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1760-CAZHT', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2774-LVQUS', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6128-AQBMT', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0674-EYYZV', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1661-CZBAU', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5949-EBSQK', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8573-JGCZW', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6661-HBGWL', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7989-AWGEH', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4703-MQYKT', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6993-YCOBK', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5356-KZCKT', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5124-EOGYE', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4455-BFSPD', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4423-JWZJN', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4891-NLUBA', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3200-MNQTF', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1073-XXCZD', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3556-BVQGL', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6416-YJTTB', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0017-IUDMW', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9297-FVVDH', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1282-IHQAC', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1936-UAFEH', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8937-RDTHP', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8627-ZYGSZ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7459-RRWQZ', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1085-LDWAM', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3656-TKRVZ', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4760-XOHVN', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4622-YNKIJ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1172-VIYBP', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6729-GDNGC', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9497-QCMMS', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3587-PMCOY', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3043-SUDUA', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7901-TBKJX', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0825-CPPQH', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2398-YPMUR', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8006-PYCSW', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3853-LYGAM', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5493-SDRDQ', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1335-HQMKX', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2812-ENYMO', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0568-ONFPC', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6023-YEBUP', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6103-BOCOU', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2581-VKIRT', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4353-HYOJD', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4188-FRABG', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4855-SNKMY', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5995-WWKKG', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0311-QYWSS', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3583-KRKMD', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5828-AVIPD', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8311-UEUAB', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8910-LEDAG', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7639-SUPCW', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0750-EBAIU', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9200-NLNPD', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1658-BYGOY', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4913-EHYUI', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8266-VBFQL', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1229-RCALF', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6754-LZUKA', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7005-CYUIL', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5832-XKAES', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8979-CAMGB', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1216-BGTSP', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9229-RQABD', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3727-OVPRY', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3891-NLXJB', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8219-VYBVI', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4822-YCXMX', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0428-IKYCP', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3146-JTQHR', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7813-TKCVO', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1465-LNTLJ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3126-WQMGH', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8777-MBMTS', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4706-DGAHW', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4192-GORJT', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2057-BOYKM', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7566-DSRLQ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5447-WZAFP', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1228-ZLNBX', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9844-FELAJ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5136-KCKGI', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6825-UYPFK', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1716-LSAMB', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8008-OTEZX', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4488-PSYCG', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5855-EIBDE', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4667-OHGKG', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0909-SELIE', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8395-ETZKQ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2465-BLLEU', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5110-CHOPY', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3088-FVYWK', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2357-COQEK', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7538-GWHML', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9605-WGJVW', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4547-LYTDD', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0464-WJTKO', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0314-TKOSI', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2081-VEYEH', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5131-PONJI', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8280-MQRQN', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2267-FPIMA', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0282-NVSJS', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5389-FFVKB', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9625-QNLUX', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4013-GUXND', 'No')

INSERT INTO target_info ( customerID, Churn ) VALUES  ('0794-YVSGE', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9494-MRNYX', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7267-FRMJW', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1987-AUELQ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6286-ZHAOK', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7508-MYBOG', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6388-TABGU', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0420-BWTPW', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8058-DMYRU', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5734-EJKXG', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4111-BNXIF', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8050-DVOJX', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7975-JMZNT', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3384-CTMSF', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2782-JEEBU', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5649-RXQTV', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4824-GUCBY', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6394-HHHZM', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9405-GPBBG', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3896-RCYYE', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8774-GSBUN', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5338-YHWYT', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4750-UKWJK', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1866-RZZQS', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2360-RDGRO', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3079-BCHLN', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3943-KDREE', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2691-NZETQ', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5394-MEITZ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4826-XTSOH', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3249-VHRIP', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2079-FBMZK', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9770-KXGQU', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3522-CDKHF', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8199-ZLLSA', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7083-YNSKY', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5533-RJFTJ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6214-EDAKZ', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8984-EYLLL', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3744-ZRRDZ', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2454-RPBRZ', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4760-THGOT', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7073-QETQY', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5980-NOPLP', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4933-IKULF', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4749-VFKVB', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8276-MQBYC', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4083-EUGRJ', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9518-RWHZL', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9552-TGUZV', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8647-SDTWQ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4560-WQAQW', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4942-VZZOM', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9629-NHXFW', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2226-ICFDO', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2867-UIMSS', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6814-ZPWFQ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4471-KXAUH', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3090-QFUVD', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6766-HFKLA', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7048-GXDAY', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9495-REDIY', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7471-MQPOS', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5651-CPDND', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7586-ZATGZ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5220-AGAAX', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6248-BSHKG', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2885-HIJDH', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6635-MYYYZ', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3669-OYSJI', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9617-UDPEU', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8465-SBRXP', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0925-VYDLG', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3091-FYHKI', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7025-IWFHT', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1848-LBZHY', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0862-PRCBS', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0295-QVKPB', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3058-HJCUY', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7107-UBYKY', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9866-QEVEE', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5736-YEJAX', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1506-YJTYT', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9993-LHIEB', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9500-IWPXQ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3737-XBQDD', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4704-ERYFC', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7997-EASSD', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5378-IKEEG', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8313-NDOIA', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2237-ZFSMY', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4184-VODJZ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2103-ZRXFN', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4310-KEDTB', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8190-ZTQFB', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3125-RAHBV', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5198-HQAEN', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0969-RGKCU', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3005-TYFRD', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3038-PQIUY', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7078-NVFAM', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5433-KYGHE', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7572-KPVKK', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8337-MSSXB', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2082-OJVTK', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4402-FTBXC', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5149-QYTTU', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2558-BUOZZ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5649-ANRML', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2959-EEXWB', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6870-ZWMNX', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0031-PVLZI', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1431-AIDJQ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4332-MUOEZ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5451-MHQOF', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7783-YKGDV', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0927-CNGRH', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4510-PYUSH', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9089-UOWJG', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1493-AMTIE', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6823-SIDFQ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1247-QBVSH', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6804-GDMOI', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5402-HTOTQ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6379-RXJRQ', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2796-UUZZO', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0784-GTUUK', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9674-EHPPG', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2239-CFOUJ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3173-NVMPX', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0754-UKWQP', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8221-HVAYI', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8645-KOMJQ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2242-MFOTG', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9798-OPFEM', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2636-ALXXZ', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5043-TRZWM', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2050-ONYDQ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0851-DFJKB', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8993-IZEUX', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4013-TLDHQ', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1216-JWVUX', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9767-FFLEM', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0621-CXBKL', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1963-SVUCV', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1086-LXKFY', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5266-PFRQK', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9027-TMATR', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0696-UKTOX', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2737-YNGYW', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1730-VFMWO', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7593-JNWRU', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4189-NAKJS', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6817-WTYHE', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6319-QSUSR', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1660-HSOOQ', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5294-IMHHT', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7853-WNZSY', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7901-HXJVA', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8595-SIZNC', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2636-SJDOU', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5130-YPIRV', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7541-YLXCL', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2612-RRIDN', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7037-MTYVW', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9944-AEXBM', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6701-DHKWQ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9067-YGSCA', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2675-OTVVJ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9025-ZRPVR', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2977-CEBSX', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4936-YPJNK', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8845-LWKGE', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8212-DJRCH', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3120-FAZKD', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7721-JXEAW', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3472-QPRCH', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6733-LRIZX', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0719-SYFRB', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7547-EKNFS', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9861-PDSZP', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2162-FRZAA', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5144-PQCDZ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2197-OMWGI', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0484-FFVBJ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7693-LCKZL', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2266-SJNAT', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9444-JTXHZ', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4201-JMNGR', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3508-VLHCZ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0206-OYVOC', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6834-NXDCA', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2669-QVCRG', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4079-VTGLK', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9728-FTTVZ', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8050-WYBND', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2812-SFXMJ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5606-AMZBO', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4081-DYXAV', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6584-VQMYT', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7798-JVXYM', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7663-CUXZB', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8433-WXGNA', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6828-HMKWP', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2831-EBWRN', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3729-OWRVL', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6645-MXQJT', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2172-EJXVF', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2684-EIWEO', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5233-AOZUF', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4236-XPXAV', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6198-RTPMF', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3580-GICBM', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2311-QYMUQ', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8902-ZEOVF', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9592-ERDKV', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6464-KEXXH', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5256-SKJGO', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5249-QYHEX', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1784-BXEFA', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1262-OPMFY', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9972-VAFJJ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8620-RJPZN', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9522-ZSINC', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2188-SXWVT', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3486-KHMLI', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3115-CZMZD', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7175-NTIXE', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2920-RNCEZ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2516-VQRRV', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2888-ADFAO', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2190-PHBHR', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1254-IZEYF', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2520-SGTTA', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9646-NMHXE', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8749-TZYEC', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9708-KFDBY', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0778-NELLA', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8676-OOQEJ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1580-BMCMR', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7730-IUTDZ', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2351-BKRZW', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3255-GRXMG', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0420-HLGXF', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3292-PBZEJ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7854-FOKSF', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4806-HIPDW', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7233-IOQNP', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8332-OSJDW', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2252-NKNSI', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8200-LGKSR', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6308-CQRBU', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0730-KOAVE', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1897-RCFUM', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0807-ZABDG', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8909-BOLNL', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4322-RCYMT', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5465-BUBFA', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6979-ZNSFF', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0626-QXNGV', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1184-PJVDB', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3863-IUBJR', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0536-ACXIP', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4248-QPAVC', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1032-MAELW', 'No')

INSERT INTO target_info ( customerID, Churn ) VALUES  ('6625-IUTTT', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2055-BFOCC', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8382-SHQEH', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7129-ACFOG', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3727-RJMEO', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5002-GCQFH', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1697-LYYYX', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4702-IOQDC', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8439-LTUGF', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6650-BWFRT', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7247-XOZPB', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5895-QSXOD', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2876-VBBBL', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3345-JHUEO', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8963-MQVYN', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8397-MVTAZ', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8481-YYXWG', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4140-WJAWW', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8958-JPTRR', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5271-DBYSJ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5844-QVTAT', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3259-QMXUN', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8695-ARGXZ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5982-XMDEX', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3754-DXMRT', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7395-IGJOS', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5125-CNDSP', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7980-MHFLQ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5977-CKHON', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8670-ERCJH', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3077-RSNTJ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8896-BQTTI', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6839-ITVZJ', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7765-LWVVH', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6664-FPDAC', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4211-MMAZN', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0365-BZUWY', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3518-PZXZQ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3638-VBZTA', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2481-SBOYW', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0308-IVGOK', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7876-BEUTG', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1663-MHLHE', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5153-RTHKF', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6734-PSBAW', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9052-DHNKM', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9494-BDNNC', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1471-GIQKQ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9795-NREXC', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3043-TYBNO', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3318-ISQFQ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4800-CZMPC', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7100-FQPRV', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3082-WQRVY', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1399-OUPJN', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8338-QIUNR', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2509-TFPJU', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6516-NKQBO', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1226-UDFZR', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8098-LLAZX', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8663-UPDGF', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9572-WUKSB', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6100-FJZDG', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3635-JBPSG', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1956-YIFGE', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7996-BPXHY', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2235-DWLJU', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8883-GRDWQ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0784-ZQJZX', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0380-NEAVX', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5552-ZNFSJ', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8191-XWSZG', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3148-AOIQT', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9710-NJERN', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5458-CQJTA', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2072-ZVJJX', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3196-NVXLZ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7005-CCBKV', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7359-SSBJK', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3799-ISUZQ', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5651-YLPRD', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6000-UKLWI', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4432-ADRLB', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6778-JFCMK', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2220-IAHLS', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7029-IJEJK', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8033-ATFAS', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9921-ZVRHG', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3701-SFMUH', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0428-AXXLJ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0943-ZQPXH', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4937-QPZPO', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7359-WWYJV', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3524-WQDSG', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2000-MPKCA', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1866-DIOQZ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5382-SOYZL', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0666-UXTJO', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7693-QPEFS', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6211-WHMYA', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0723-FDLAY', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3640-JQGJG', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7979-CORPM', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4393-GEADV', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6586-MYGKD', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6230-BSUXY', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0640-YJTPY', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7625-XCQRH', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1699-HPSBG', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1291-CUOCY', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7234-FECYN', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6719-OXYBR', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8992-VONJD', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9140-CZQZZ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7129-CAKJW', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3261-CQXOL', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3453-RTHJQ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8173-RXAYP', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2672-HUYVI', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4742-TXUEX', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4749-OJKQU', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7852-LECYP', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2325-NBPZG', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6898-MDLZW', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7049-GKVZY', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6296-DDOOR', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3212-KXOCR', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6897-UUBNU', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4061-UKJWL', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7890-VYYWG', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3282-ZISZV', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5275-SQEIZ', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4088-YLDSU', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3211-AAPKX', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4632-PAOYU', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7426-WEIJX', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0504-HHAPI', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4274-OWWYO', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1731-TVIUK', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8593-WHYHV', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7636-OWBPG', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1585-MQSSU', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7033-CLAMM', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6178-KFNHS', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8292-ITGYJ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9537-VHDTA', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9225-BZLNZ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7272-QDCKA', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4138-NAXED', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1453-RZFON', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8792-AOROI', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5056-FIMPT', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5572-ZDXHY', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7010-ZMVBF', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7994-XIRTR', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5228-EXCET', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1170-SASML', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8165-CBKXO', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9451-WLYRI', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9039-ZVJDC', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5148-HKFIR', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9318-NKNFC', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7931-PXHFC', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6131-JLWZM', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7529-ZDFXI', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7167-PCEYD', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4680-KUTAJ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1629-DQQVB', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7964-VEXDG', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6615-ZGEDR', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4458-KVRBJ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9600-NAXZN', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7492-TAFJD', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3050-RLLXC', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0550-DCXLH', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5156-UMKOW', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4526-RMTLL', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9985-MWVIX', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5882-CMAZQ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4830-FAXFM', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4472-LVYGI', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3173-WSSUE', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7511-YMXVQ', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9747-DDZOS', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3896-ZVNET', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6837-BJYDQ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9801-GDWGV', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7710-JSYOA', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5478-JJVZK', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9828-QHFBK', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4079-ULGFR', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5804-JMYIO', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2085-JVGAD', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5377-NDTOU', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7016-NVRIC', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1642-HMARX', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5811-IWXYM', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0411-EZJZE', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6772-KSATR', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8207-DMRVL', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3223-WZWJM', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6357-JJPQT', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2792-VPPET', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6168-YBYNP', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8059-UDZFY', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0869-PAPRP', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1482-OXZSY', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5175-WLYXL', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9489-JMTTN', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9027-YFHQJ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4827-LTQRJ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3363-DTIVD', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3199-XGZCY', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4298-OYIFC', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6994-FGRHH', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2404-JIBFC', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1015-OWJKI', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7233-DRTRF', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4860-YZGZM', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4854-CIDCF', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9507-HSMMZ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5115-GZDEL', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5539-HIVAK', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3982-DQLUS', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4957-SREEC', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2338-BQEZT', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7695-PKLCZ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4475-NVTLU', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8778-LMWTJ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9298-WGMRW', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9974-JFBHQ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7101-HRBLJ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9978-HYCIN', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4745-LSPLO', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1038-RQOST', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3144-AUDBS', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1371-OJCEK', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8566-YPRGL', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7860-UXCRM', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7993-PYKOF', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6616-AALSR', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4955-VCWBI', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9555-SAHUZ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1612-EOHDH', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1755-RMCXH', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2959-MJHIC', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0136-IFMYD', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9398-MMQTO', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8707-HOEDG', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2391-SOORI', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7047-FWEYA', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7615-ESMYF', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9565-FLVCG', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0480-BIXDE', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8992-OBVDG', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6339-RZCBJ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1792-UXAFY', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6139-ZZRBQ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9644-KVCNC', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1492-KGETH', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3347-YJZZE', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6260-ONULR', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5093-FEGLU', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6892-BOGQE', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4878-BUNFV', 'No')

INSERT INTO target_info ( customerID, Churn ) VALUES  ('9769-TSBZE', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9184-GALIL', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4121-AGSIN', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7945-HLKEA', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2088-IEBAU', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0657-DOGUM', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9137-UIYPG', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7649-SIJJF', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5095-ETBRJ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2800-QQUSO', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5827-MWCZK', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0384-LPITE', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8565-WUXZU', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7739-LAXOG', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3842-IYKUE', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0348-SDKOL', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2192-OZITF', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0867-MKZVY', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4983-CCWMC', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6369-MCAKO', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1518-VOWAV', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4948-WBBKL', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7041-TXQJH', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0812-WUPTB', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5376-PCKNB', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0137-OCGAB', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8400-WZICQ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3422-WJOYD', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5762-TJXGK', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8720-RQSBJ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4522-XRWWI', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0701-RFGFI', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9909-DFRJA', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3451-VAWLI', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3413-BMNZE', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3657-COGMW', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8823-RLPWL', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8868-GAGIO', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9851-QXEEQ', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7609-YBPXG', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5180-UCIIQ', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3084-DOWLE', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8198-RKSZG', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8857-CUPFQ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3546-GHEAE', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6614-FHDBO', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4958-GZWIY', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4373-VVHQL', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5839-SUYVZ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9481-SFCQY', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5376-DEQCP', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5872-OEQNH', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7409-KIUTL', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7779-ORAEL', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0887-HJGAR', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3886-CERTZ', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0895-LNKRC', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5501-TVMGM', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8096-LOIST', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1904-WAJAA', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2612-PHGOX', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8563-OYMQY', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8455-HIRAQ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0516-QREYC', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2371-JUNGC', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8017-UVSZU', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8966-KZXXA', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2834-JRTUA', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8295-FHIVV', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8543-MSDMF', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5380-XPJNZ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4367-NUYAO', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9399-APLBT', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2115-BFTIW', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0902-XKXPN', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2974-GGUXS', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6211-WWLTF', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7526-BEZQB', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4804-NCPET', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4660-IRIBM', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1422-DGUBX', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0899-WZRSD', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8053-WWDRO', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8314-DPQHL', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3648-GZPHF', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6847-KJLTS', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7318-EIVKO', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3137-NYQQI', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9365-SRSZE', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('2876-GZYZC', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('1936-CZAKF', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8908-SLFCJ', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3739-YBWAB', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3296-SILRA', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8215-NGSPE', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8652-YHIYU', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6386-SZZKH', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('9076-AXYIK', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('3278-FSIXX', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6408-WHTEF', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('6032-IGALN', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('0684-AOSIH', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('5982-PSMKW', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('8044-BGWPI', 'No')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('7450-NWRTR', 'Yes')
INSERT INTO target_info ( customerID, Churn ) VALUES  ('4795-UXVCJ', 'No')

In [23]:
cur.execute('commit;')

In [24]:
cur.close()

The next cell comes in handy during testing

In [45]:
cur.execute('rollback;')